[Signature]
ID=bQd6HHhXFPUvx4qLkSHGMyDl00000000
[Version]
ID=G2715 Version: A.00.00
[General]
Type=0
Run Duration=900.00
NoLimit=1
NoMSD=0
PeakWidth=12.00
ScanSpeedOverride=0
Solvent Delay=0.00
Tune File=atunes.tun
Polarity=0
IonizationMode=5
Group Ions=1
Acq Mode=2
Zones=3
Scan Groups=1
Data Curves=0
Data Curve Rate=1000
[DynamicParm 1]
GlobalId=11
Enable=0
DynamicValues=118.05,82.00,322.05,102.00,622.03,170.00,922.01,216.00,1521.97,250.00,2121.93,284.00
[Zone 1]
ID=6
On=1
Soft Max=350.00
Set Point=325.00
Type=0
[Zone 2]
ID=13
On=1
Soft Max=13.00
Set Point=8.00
Type=0
[Zone 3]
ID=14
On=1
Soft Max=60.00
Set Point=50.00
Type=0
[Ions 1]
Group Name=Group 1
Start Time=0.00
Resolution=0
Gain=1.0
Fragmentor=70
Plot Index 1=0
Plot Index 2=0
Number of Ions=1
Ion 1=195.0,1000
[Scan 1]
Start Time=0.00
Low Mass=400.0
High Mass=1800.0
Threshold=100
Sampling=8
Stepsize=0.15
Gain=1.5
Fragmentor=125
Low Plot 1=50.0
High Plot 1=550.0
Low Plot 2=50.0
High Plot 2=550.0
[Filters]
Mass Type=1
Mass Param=0.300
Mass Sigma=2.00
Time Type=1
Time Param=6.000
Time Sigma=2.00
[Plot]
Plot Type 1=0
Plot Type 2=1
[Parameters]
ID 1=1
Mode 1=1
Value 1=4000.000000
ID 2=5
Mode 2=1
Value 2=4000.000000
ID 3=7
Mode 3=1
Value 3=4.000000
ID 4=8
Mode 4=1
Value 4=40.000000
ID 5=-1
Mode 5=0
Value 5=0.000000
[Time Events]
Number Events=0
