[Signature]
ID=DOEwYSloDL5gRFt4jMZxRD2n00000000
[Version]
ID=G2715 Version: A.05.01
[General]
Type=0
Run Duration=900.00
NoLimit=0
NoMSD=0
PeakWidth=4.20
ScanSpeedOverride=0
Solvent Delay=0.00
Polarity=0
IonizationMode=5
Group Ions=1
Tune File=atunes.tun
Acq Mode=0
Zones=3
Scan Groups=1
Data Curves=0
Data Curve Rate=0
[Parameters]
ID 1=1
Mode 1=1
Value 1=3500.000000
ID 2=5
Mode 2=1
Value 2=4000.000000
ID 3=7
Mode 3=1
Value 3=4.000000
ID 4=8
Mode 4=1
Value 4=40.000000
ID 5=-1
Mode 5=0
Value 5=0.000000
[DynamicParm 1]
GlobalId=11
Enable=0
DynamicValues=
[Zone 1]
ID=6
On=1
Soft Max=350.00
Set Point=350.00
Type=0
[Zone 2]
ID=13
On=1
Soft Max=13.00
Set Point=10.00
Type=0
[Zone 3]
ID=14
On=1
Soft Max=60.00
Set Point=25.00
Type=0
[Ions 1]
Group Name=Group 1
Start Time=0.00
Resolution=0
Gain=1.0
Fragmentor=70
Plot Index 1=0
Plot Index 2=0
Number of Ions=1
Ion 1=195.0,400
[Scan 1]
Start Time=0.00
Low Mass=100.0
High Mass=500.0
Threshold=20
Sampling=7
Stepsize=0.10
Gain=1.0
Fragmentor=70
Low Plot 1=100.0
High Plot 1=500.0
Low Plot 2=100.0
High Plot 2=500.0
[Time Events]
Number Events=0
[Filters]
Mass Type=1
Mass Param=0.300
Mass Sigma=2.00
Time Type=1
Time Param=2.100
Time Sigma=2.00
[Plot]
Plot Type 1=0
Plot Type 2=1
