!******************************************************************************
!*
!* FILE:  dgmsutil.mac 
!*  
!*
!* 
!* DESCRIPTION:
!*    generic macros for test utilility purpose
!*
!* MACROS:
!*       dgMsSwVersion
!*       dgMsPrintError
!*
!* Display Manager Macros:
!*       dgMsTestInfo         Set up a test display definition
!*       dgMsTestDateTime$    Format date and time of test
!*       dgMsGetTestResults$  Display results after test run
!*       dgMsCopyResultTable  Copy test results to display table
!*       dgMsDisplayTest      Reload from file
!*       dgMsPrintTest        Print an MS diagnosis test
!*
!* Test Tools:
!*       dgMsGetDynamicsParmTab
!*       dgMsReadDynParm
!*       dgMsGetTestParmsTab
!*       dgMsSetTestParms
!*       dgMsRestoreDynamic
!*       dgMsGetParmLimitsTab
!*
 dgMSutilVer$ = "$Header: /cag/triath1b/partsmac/diag/dgmsutil.mac 1.30 2003-04-15 13:49:24-07 pcormia Exp $"
 verIx = instr(dgMsUtilVer$, ".mac") + 5
 dgMsUtilVer$ =  dgMsUtilVer$[verIx:VerIx + instr(dgMsUtilVer$[VerIx:len(dgMsUtilVer$)]," ") - 1] 
 remove verIx
!*
!******************************************************************************

!****************************************************************************
NAME dgMsSwVersion
!
! returns seaweed version number digits
!****************************************************************************
  LOCAL i, k

  i=InStr(_Version$, "SW ")
  k=InStr(_Version$, " Copyright")
  IF i>0 and i+5<k THEN
    return VAL(_Version$[i+5:k])
  ENDIF

  return 0
ENDMACRO
!****************************************************************************

!****************************************************************************
NAME dgMsPrintError
!  PARAMETER command$ default ""
!
!****************************************************************************
  ! setverbose 0
  print ">>>>>>>>>>>>>>>>>>>>>>>"
  print ">> ERROR:   ", _ERROR
  print ">> Command: ", _ERRCMD$
  print ">> Message: ", _ERRMSG$
  print ">> Macro  : ", _ERRMacro$
  print ">> Line   : ", _ERRLine
  print ">> File   : ", _ERRFile$
  print ">>>>>>>>>>>>>>>>>>>>>>>"

ENDMACRO
!***************************************************************************!

!***************************************************************************!
NAME dgMsTestInfo

PARAMETER NLSChartTitle$ DEFAULT "MSD"
PARAMETER DispCommand$   DEFAULT ""
PARAMETER MacroVers$     DEFAULT "<none>"
PARAMETER RegObj$        DEFAULT "RESULT_REG[1]"
! This macro adds instrument identification information to RESULT_REG
!***************************************************************************!
LOCAL  SWRev$, SCRev$, SerialNo$, ChartTitle$, regName$, RegNum, Reg
LOCAL  QP$, found

   ON ERROR dgMsPrintError

   If InStr(RegObj$,"[") <>0 then
     RegName$=RegObj$[ 1 : InStr(RegObj$,"[")-1 ]
    RegNum=VAL( RegObj$[ InStr(RegObj$,"[")+1 : InStr(RegObj$,"]")-1 ]  )
   else
     RegName$=RegObj$
    RegNum=1
   endif

   evaluate "Reg=RegSize("+RegName$+")"
   if Reg<RegNum then
     print "WARNING from dgMsTestInfo: the register "+ RegObj$ +" doesn't exist!"
     return
   endif

   ! get software rev
   SWRev$ = _Version$
   pos = instr(_Version$,"Copyright")
   SWRev$ = SWRev$[1:pos-1]

   ! get SmartCard rev and serial number
   SCRev$ = dgMsQuery$("*idn?",4)
   SerialNo$ = dgMsQuery$("config:snum?")
   
   ! get quad polarity
   QP$ = dgMSQuery$("msc:parm? quadpol")

   ChartTitle$=NlsMsDiag$(NlsChartTitle$)
   print " "

   ! Create object header items
   evaluate "SetObjHdrText " + RegObj$ + ", ""MSSCVersion"", """  + \
                               SCRev$ +""""
   evaluate "SetObjHdrText " + RegObj$ + ", ""MacroVersion"", """ + \
                               MacroVers$ +""""

   evaluate "SetObjHdrText " + RegObj$ + ", ""AcqInstName"", """  + \
                               _InstName$ +""""
   evaluate "SetObjHdrText " + RegObj$ + ", ""AcqVersion"", """   + \
                               SWRev$ +""""
   
   ! add necessary test information
   evaluate "SetObjHdrText " + RegObj$ + ", ""TuneFile"", """ + \
                               _DiagTuneFile$ +""""
   !evaluate "SetObjHdrText " + RegObj$ + ", ""Instrument"",  ""MSD"""
   evaluate "SetObjHdrText " + RegObj$ + ", ""Instrument"",  """ + \
                               _InstName$ +""""
   evaluate "SetObjHdrText " + RegObj$ + ", ""SerialNumber"", """ + \
                               SerialNo$ +""""
   evaluate "SetObjHdrText " + RegObj$ + ", ""QuadPol"", """ + \
                               QP$ +""""                               
   evaluate "SetObjHdrText " + RegObj$ + ", ""SampleName"", """  + \
                               ChartTitle$ +""""
   evaluate "SetObjHdrText " + RegObj$ + ", ""FileName"", """" "
   evaluate "SetObjHdrText " + RegObj$ + ", ""DispCommand"", """ + \
                               DispCommand$ +""""

   evaluate "found = ObjHdrType("+ RegObj$ +", ""DiagTime"") "
   if found = 99 then
     evaluate "SetObjHdrText " + RegObj$ + ", ""DiagTime"", """ + \
                                 time$(1) +""""
     evaluate "SetObjHdrText " + RegObj$ + ", ""DiagDate"", """ + \
                                 date$(1) +""""
   endif

   if len(_Operator$) < 1 THEN
     evaluate "SetObjHdrText " + RegObj$ + ", ""Operator"",""none"" "
   else
     evaluate "SetObjHdrText " + RegObj$ + ", ""Operator"", """ + \
                                 _Operator$ +""""
   endif

ENDMACRO            ! end dgMsTestInfo
!***************************************************************************!

!****************************************************************************
NAME   dgMsTestDateTime$

PARAMETER RegName$
PARAMETER Screen$
PARAMETER Table$
!
!   DESCRIPTION
!  Format a string with actual date and time and write it to a results
!  table.
!
!   RETURN
!       Empty string
!
!****************************************************************************
   LOCAL string$, regnum, exist, date$, time$

   evaluate "regnum=RegSize("+RegName$+")"
   IF regnum<1 THEN
      PRINT "ERROR: No Input Register!"
      RETURN ""
   ENDIF

   ON ERROR print "error in datetime access"
   evaluate "exist=ObjHdrType("+ RegName$+ ",DiagDate)"
     IF exist = 99 THEN ! Entry does not exist
        evaluate "SetObjHdrText "+RegName$+", DiagDate, date$(1)"
        evaluate "SetObjHdrText "+RegName$+", DiagTime, time$(1)"
      ENDIF
   evaluate "date$=ObjHdrText$("+RegName$+", DiagDate)"
   evaluate "time$=ObjHdrText$("+RegName$+", DiagTime)"

   string$ = "Date: " + date$ + ";  Time: " + time$
    
   DIAG_DispMgrSet Screen$, Table$, "DateTime", "text", string$
   
   RETURN ""
    
ENDMACRO
!****************************************************************************

!****************************************************************************
NAME dgMsGetTestResults$

PARAMETER Chart$
PARAMETER Table$
PARAMETER PrintMac$
! displays the result table and a chart of all collected data points
! returns the evaluated result of the noise test.
! call: print dgMsGetTestResults$("NoiseChart", "NoiseRes", 
!                                 "dgMsPrintNoiseTest")
!****************************************************************************

  LOCAL i, ObjNo, RowNo, Result$, FailedResult$
  LOCAL ret, WinNum

  ! print "dgMsGetTestResults$", Chart$,",", Table$,",", PrintMac$

  ! FailedResult$ = NlsMsDiag$( "Failed")
  FailedResult$ = "Failed: macro error in dgMSGetTestResults"
  ON ERROR RETURN FailedResult$

  IF RegSize(RESULT_REG) < 1 THEN
    RETURN FailedResult$
  ENDIF

  ! See if DiagDispReg needs patching (for ion optics chart)
  if (ConvertText$(lower, Chart$) = "ionopchart") then
     dgDispRegFix
  endif

  ! Initial overall Test Result 
  if ObjHdrType(RESULT_REG[1], "TestResAll") = 99 then
    SetObjHdrText RESULT_REG[1], "TestResAll", "Failed: Error"
  endif

  ! based on RESULT_REG: clear display and show table
  DIAG_DispMgr "MsdDiag", Table$, 0
  ! Modify the NoiseRes display description table in _config[3]
  ! This should be changed in the default config.reg
  if ObjHdrType(_Config[3], "NoiseResDDT") = 4 then
     SetTabVal _Config[3], NoiseResDDT, 1, "Width", 35
     SetTabVal _Config[3], NoiseResDDT, 2, "Width", 35
  endif
 
  ! copies the register to DiagTestResult  
  ret=dgCopyTestResults(RESULT_REG, "MsdDiag", Table$, "MSD", PrintMac$)
  !delreg RESULT_REG
  dgMsCopyResultTable "MsdDiag", Table$, RESULT_REG

  if ret = 0 then
    RETURN FailedResult$
  endif

  ! look for a "FAILED" in the results table

  if ObjHdrType(DiagTestResult[1],testresulttab) = 4 then
    if RowByText(DiagTestResult[1],TestResultTab,,"Result","in","F") \
                                                                   <> -1 then
       Result$ = NlsMsDiag$("Failed")
    else
       if RowByText(DiagTestResult[1],TestResultTab,,"Result","in","ERROR") \
                                                                   <> -1 then
          Result$ = FailedResult$
       else
          Result$ = NlsMsDiag$("Passed")
       endif
    endif
  else
     Result$ = FailedResult$
  endif
  SetObjHdrText DiagTestResult[1], "TestResAll", Result$

  ! show chart when no error detected & a chart is to be printed
  !4-02PR(PVCS1758) "NoDraw" indicates there is either no chart or a data problem; so don't draw chart
  if objhdrtype(DiagTestResult[1], "nodraw") = 99 then
    ! display chart and delete first object
    WinUpdate off
    ! Make sure the x axis is visible
    RowNo = RowByText(DiagDispReg[1], "ScreenTab",, "EntryID", "=", \
                                      Chart$)
    if RowNo > 0 then
       WinNum = TabVal(DiagDispReg[1], "ScreenTab", RowNo, "WinID")
       if WinNum > 0 then
          SetTabVal _Config[1], Window, WinNum, "XAxisStyle", 1
       endif
    endif
    
    DIAG_DispMgr MsdDiag, Chart$
    
    ! workaround for QE test display
    if Chart$ = "QEChart1" then
       if RowNo > 1 then
          WinNum = TabVal(DiagDispReg[1], "ScreenTab", RowNo, "WinID")
          SetTabVal _Config[1], Window, WinNum, "XAxisStyle", 11
          evaluate "Draw " + val$(WinNum) + ", DiagTestResult" + \
                    ObjHdrText$(DiagTestResult, "DrawChart1")
       endif
    endif
    WinUpdate on

  else
    !4-02PR removed:    Generate Error 55555, "Undefined error in MSD Test!"
    !4-02PR will get here with "LampChart"(no chart), and if bad data then also "IonOpChart"
	print "no chart available"     ! log this event
  endif

  RETURN result$
  
ENDMACRO
!****************************************************************************

!****************************************************************************
NAME dgMsCopyResultTable

  PARAMETER Screen$
  PARAMETER Table$
  PARAMETER RegName$  ! RESULT_REG for first display
                      ! DiagTestResult for reload test result from file
!****************************************************************************
  LOCAL reg, RegMax, i, title$, result$, text$, rowmax
  LOCAL PassedResult$, FailedResult$, rowoffset, ok, unit$

  RegMax=RegSize(DiagDispReg)
  Screen$=ConvertText$(UPPER,Screen$)
  i=1
  reg=0

  ! find screen register number in Display Manager
  while (i <= RegMax) do
    title$=ConvertText$(UPPER, ObjHdrText$(DiagDispReg[i], "Title"))
    if (Screen$=Title$) then
     reg=i
     i=RegMax+1 
    endif
    i=i+1
  endwhile

  if reg>0 then

    PassedResult$= NlsMsDiag$("Passed")
    FailedResult$= NlsMsDiag$("Failed")

   evaluate "rowmax=TabHdrVal("+RegName$+", TestResultTab, NumberOfRows)"
   rowoffset=TabHdrVal(DiagDispReg[reg], "TO"+table$, NumberOfRows)
  
    WinUpdate OFF

   for i=1 To rowmax
      InsTabRow DiagDispReg[reg], "TO"+table$

      ! unit
     evaluate "ok=tabcoltype("+RegName$+", ""TestResultTab"", ""unit"")"
     if ok=0 then
       evaluate "Text$=TabText$("+RegName$+", ""TestResultTab"", i, ""unit"")"
       SetTabText DiagDispReg[reg], "TO"+table$, i+rowoffset, "unit", unit$
      !print "row:",i+rowoffset,"unit=", unit$
     else
       unit$=""
     endif

      ! text
     evaluate "ok=tabcoltype("+RegName$+", ""TestResultTab"", ""text"")"
     if ok=0 then
       evaluate "Text$=TabText$("+RegName$+", ""TestResultTab"", i, ""Text"")"
       SetTabText DiagDispReg[reg], "TO"+table$, i+rowoffset, "Text", Text$
      !print "row:",i+rowoffset,"text=", text$
     endif

      ! Range
     evaluate "ok=tabcoltype("+RegName$+", ""TestResultTab"", ""Range"")"
     if ok=0 then
       evaluate "Text$=TabText$("+RegName$+", ""TestResultTab"", i, ""Range"")"
       SetTabText DiagDispReg[reg], "TO"+table$, i+rowoffset, "dRange", \
                   Text$+" "+unit$
      !print "row:",i+rowoffset,"Range=", text$
     endif

      ! Value
     evaluate "ok=tabcoltype("+RegName$+", ""TestResultTab"", ""Value"")"
     if ok=0 then
       evaluate "Text$=TabText$("+RegName$+", ""TestResultTab"", i, ""Value"")"
       SetTabText DiagDispReg[reg], "TO"+table$, i+rowoffset, "dValue", \
                  Text$+" "+unit$
      !print "row:",i+rowoffset,"Value=", text$
     endif

      ! Result
     evaluate "ok=tabcoltype("+RegName$+", ""TestResultTab"", ""Result"")"
     if ok=0 then
       evaluate "result$=TabText$("+RegName$+", ""TestResultTab"", i, " + \
                  """Result"")"
       if result$="FAILED" then
         SetTabText DiagDispReg[reg], "TO"+table$, i+rowoffset, "Result", \
                     FailedResult$
       else; if result$="PASSED" then
         SetTabText DiagDispReg[reg], "TO"+table$, i+rowoffset, "Result", \
                     PassedResult$
       else
         SetTabText DiagDispReg[reg], "TO"+table$, i+rowoffset, "Result", \
                     Result$
       endif;endif
      !print "row:",i+rowoffset,"Result=", result$
     endif
    next i
    WinUpdate ON
  endif

ENDMACRO
!****************************************************************************

!****************************************************************************
NAME dgMsDisplayTest

  PARAMETER Chart$
  PARAMETER Table$
  PARAMETER Title$ 
!
! displays the noise result table and a chart of all collected data points
! from a *.dgr file.
! call   dgMsDisplayTest "NoiseChart", "NoiseRes", "NoiseReport"
!****************************************************************************
  LOCAL FileNAME$, TabRow, WinID, NlsTitle$, SampleNAME$, i

  ON ERROR i=1

  FileNAME$   = ObjHdrText$(DiagTestResult, "FileName")
  NlsTitle$   = NlsMsDiag$(Title$)
  SampleNAME$ = ObjHdrText$(DiagTestResult, "SampleName")
  !print "dgDisplayTest: ",FileName$

  ! show table and clear display based on RESULT_REG
  DIAG_DispMgr "MsdDiagStrd", Table$, 0
  dgMsCopyResultTable "MsdDiagStrd", Table$, DiagTestResult
  ! set win title with file name
  TabRow = DIAG_GetScreenTabRow( "MsdDiagStrd", Table$)
  WinID = TabVal(diagdispreg,"ScreenTab",TabRow,WinID)
  !print "SetWinTitle ",WinID, NlsTitle$,  " (", FileName$,")"
  SetWinTitle WinID, NlsTitle$ + " (" + FileName$ +")"


  !display chart  when no error detected
  IF ObjHdrType(DiagTestResult[1], "NoDraw") = 99 then
    ! display chart and delete first object
    WinUpdate off
    DIAG_DispMgr MsdDiag, Chart$
    ! workaround for QE test display
    if Chart$ = "QEChart1" then
       RowNo = RowByText(DiagDispReg[1], "ScreenTab",, "EntryID", "=", \
                                         "QEChart1")
       if RowNo > 1 then
          WinNum = TabVal(DiagDispReg[1], "ScreenTab", RowNo, "WinID")
          OldXaxisStyle = TabVal(_Config[1], Window, WinNum, "XAxisStyle")
          SetTabVal _Config[1], Window, WinNum, "XAxisStyle", 11
          evaluate "Draw " + val$(WinNum) + ", DiagTestResult" + \
                    ObjHdrText$(DiagTestResult, "DrawChart1")
       endif
    endif
    TabRow = DIAG_GetScreenTabRow( "MsdDiag", Chart$)
    WinID = TabVal(diagdispreg,"ScreenTab",TabRow,WinID)
    !print "SetWinTitle ",WinID, NlsTitle$, SampleNAME$, " (", FileNAME$,")"
    SetWinTitle WinID, SampleNAME$ + " (" + FileNAME$ +")"
    WinUpdate on
  ENDIF

ENDMACRO
!****************************************************************************

!****************************************************************************
NAME dgMsPrintTest

PARAMETER ReportTitle$        ! "NoiseReport"
PARAMETER TestResults$        ! "NoiseResults"
PARAMETER Chart1$             ! "NoiseChart"
PARAMETER Chart2$      Default "" ! "NoiseChart2"
PARAMETER drawWinSize  Default 16.3
PARAMETER WinPerPage   Default  3    
PARAMETER TextF$       Default "%-38s"
PARAMETER RangeF$      Default "%13s"
PARAMETER ValueF$      Default "%15s"
PARAMETER ResultF$     Default "%+8s"
!****************************************************************************
!
!   DESCRIPTION
!    MSD test print out. 
!       visible page size: 78 characters and 58 lines.
!       logical page size: 78 characters and 61 lines.             
!     1. page: title (log. line 1)
!              test info (log. line  2 - 7)
!              optional* File name (Log. Line 8) * if header item exists
!              optional** Two blank lines
!              optional** draw window title (Log Line 10 or 11).
!              optional** draw window (Log. Line 11 or 12)
!               (**: if ObjHdr NoDraw not exists and register size > 0 )
!              optional *** two blank lines or new page 
!              optional *** draw table 
!               (***: if table TestResultTab does exist and register size > 0 )
!     x. page: start on log line 2.
!
!     Draw Window Size:
!     The draw window size for the first page will be (61-12)/WinPerPage.
!     and for all following (61-2)/(WinPerPage+1) to fill the page print out.
!     If a additional draw window doesn't fit on the page the window per page
!     variable will not be increased.
!     
!    xxxxxF$:
!     contains the sprintf format of the corresponding column in the 
!     testresulttab.
!    the emtpy string will suppress the print out of the corresponding column.
! 
!     example: 
!        (first load a msd analyzer noise test result)
!        dgMsPrintTest NoiseReport, NoiseResults, NoiseChart, , 14.7, 3, \ 
!                       "%-40s", "", "", "%-10s"
!
!   RETURN
!    <none>
!****************************************************************************
LOCAL   line$, Text$, TabHeader$, unit$
LOCAL   MinInt, ToRow, FromRow, MaxRow
LOCAL   RegObj, regnum , drawRegMin, drawRegMax, rownum
LOCAL   yRange$, drawCmd$, isPRTestEnv
LOCAL   i, xl, Reg, RegMax, xMin, xMax, PageSize
LOCAL   HeaderFormat$, Dashes$, Header$

   ON ERROR goto EndPrintOut

   isPRTestEnv = Check(Variable, PRTestVer$)
   
   ! define header and dash line
   Header$ = NlsMsDiag$(ReportTitle$)
   HeaderFormat$ = "%%%%%%%%%%%%%%%%% %%%/"
   Dashes$ = \
    "--------------------------------------------------------------------------"
   ! 12345678901234567890123456789012345678901234567890123456789012345678901234
   !          1         2         3         4         5         6         7    

   GetCurrentPrinterSetup                   !3-02PR utilize current printer setup
   On Error print _ErrMsg$
   if RegSize(DiagTestResult) < 1 then
      RETURN
   endif

   PageSize= YLogMax()+1            !3-02PR fix#243 (don't set to constant: 60 here)
   if isPRTestEnv = 0 then
       ! begin print out and set error trap to close printer device
       BeginJob ,,XMax()-13, YMax()-1

       SetHeader Header$, XLogMax()/2 - len(Header$)/2
       SetMargin 2, 2, 2
       SetFooter PageFooterLine$()

       On Error CloseDeviceBeforeOpenDevice    !3-02PR recover and continue
       OpenDevice "Printer" As #5
       On Error print _ErrMsg$

    else
       MfgHeaderMain Header$, 1
       SetFooter "    dgNoise.mac v. " + dgNoiseVer$
    endif
   
    ! test info
    !===========
    if isPRTestEnv = 0 then
       Print Using #5, HeaderFormat$, NlsMsDiag$("InstrumColon"), \
                       ObjHdrText$ (DiagTestResult,"Instrument")
       Text$ = ObjHdrText$ (DiagTestResult,"TuneFile") 
       if ObjHdrType(DiagTestResult, "IonMode") <> 99 then
          Text$ = Text$ + "    " + ObjHdrText$ (DiagTestResult[1], "IonMode") + \
                  " " + ObjHdrText$ (DiagTestResult[1], "IonPol")
       endif
       Print Using #5, HeaderFormat$, NlsMsDiag$("TuneFileColon"), Text$ 


       ! Quad polarity for noise test
       if InStr(ConvertText$(lower, Chart1$),"noise") > 0 then
          Print Using #5, HeaderFormat$, "Quad Polarity",  \
                          ObjHdrText$(DiagTestResult,"QuadPol")
       endif
       Print Using #5, HeaderFormat$, NlsMsDiag$("SerNoColon"), \
                       ObjHdrText$ (DiagTestResult,"SerialNumber")
       Print Using #5, HeaderFormat$, NlsMsDiag$("OperColon"), \
                       ObjHdrText$( DiagTestResult,"Operator")
       Print Using #5, HeaderFormat$, NlsMsDiag$("DateColon"), \
                       ObjHdrText$ (DiagTestResult,"DiagDate")
       Print Using #5, HeaderFormat$, NlsMsDiag$("TimeColon"), \
                       ObjHdrText$ (DiagTestResult,"DiagTime")

       ! print optional file name of loaded *.dgr file
       if  ObjHdrText$ (DiagTestResult,"FileName") <> ""  THEN
           Print Using #5, HeaderFormat$, NlsMsDiag$("FileColon"), \
                           ObjHdrText$ (DiagTestResult,"FileName")
       endif
    endif
    
    !Print Using #5, "/" ! space between test info and draw window (or table)
    xl = XLoc()

   ! drawing register data blocks only if NoDraw doesn't exist
   !==========================================================
   if ObjHdrType(DiagTestResult, "NoDraw")=99 then
      ! Make sure x axis gets labelled right
      if InStr(ConvertText$(lower, Chart1$), "qechart1") > 0 then
         SetTabVal _Config[1], Window, DIAG_WinEnd + 1, "XAxisStyle", 11
      else
         SetTabVal _Config[1], Window, DIAG_WinEnd + 1, "XAxisStyle", 1
      endif

      ! check if a draw information already exists
      ! if yes go and draw with this information otherwise use
      ! default drawing procedure
      if ObjHdrType (DiagTestResult, "DrawChart1") <> 99 then
        for i=1 to 2
           if ObjHdrType (DiagTestResult, "DrawChart"+Val$(i)) <> 99 then
              DrawCmd$ = ObjHdrText$(DiagTestResult[1], "DrawChart"+val$(i))
              SetWinPrintParams DIAG_WinEnd + 1,, 74/XLogMax(), \
                                drawWinSize / PageSize
              ! print Chart Title
              Print Using #5, "/" ! space between draw window
              evaluate "Print #5, NlsMsDiag$(Chart"+Val$(i)+"$)"
              ! get drawing command
              ! print "DrawWinSize= ", val$(drawwinsize) + "; pagesize= " + \
              !     val$(pagesize)
              SetTabVal _Config[1], Window, DIAG_WinEnd + 1, "XAxisStyle", 11
              evaluate "Draw " + VAL$(DIAG_WinEnd + 1) + \
                       ", DiagTestResult"+DrawCmd$
              SetPageLoc xl, YLoc()
           endif
        next i
      else

        ! check register range to draw
        regnum=RegSize(DiagTestResult)
        FirstPage=1
        drawRegMin=1
        drawRegMax=MIN(drawRegMin + WinPerPage -1, RegNum)

        ! print Chart Title
         Print Using #5, "/" ! space between draw window
         Print #5, NlsMsDiag$(Chart1$)

         ! check drawing size
        !print "Position before drawing: ", YLoc(), "(", YLogMax(), ")"
        drawWinSize = MIN(drawWinSize, \
                       TRUNC( (YLogMax()- YLoc() )*10 / WinPerPage) /10 )

        While (drawRegMin <= RegNum)
           if FirstPage = 0 then
              !print "NEXT draw page"
              FormFeed
              if isPRTestEnv = 1 then
                 MfgHeaderPrint 1
              endif
              ! print "check new draw size:", \
              !        TRUNC( (PageSize-YLoc()+1)* 10/(WinPerPage+1) )/10, \
              !        "<=", drawWinSize, "?"
              if drawWinSize >= MIN(drawWinSize, \
                  TRUNC( (PageSize-YLoc()+1)*10 / (WinPerPage+1))/10 ) then
                  WinPerPage= WinPerPage+1
                  drawRegMax= MIN(drawRegMax+1, RegNum)
                  !print " New WinPerPage:", WinPerPage
              endif
           endif

           ! print "draw register:", drawRegMin,"-", drawRegMax, \
           !       "Size:", drawWinSize
           ! print "draw window: (2," , YLoc(), ") 74 x ", \
           !        drawWinSize * (drawRegMax-drawRegMin+1)
           SetWinPrintParams DIAG_WinEnd + 1, , 74/XLogMax(), \
                             (drawWinSize * (drawRegMax-drawRegMin+1)/PageSize)

           ! special case for the noise report to ensure that the full
           ! mass range is drawn
           if ReportTitle$ = "NoiseReport" then
              DrawCmd$ = "Draw " + VAL$(DIAG_WinEnd + 1) + \
                         ", DiagTestResult[drawRegMin:drawRegMax]," + \
                         val$(MSinstrParm("MinMass")) + ":" + \
                         val$(MSinstrParm("MaxMass")) + ",,1,1"
              ! print DrawCmd$
              evaluate DrawCmd$
           else
              DrawCmd$ = "Draw " + VAL$(DIAG_WinEnd + 1) + \
                         ", DiagTestResult[drawRegMin:drawRegMax],,,1,1"
              ! print DrawCmd$
              evaluate DrawCmd$
           endif
           drawRegMin = drawRegMax+1
           drawRegMax = MIN(drawRegMin + WinPerPage -1, RegNum)
           FirstPage  = 0
        EndWhile
     endif

     ! add two blank lines to print out if on the same page
     !=====================================================
     If YLoc() <= (PageSize-2) then
        Print Using #5, "/"  ! space between draw window and table
     endif  
     SetPageLoc xl, YLoc()
   endif

    ! draw table if testResultTab does exist
   !=======================================
   IF ObjHdrType(DiagTestResult[1], "TestResultTab")=4 then
      Print Using #5, "/" ! space between draw window
     MaxRow=TabHdrVal(DiagTestResult[1], TestResultTab, NumberOfRows)
     if maxRow < 1 then
       !print "No entries in Test Table!"
       GOTO EndPrintOut
     endif

     ! print "Position: ",YLoc()," Page length:", pagesize, 
      !       " Table Size:", rownum
     if YLoc() > (PageSize-2) then
        !print "NEXT table page (before print table)"
        FormFeed
        if isPRTestEnv = 1 then
           MfgHeaderPrint 1
        endif
     endif

     ! print table header
     TabHeader$=""
      if (TabColType(DiagTestResult[1], TestResultTab, "Text") = 0 ) AND \
                    (len(TextF$) > 0) then
       TabHeader$=SPrintF$(NlsMsDiag$(TestResults$),TextF$)
     else
       TextF$=""
     endif
      if TabColType(DiagTestResult[1], TestResultTab, "Range") = 0 AND \
                   (len(RangeF$) > 0) then
       TabHeader$= TabHeader$ + SPrintF$(NlsMsDiag$("Range"),RangeF$)
     else
       RangeF$=""
     endif
      if TabColType(DiagTestResult[1], TestResultTab, "Value") = 0 AND \
                   (len(ValueF$) > 0) then
       TabHeader$= TabHeader$ + SPrintF$(NlsMsDiag$("Value"),ValueF$)
     else
       ValueF$=""
     endif
      if TabColType(DiagTestResult[1], TestResultTab, "Result") = 0 AND \
                   (len(ResultF$) > 0) then
       TabHeader$= TabHeader$ + SPrintF$(NlsMsDiag$("Result"),ResultF$)
     else
       ResultF$=""
     endif

     FromRow = 1
     ! reserve 2 lines for table header + dashes
      ToRow = MIN(MaxRow, PageSize-1-YLoc())  
      ! print on existing page or on new page
      FirstPage = 1
     
     while FromRow <= MaxRow

        if FirstPage=0 then
          ! print "NEXT table page"
          FormFeed
          if isPRTestEnv = 1 then
             MfgHeaderPrint 1
          endif
      endif

        Print #5, TabHeader$
        Print #5, Dashes$

      ! print table line by line
      ! print "Table rows:", FromRow, ToRow 
        for i = fromrow to torow

          ! unit
         if tabcoltype(DiagTestResult[1], TestResultTab, "unit") = 0 then
           unit$=" " + TabText$(DiagTestResult[1], TestResultTab, i, "unit")
         else
           unit$=""
         endif

        Line$=""
          if len(TextF$) > 0 then
           Text$=TabText$(DiagTestResult[1], TestResultTab, i, Text)
         Line$=SPrintF$(Text$, TextF$)
        endif
          if len(RangeF$) > 0 then
           Text$=TabText$(DiagTestResult[1], TestResultTab, i, Range)
         Line$=line$ + SPrintF$(Text$+Unit$, RangeF$)
        endif
          if len(ValueF$) > 0 then
           Text$=TabText$(DiagTestResult[1], TestResultTab, i, Value)
         Line$=line$ + SPrintF$(Text$+Unit$, ValueF$)
        endif
          if len(ResultF$) > 0 then
           Text$=TabText$(DiagTestResult[1], TestResultTab, i, Result)
         Line$=line$ + SPrintF$(Text$, ResultF$)
        endif
          !check line length
        if len(Line$) > XLogMax() then
          print "Table line", i, "is ",len(Line$)-XLogMax(), \
                                         "character too long!"
        else
          !print Line$
        endif
          Print #5, Line$
        next i

       FirstPage=0
       FromRow=ToRow+1
       ! reserve 2 lines for table header + dashes,
        ! plus 2 free lines for the top page header
        ToRow=MIN(ToRow+PageSize-4, MaxRow)  
                
     endwhile

   endif

    ! end print out.
    
EndPrintOut:
    ON ERROR print
    if RegSize(DiagGuiReg) < 1 then
       Load_DiagGuiReg
    endif
    if ObjHdrType( DiagGuiReg[1], "ErrMsg") <> 99 then
       Print using #5, "//"
       Print #5, "ERROR: "+ ObjHdrText$(DiagGuiReg[1], "ErrMsg")
    endif
    EndJob
    Close #5

ENDMACRO
!****************************************************************************


!****************************************************************************
NAME dgMsPrintDemoPage

! prints a demo page to show the margins and the settings of the 
! test print out
!****************************************************************************
LOCAL Dashes$, Num1$, Num2$, i


    GetCurrentPrinterSetup                   !3-02PR utilize current printer setup
    On Error print _ErrMsg$

    ! begin print out and set error trap to close printer device
    BeginJob ,,XMax()-13, YMax()-1

    print "Print MSD Test Demo Page"

    Header$ = ">>>>> Title <<<<<"
    SetHeader Header$, XLogMax()/2 - len(Header$)/2
    SetFooter PageFooterLine$()
    SetMargin 2, 2, 2
    PageSize= YLogMax()+1        !3-02PR fix#243 (don't set to constant: 60 here)

    On Error CloseDeviceBeforeOpenDevice    !3-02PR recover and continue
    OpenDevice "Printer" As #5
    On Error print _ErrMsg$

    xl = XLoc()

    ON ERROR GOTO EndPrintOut 
    Num1$   = "         1         2         3         4         5         6         7    "
    Num2$   = "123456789012345678901234567890123456789012345678901234567890123456789012345678"
    Dashes$ = "--------------------------------------------------------------------------"

    Print #5, Num1$
    Print #5, Num2$
    Print #5, Dashes$
    Print #5, "Line  XLoc  YLoc XLogMax YLogMax"

   For i=5 to pageSize
      Print using #5,"****  ****  **** ******* *******/", i, XLoc(), YLoc(), \
                                                       XLogMax(), YLogMax()
    next i

EndPrintOut:
    ON ERROR
    EndJob
    Close #5
ENDMACRO
!***************************************************************************!

!***************************************************************************!
NAME dgMsReadDynParm

   PARAMETER RegObj DEFAULT 1
   PARAMETER ParmNum

! This macro reads a dynamic list and stores it in the DynamicsParm table
! as a string
!***************************************************************************!
LOCAL nPoints, mass, setting, i
LOCAL Parm$, ParmStr$, temp$

    ! get the parameter name
    Parm$ = TabText$(RESULT_REG[RegObj], DynamicsParm, ParmNum, "Parameter")
    MsUseEmv 0
    MSDynamic Parm$, read, 0, nPoints
    
    if nPoints = 0 then
       RETURN
    endif
    
    for i = 1 to nPoints
        MSDynamic Parm$, read, i, mass, setting
        ParmStr$ = ParmStr$ +    val$(mass) + "," + val$(setting) + ","
    next i

    ! strip the trailing comma
    ParmStr$ = ParmStr$[1:len(ParmStr$)-1]
    
    ! store it in the table
    SetTabText RESULT_REG[RegObj], DynamicsParm, ParmNum, "ParmString", ParmStr$

ENDMACRO 
!***************************************************************************!

!***************************************************************************!
NAME dgMsGetDynamicsParmTab

   PARAMETER RegObj DEFAULT 1

! This macro reads a dynamic list and stores it in the DynamicsParm table
! as a string
! COLUMNS
!   Parameter:   name of the dynamic parameter
!   ParamString: dynamic settings
!***************************************************************************!
LOCAL parm1$, parm2$, parm3$, parm4$, parm5$, parm6$, parm7$, parm8$, row
LOCAL i, parm$

   if ObjHdrType(RESULT_REG[RegObj], DynamicsParm) <> 99 then
     delTab RESULT_REG[RegObj], DynamicsParm
   endif

   ! Find out which parms are dynamically ramped
   NewTab RESULT_REG[RegObj], DynamicsParm
   NewColText RESULT_REG[RegObj], DynamicsParm, "Parameter", ""
   NewColText RESULT_REG[RegObj], DynamicsParm, "ParmString", ""
   
   MsUseEmv 0
   MSDynamic list, parm1$, parm2$, parm3$, parm4$, parm5$, parm6$, parm7$, parm8$
   for i = 1 to 8
      evaluate "parm$ = parm" + val$(i) + "$"; print parm$
      if len(parm$) > 0 then 
        ! trim the fragmentor label
          if inStr(convertText$(upper,parm$), "FRAG") > 0 then
            parm$ = "Frag"
          endif
         print "Parm$: ",parm$
         InsTabRow  RESULT_REG[RegObj], DynamicsParm
         row = TabHdrVal(RESULT_REG[RegObj], DynamicsParm, "NumberOfRows")
         SetTabText RESULT_REG[RegObj], DynamicsParm, row, "Parameter", parm$
         dgMsReadDynParm RegObj, row
      endif
   next i

ENDMACRO 
!***************************************************************************!

!***************************************************************************!
NAME dgMsGetTestParmsTab

   PARAMETER RegObj DEFAULT 1

! generates a table to save all original settings and specific test params .
!
! COLUMNS
!   Name:     full name of the parameter
!   Item:     short name of the parameter
!   Dynamic:  >0 if the parameter is dynamic, -1 otherwise
!   Original: actual settings before the test started
!   Units:    units of the parameter
!***************************************************************************!
LOCAL value$, val, ionMode$, dynamic, MaxMass, MinMass, i, rowNum

   ON ERROR dgMsPrintError
   
   ! get spray chamber ID
   MSGetMode ionMode$
   SetObjHdrText RESULT_REG[1], "IonMode", ionMode$

   Value$=dgMsQuery$(":msc:parm? quadf")
   SetObjHdrVal  RESULT_REG[1], "OldQuadFreq", VAL(value$)

   NewTab     RESULT_REG[RegObj], TestParms
   NewColText RESULT_REG[RegObj], TestParms, "Item", ""
   NewColText RESULT_REG[RegObj], TestParms, "Name", ""
   NewColVal  RESULT_REG[RegObj], TestParms, "Dynamic", -1
   NewColVal  RESULT_REG[RegObj], TestParms, "Original", -99
   NewColText RESULT_REG[RegObj], TestParms, "Units", ""
   InsTabRow  RESULT_REG[RegObj], TestParms, 1:26

   !***** F I X or D Y N A M I C
   rowNum = 1 
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Item", "Gain"
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Name", "Gain"
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Units","Gain Units"
   dynamic=RowByText (RESULT_REG[RegObj], DynamicsParm,, "Parameter", "i=",\
                                                           "Gain")
   if dynamic = -1 then
     MsUseEmv 0
     MSParm GAIN, val
     SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Original", val
   else
      SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Dynamic", dynamic
   endif

   rowNum = rowNum + 1 
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Item", "HED"
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Name", "HED Voltage"
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Units","Volts"
   dynamic=RowByText (RESULT_REG[RegObj], DynamicsParm,, "Parameter", "i=", \
                      "HED")
   if dynamic = -1 then
     MSParm hed, val
     SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Original", val
   else
      SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Dynamic", dynamic
   endif
    
   rowNum = rowNum + 1 
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Item", "IonPolarity"
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Name", "Ion polarity"
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Units","0=Pos; 1=Neg"
   dynamic=RowByText (RESULT_REG[RegObj], DynamicsParm,, "Parameter", "i=", \
                                                         "IonPolarity")
   if dynamic = -1 then
     MSParm IonPolarity, val
     SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Original", val
   else
      SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Dynamic", dynamic
   endif
      
   rowNum = rowNum + 1 
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Item", "VCap"
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Name", "Capillary voltage"
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Units","Volts"
   dynamic=RowByText (RESULT_REG[RegObj], DynamicsParm,, "Parameter", "i=", \ 
                                                         "VCap")
   if dynamic = -1 then
     MsParm VCap, val
     SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Original", val
   else
     SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Dynamic", dynamic
   endif

   rowNum = rowNum + 1 
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Item", "Corona"
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Name", "Corona current"
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Units","µA"
   dynamic=RowByText (RESULT_REG[RegObj], DynamicsParm,, "Parameter", "i=", \
                                                         "Corona")
   if ionMode$ = "APCI" AND dynamic = -1 then
     MSParm corona, val
     SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Original", val
   else
     SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Dynamic", 99
   endif
   
   ! Using short name for fragmentor so it works for linked and unlinked cases
   rowNum = rowNum + 1 
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Item", "Frag"
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Name", "Fragmentor"
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Units","Volts"
   dynamic=RowByText (RESULT_REG[RegObj], DynamicsParm,, "Parameter", "i=", \
                                                         "Frag")
   if dynamic = -1 then
    if ((MS_SQ_SL = 0) and (check(variable, dgMSUnlinked) = 0)) then
       MSParm Fragmentor, val               ! All other models, with Frag/Sk1 linked
     else
       MSParm Fragment, val                 ! SL model
     endif
     SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Original", val
   else
     SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Dynamic", dynamic
   endif
   
   if MS_SQ_SL = 0 then
     rowNum = rowNum + 1 
     SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Item", "Skim2"
     SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Name", "Skimmer 2"
     SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Units","Volts"
     dynamic=RowByText (RESULT_REG[RegObj], DynamicsParm,, "Parameter", "i=", \
                                                         "Skim2")
     if dynamic = -1 then
        MSParm Skim2, val
        SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Original", val
     else
       SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Dynamic", dynamic
     endif
   else
     rowNum = rowNum + 1 
     SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Item", "Skim1"
     SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Name", "Skimmer 1"
     SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Units","Volts"
     dynamic=RowByText (RESULT_REG[RegObj], DynamicsParm,, "Parameter", "i=", \
                                                         "Skim1")
     if dynamic = -1 then
        MSParm Skim1, val
        SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Original", val
     else
       SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Dynamic", dynamic
     endif
   endif
   
   rowNum = rowNum + 1 
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Item", "IonEnergy"
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Name", "Ion Energy"
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Units","Volts"
   dynamic=RowByText (RESULT_REG[RegObj], DynamicsParm,, "Parameter", "i=", "IonEnergy")
   if dynamic = -1 then
      MSParm IonEnergy, val
      SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Original", val
   else
      SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Dynamic", dynamic
   endif

   rowNum = rowNum + 1 
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Item", "Lens1"
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Name", "Lens 1"
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Units","Volts"
   dynamic=RowByText (RESULT_REG[RegObj], DynamicsParm,, "Parameter", "i=", \
                                                         "Lens1")
   if dynamic = -1 then
      MSParm Lens1, val
      SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Original", val
   else
      SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Dynamic", dynamic
   endif

   if MS_SQ_SL = 0 then
     rowNum = rowNum + 1 
     SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Item", "Lens2"
     SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Name", "Lens 2"
     SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Units","Volts"
     dynamic=RowByText (RESULT_REG[RegObj], DynamicsParm,, "Parameter", "i=", \
                                                         "Lens2")
     if dynamic = -1 then
       MSParm Lens2, val
       SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Original", val
     else
       SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Dynamic", dynamic
     endif
   else
     rowNum = rowNum + 1 
     SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Item", "Lens2DC"
     SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Name", "Lens 2DC"
     SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Units","Volts"
     dynamic=RowByText (RESULT_REG[RegObj], DynamicsParm,, "Parameter", "i=", \
                                                         "Lens2DC")
     if dynamic = -1 then
       MSParm Lens2DC, val
       SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Original", val
     else
       SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Dynamic", dynamic
     endif
   endif
   
   rowNum = rowNum + 1 
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Item", "OpolPeak"
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Name", \
                                                     "Octopole RF Amplitude"
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Units","Volts p-p"
   dynamic=RowByText (RESULT_REG[RegObj], DynamicsParm,, "Parameter", "i=", \
                                                         "OpolPeak")
   if dynamic = -1 then
      MSParm OpolPeak, val
      SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Original", val
   else
      SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Dynamic", dynamic
   endif

   if MSD_46 = 1 then               ! Only G1946 MSD's have OpolNnee
     rowNum = rowNum + 1 
     SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Item", "OpolKnee"
     SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Name", "Octopole RF Knee"
     SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Units","Volts p-p"
     dynamic=RowByText (RESULT_REG[RegObj], DynamicsParm,, "Parameter", "i=", \
                                                         "OpolKnee")
     if dynamic = -1 then
        MSParm OpolKnee, val
        SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Original", val
     else
        SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Dynamic", dynamic
     endif
   endif !* if MSD_46 = 1
    
   rowNum = rowNum + 1 
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Item", "QuadDC"
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Name", "Quad Offset"
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Units", "Volts"
   dynamic=RowByText (RESULT_REG[RegObj], DynamicsParm,, "Parameter", "i=", \
                                                         "QuadDC")
   if dynamic = -1 then
      MSParm QuadDC, val
      SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Original", val
   else
      SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Dynamic", dynamic
   endif

   rowNum = rowNum + 1 
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Item", "Iris"
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Name", "Iris"
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Units", "Volts"
   dynamic=RowByText (RESULT_REG[RegObj], DynamicsParm,, "Parameter", "i=", \
                                                         "Iris")
   if dynamic = -1 then
      MSParm Iris, val
      SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Original", val
   else
      SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Dynamic", dynamic
   endif

   !*****  Q U E R Y 
   rowNum = rowNum + 1 
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Item", "CapPeriod"
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Name", "Capture period"
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Units","sec"
   value$=dgMsQuery$(":cap:per?")
   SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Original", val(value$)
      
   rowNum = rowNum + 1 
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Item", "CapCur"
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Name", "Capillary current"
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Units","µA"
   ! Read Capillary current here
   value$=dgMsQuery$("sens? capilcur")
   SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Original", Val(value$)

   rowNum = rowNum + 1 
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Item", "QuadF"
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Name", "Quad Frequency"
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Units","MHz"
   value$=dgMsQuery$(":msc:parm? quadf")
   SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Original", VAL(value$)

   !*****  O T H E R S
   rowNum = rowNum + 1 
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Item", "LowScanMass"
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Name", "MinMass"
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Units","amu"
   val= MsInstrParm("MinMass")
   SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Original", val
   
   rowNum = rowNum + 1 
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Item", "HighScanMass"
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Name", "MaxMass"
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Units","amu"
   val = MsInstrParm("MaxMass") 
   SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Original", val

   rowNum = rowNum + 1 
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Item", "CapMass"
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Name", "Capture mass"
   SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Original", 500
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Units", "amu"
   
   rowNum = rowNum + 1 
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Item", "CapPts"
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Name", "Capture Pts"
   SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Original", 10000
   
   rowNum = rowNum + 1 
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Item", "MSStepSize"
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Name", "Step size"
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Units","amu"
   MSStepSize val
   SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Original", val
   
   rowNum = rowNum + 1 
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Item", "MSSamples"
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Name", "Samples"
   MSSamples val
   SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Original", val
   ! SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Units", "2^n"
   
   rowNum = rowNum + 1 
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Item", "ScanType"
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Name", "ScanType"
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Units", \
                                                     "0=pkDet;1=Cont;2=Raw"
   MSScanParm ScanType, Val  ! set to raw data
   SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Original", val
   
   rowNum = rowNum + 1 
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Item", "MSFilterMass"
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Name", "MS Filter"
   MSFilterMass value$,,val
   SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Original", val
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Units", value$   

   rowNum = rowNum + 1 
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Item", "MSAverages"
   SetTabText RESULT_REG[RegObj], TestParms, rowNum, "Name", "Averages"
   MSAverages val
   SetTabVal  RESULT_REG[RegObj], TestParms, rowNum, "Original", val

ENDMACRO 
!***************************************************************************!

!******************************************************************************
NAME dgMsSetTestParms
PARAMETER RegObj  DEFAULT 1
PARAMETER TabCol$ DEFAULT "Original"

! Download the MS parameters in the TestParms table of the specified 
! RESULT_REG
! The following parameters are not redownloaded because they were never set:
!   LowScanMass, HighScanMass, Capture Mass, Capture Pts,Quad Freq
! Modified to reset dynamic parameters if TabCol$ is "Original"
!
!******************************************************************************
LOCAL Row, Val, OldVal, Value$, Parm$, i

   !print ">>>> dgMsSetTestParms for Test ",TabCol$
   
   ms_echo = 0

   if ObjHdrType(RESULT_REG[RegObj], TestParms) = 99 then
     return
   endif
   
   Row=RowByText( RESULT_REG[RegObj], TestParms,, "Item", "i=", "Gain")
   if TabVal(RESULT_REG[RegObj], TestParms, Row, "Dynamic") = -1 then
     MsUseEmv 0
     Val=TabVal(RESULT_REG[RegObj], TestParms, Row, TabCol$)
     MSParm GAIN, , Val
   endif

   Row=RowByText( RESULT_REG[RegObj], TestParms,, "Item", "i=", "HED")
   if TabVal(RESULT_REG[RegObj], TestParms, Row, "Dynamic") = -1 then
     Val=TabVal(RESULT_REG[RegObj], TestParms, Row, TabCol$)
     MSParm HED, , Val
   endif

   Row=RowByText( RESULT_REG[RegObj], TestParms,, "Item", "i=", "IonPolarity")
   if TabVal(RESULT_REG[RegObj], TestParms, Row, "Dynamic") = -1 then
     Val=TabVal(RESULT_REG[RegObj], TestParms, Row, TabCol$)
     MSParm IonPolarity, , Val
   endif

   Row=RowByText( RESULT_REG[RegObj], TestParms,, "Item", "i=", "MSStepSize")
   Val=TabVal(RESULT_REG[RegObj], TestParms, Row, TabCol$)
   MSStepSize OldVal, Val

   Row=RowByText( RESULT_REG[RegObj], TestParms,, "Item", "i=", "MSSamples")
   Val=TabVal(RESULT_REG[RegObj], TestParms, Row, TabCol$)
   MSSamples OldVal, Val

   Row=RowByText( RESULT_REG[RegObj], TestParms,, "Item", "i=", "scanType")
   Val=TabVal(RESULT_REG[RegObj], TestParms, Row, TabCol$)
   MSScanParm scanType,,Val
   
   Row=RowByText( RESULT_REG[RegObj], TestParms,, "Item", "i=", "MSFilterMass")
   Val=TabVal(RESULT_REG[RegObj], TestParms, Row, TabCol$)
   Value$=TabText$(RESULT_REG[RegObj], TestParms, Row, "Units")
   MSFilterMass ,value$, , val

   Row=RowByText( RESULT_REG[RegObj], TestParms,, "Item", "i=", "CapPeriod")
   Val=TabVal(RESULT_REG[RegObj], TestParms, Row, TabCol$)
   dgMsWrite "cap:per "+val$(Val), 1

   Row=RowByText( RESULT_REG[RegObj], TestParms,, "Item", "i=", "VCap")
   if TabVal(RESULT_REG[RegObj], TestParms, Row, "Dynamic") = -1 then
     Val=TabVal(RESULT_REG[RegObj], TestParms, Row, TabCol$)
     MSParm Vcap, , Val
   endif

   Row=RowByText( RESULT_REG[RegObj], TestParms,, "Item", "i=", "Corona")
   if TabVal(RESULT_REG[RegObj], TestParms, Row, "Dynamic") = -1 then
     Val=TabVal(RESULT_REG[RegObj], TestParms, Row, TabCol$)
     MSParm Corona, , Val
   endif

   Row=RowByText( RESULT_REG[RegObj], TestParms,, "Item", "i=", "Frag")
   if TabVal(RESULT_REG[RegObj], TestParms, Row, "Dynamic") = -1 then
     Val=TabVal(RESULT_REG[RegObj], TestParms, Row, TabCol$)
     if ((MS_SQ_SL = 0) and (check(variable, dgMSUnlinked) = 0)) then
       MSParm Fragmentor, , Val
     else
       MSParm Fragment, , Val
     endif
   endif

   if MS_SQ_SL = 0 then
     Row=RowByText( RESULT_REG[RegObj], TestParms,, "Item", "i=", "Skim2")
     if TabVal(RESULT_REG[RegObj], TestParms, Row, "Dynamic") = -1 then
       Val=TabVal(RESULT_REG[RegObj], TestParms, Row, TabCol$)
       MSParm Skim2, , Val
     endif
   else
     Row=RowByText( RESULT_REG[RegObj], TestParms,, "Item", "i=", "Skim1")
     if TabVal(RESULT_REG[RegObj], TestParms, Row, "Dynamic") = -1 then
       Val=TabVal(RESULT_REG[RegObj], TestParms, Row, TabCol$)
       MSParm Skim1, , Val
     endif
   endif

   Row=RowByText( RESULT_REG[RegObj], TestParms,, "Item", "i=", "IonEnergy")
   if TabVal(RESULT_REG[RegObj], TestParms, Row, "Dynamic") = -1 then
     Val=TabVal(RESULT_REG[RegObj], TestParms, Row, TabCol$)
     MSParm IonEnergy, , Val
   endif

   Row=RowByText( RESULT_REG[RegObj], TestParms,, "Item", "i=", "Lens1")
   if TabVal(RESULT_REG[RegObj], TestParms, Row, "Dynamic") = -1 then
     Val=TabVal(RESULT_REG[RegObj], TestParms, Row, TabCol$)
     MSParm Lens1, , Val
   endif

   if MS_SQ_SL = 0 then
     Row=RowByText( RESULT_REG[RegObj], TestParms,, "Item", "i=", "Lens2")
     if TabVal(RESULT_REG[RegObj], TestParms, Row, "Dynamic") = -1 then
       Val=TabVal(RESULT_REG[RegObj], TestParms, Row, TabCol$)
       MSParm Lens2, , Val
     endif
   else
     
     Row=RowByText( RESULT_REG[RegObj], TestParms,, "Item", "i=", "Lens2DC")
     if TabVal(RESULT_REG[RegObj], TestParms, Row, "Dynamic") = -1 then
       Val=TabVal(RESULT_REG[RegObj], TestParms, Row, TabCol$)
       MSParm Lens2DC, , Val
     endif
   endif

   Row=RowByText( RESULT_REG[RegObj], TestParms,, "Item", "i=", "OpolPeak")
   if TabVal(RESULT_REG[RegObj], TestParms, Row, "Dynamic") = -1 then
     Val=TabVal(RESULT_REG[RegObj], TestParms, Row, TabCol$)
     MSParm OpolPeak, , Val
   endif

   if MSD_46 = 1 then               ! Only G1946 MSD's have OpolNnee
     Row=RowByText( RESULT_REG[RegObj], TestParms,, "Item", "i=", "OpolKnee")
     if TabVal(RESULT_REG[RegObj], TestParms, Row, "Dynamic") = -1 then
       Val=TabVal(RESULT_REG[RegObj], TestParms, Row, TabCol$)
       MSParm OpolKnee, , Val
     endif
   endif

   Row=RowByText( RESULT_REG[RegObj], TestParms,, "Item", "i=", "QuadDC")
   if TabVal(RESULT_REG[RegObj], TestParms, Row, "Dynamic") = -1 then
     Val=TabVal(RESULT_REG[RegObj], TestParms, Row, TabCol$)
     MSParm QuadDC, , Val
   endif

   Row=RowByText( RESULT_REG[RegObj], TestParms,, "Item", "i=", "QuadF")
   Val=TabVal(RESULT_REG[RegObj], TestParms, Row, TabCol$)
   sctimeout=10
   dgMsWrite ":msc:parm quadf,"+VAL$(Val), 1
   remove sctimeout

   ! restore dynamic ramps if TabCol$ = "Original"
   if TabCol$ = "Original" then
      for i = 1 to TabHdrVal(RESULT_REG[RegObj], DynamicsParm, "NumberOfRows")
         Parm$ = TabText$(RESULT_REG[RegObj], DynamicsParm, i, "Parameter")
         dgMSRestoreDynamic RegObj, Parm$
      next i
   endif

ENDMACRO
!******************************************************************************

!******************************************************************************
NAME dgMsRestoreDynamic
PARAMETER RegObj default 1, Parm$
! This will restore a dynamic ramp for a given parameter if it has been 
! stored in DynamicsParm table

!******************************************************************************
LOCAL rowNum

   if ObjHdrType(RESULT_REG[RegObj], DynamicsParm) = 4 then    ! Changed <> to =. PHC 09/21/2001
      rowNum = RowByText(RESULT_REG[RegObj], DynamicsParm,, "Parameter", "i=", \
                                                            Parm$)
      if rowNum > 0 then
         on error print    ! in case it's still enabled
         if parm$ = "FRAG" then
           if ((MS_SQ_SL = 0) and (check(variable, dgMSUnlinked) = 0)) then
             parm$ = Fragmentor
           else
             parm$ = Fragment
           endif
         endif
         evaluate "MSDynamic " + Parm$ + ", enable"
         on error
         
         evaluate "MSDynamic " + Parm$ + ", set, " + \
                        TabText$(RESULT_REG[RegObj], DynamicsParm, rowNum, \
                                "ParmString")
      endif
   endif

ENDMACRO
!******************************************************************************

!******************************************************************************
NAME dgMsGetParmLimitsTab

  PARAMETER RegObj DEFAULT 1

!******************************************************************************
LOCAL MaxVal, MinVal, IonPolarity, dynamic, row, enabled

   ! Define the ion optics parameters list table
   if ObjHdrType (RESULT_REG[RegObj], ParmLimits) <> 99 then
     delTab RESULT_REG[RegObj], ParmLimits
   endif

   NewTab     RESULT_REG[RegObj], ParmLimits
   NewColText RESULT_REG[RegObj], ParmLimits, "Parameter"
   NewColVal  RESULT_REG[RegObj], ParmLimits, "Max"
   NewColVal  RESULT_REG[RegObj], ParmLimits, "Min"

   if ObjHdrType ( RESULT_REG[RegObj], DynamicsParm) = 99 then
    dgMsGetDynamicsParmTab RegObj
   endif

   row=0
   dynamic=RowByText (RESULT_REG[RegObj], DynamicsParm,, "Parameter", "i=", \
                                                         "Frag")
   InsTabRow RESULT_REG[RegObj], ParmLimits
   row=row+1
   SetTabText RESULT_REG[RegObj], ParmLimits, row, "Parameter", "Frag"
   if ((MS_SQ_SL = 0) and (check(variable, dgMSUnlinked) = 0)) then
     MSParmInfo Fragmentor,, minVal, maxVal
   else
     MSParmInfo Fragment,, minVal, maxVal
   endif
   SetTabVal  RESULT_REG[RegObj], ParmLimits, row, "Max", maxVal
   SetTabVal  RESULT_REG[RegObj], ParmLimits, row, "Min", minVal

   dynamic=RowByText (RESULT_REG[RegObj], DynamicsParm,, "Parameter", "i=", \
                                                         "Skim1")
   InsTabRow RESULT_REG[RegObj], ParmLimits
   row=row+1
   SetTabText RESULT_REG[RegObj], ParmLimits, row, "Parameter", "Skim1"
   MSParmInfo Skim1,, minVal, maxVal
   SetTabVal  RESULT_REG[RegObj], ParmLimits, row, "Max", maxVal
   SetTabVal  RESULT_REG[RegObj], ParmLimits, row, "Min", minVal

   if MS_SQ_SL = 0 then
     dynamic=RowByText (RESULT_REG[RegObj], DynamicsParm,, "Parameter", "i=", \
                                                           "Skim2")
     InsTabRow RESULT_REG[RegObj], ParmLimits
     row=row+1
     SetTabText RESULT_REG[RegObj], ParmLimits, row, "Parameter", "Skim2"
     MSParmInfo Skim2, enabled, minVal, maxVal 
     if enabled = 0 then
        ! hardcoded ramp limits a bit risky
        MaxVal = 30
        MinVal = 0
     endif
     SetTabVal  RESULT_REG[RegObj], ParmLimits, row, "Max", maxVal
     SetTabVal  RESULT_REG[RegObj], ParmLimits, row, "Min", minVal
   endif

   dynamic=RowByText (RESULT_REG[RegObj], DynamicsParm,, "Parameter", "i=", \
                                                         "IonEnergy")
   InsTabRow RESULT_REG[RegObj], ParmLimits
   row=row+1
   SetTabText RESULT_REG[RegObj], ParmLimits, row, "Parameter", "IonEnergy"
   MSParmInfo IonEnergy,, minVal, maxVal
   SetTabVal  RESULT_REG[RegObj], ParmLimits, row, "Max", maxVal
   SetTabVal  RESULT_REG[RegObj], ParmLimits, row, "Min", minVal

   dynamic=RowByText (RESULT_REG[RegObj], DynamicsParm,, "Parameter", "i=", \
                                                         "OpolPeak")
   InsTabRow RESULT_REG[RegObj], ParmLimits
    row=row+1
   SetTabText RESULT_REG[RegObj], ParmLimits, row, "Parameter", "OpolPeak"
   MSParmInfo OpolPeak,, minVal, maxVal
   SetTabVal  RESULT_REG[RegObj], ParmLimits, row, "Max", maxVal
   SetTabVal  RESULT_REG[RegObj], ParmLimits, row, "Min", minVal

   dynamic=RowByText (RESULT_REG[RegObj], DynamicsParm,, "Parameter", "i=", \
                                                         "QuadDC")
   dynamic=RowByText (RESULT_REG[RegObj], DynamicsParm,, "Parameter", "i=", \
                                                         "Lens1")
   InsTabRow RESULT_REG[RegObj], ParmLimits
   row=row+1
   SetTabText RESULT_REG[RegObj], ParmLimits, row, "Parameter", "Lens1"
   MSParmInfo Lens1,, minVal, maxVal
   SetTabVal  RESULT_REG[RegObj], ParmLimits, row, "Max", maxVal
   SetTabVal  RESULT_REG[RegObj], ParmLimits, row, "Min", minVal

   if MS_SQ_SL = 0 then
     dynamic=RowByText (RESULT_REG[RegObj], DynamicsParm,, "Parameter", "i=", \
                                                           "Lens2")
     InsTabRow RESULT_REG[RegObj], ParmLimits
     row=row+1
     SetTabText RESULT_REG[RegObj], ParmLimits, row, "Parameter", "Lens2"
     MSParmInfo Lens2,, minVal, maxVal
     SetTabVal  RESULT_REG[RegObj], ParmLimits, row, "Max", maxVal
     SetTabVal  RESULT_REG[RegObj], ParmLimits, row, "Min", minVal
   else
     dynamic=RowByText (RESULT_REG[RegObj], DynamicsParm,, "Parameter", "i=", \
                                                           "Lens2DC")
     InsTabRow RESULT_REG[RegObj], ParmLimits
     row=row+1
     SetTabText RESULT_REG[RegObj], ParmLimits, row, "Parameter", "Lens2DC"
     MSParmInfo Lens2DC,, minVal, maxVal
     SetTabVal  RESULT_REG[RegObj], ParmLimits, row, "Max", maxVal
     SetTabVal  RESULT_REG[RegObj], ParmLimits, row, "Min", minVal
   endif

   InsTabRow RESULT_REG[RegObj], ParmLimits
   row=row+1
   SetTabText RESULT_REG[RegObj], ParmLimits, row, "Parameter", "QuadDC"
   MSParmInfo QuadDC,, minVal, maxVal
   SetTabVal  RESULT_REG[RegObj], ParmLimits, row, "Max", maxVal
   SetTabVal  RESULT_REG[RegObj], ParmLimits, row, "Min", minVal

   dynamic=RowByText (RESULT_REG[RegObj], DynamicsParm,, "Parameter", "i=", \
                                                         "Iris")
   InsTabRow RESULT_REG[RegObj], ParmLimits
   row=row+1
   SetTabText RESULT_REG[RegObj], ParmLimits, row, "Parameter", "Iris"
   MSParmInfo Iris,, minVal, maxVal
   SetTabVal  RESULT_REG[RegObj], ParmLimits, row, "Max", maxVal
   SetTabVal  RESULT_REG[RegObj], ParmLimits, row, "Min", minVal

   
ENDMACRO 
!******************************************************************************

print "dgMSutil.mac v. " + dgMSutilVer$ + " loaded."

!********* end of file ******************************************************
