! EnuTnDyn.mac  Macro to manage Dynamic ramping of MS lenses  **-Oct-96
!
! COPYRIGHT (C) AGILENT TECHNOLOGIES, 1999-2005.  ALL RIGHTS ARE RESERVED   
! COPYING OR OTHER REPRODUCTION OF THIS PROGRAM EXCEPT FOR ARCHIVAL  
! PURPOSES IS PROHIBITED WITHOUT THE PRIOR WRITTEN CONSENT OF  
! AGILENT TECHNOLOGIES.
!
!                     RESTRICTED RIGHTS LEGEND                          
!                                                                       
! Use, duplication, or disclosure by the Government is subject to       
! restrictions as set forth in subdivision (b) (3) (ii) of the Rights in  
! Technical Data and Computer Software clause at 52.227-7013.           
!                                                                       
! AGILENT TECHNOLOGIES                                               
! Life Sciences and Chemical Analysis Solutions           
! 5301 Stevens Creek Blvd
! Santa Clara, CA 95051-7201
! United States
!
!+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
!  These MACROs are the common macros that are called when tune is invoked.
!  They take care of testing for the current instrument configuration and
!  call the proper set of macros for tuning or diagnostics. IT IS STRONGLY 
!  RECOMMENDED THAT NO MODIFICATIONS BE MADE TO THESE MACROS.
!+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
                                   
! File: EnuTnDyn.mac
!
! Macros:  DYN_CheckNSet           DYN_EditVolts
!          DYN_CheckState          DYN_Extrapolate
!          DYN_CleanUp             DYN_ExtrapolationErr
!                                 
!          DYN_DoDynamicOpt        MSDynRamp
!          DYN_ErrDoDynamicOpt     MSTN_DynRampErr
!          DYN_DynamicOptMass      DYN_SortDataObj 
!          MSTN_DynTestDynOptMass  MSTN_DoDynRamp
!
!  Registers and data objects used:
!    The following three registers implement arrays.  Assume 1 row, many 
!    columns
!    dyn_points
!    dyn_LstCoef
!    dyn_OptMassReg    -- gets created and destroyed
!    dyn_SetReg        -- gets created and destroyed
!
! Global macros used:
!    STOP
!
!   Optimize signal at specified masses for Dynamic ramping of MS lenses.
!
!

!====================================================================
NAME DYN_CheckNSet
  parameter lens$, massarray$, set$ , count
! Check arrays of mass vs. setting for slope and enable dynamic ramping
! All the settings are clamped to the upper or lower limit.
! If the slope of two adjacent points is found to be greater than allowed,
!   the setting of the second point is made equal to the first point.
!
! Globals used: none
!
! Pre-conditions:
!  The masses in the register given by massarray$ must be in ascending order
!    and must be unique
!
! Post-conditions:
! 
!====================================================================
  local  setval, setmass
  local  a, lo, hi, res, temp, temp1
  local  slope, _button, i

  evaluate "MSParminfo "+lens$+",a,lo,hi,res"     !* Get lens limits
  evaluate "MSDynamic "+lens$+",enable"

  evaluate "temp = Data("+set$+",1,1)"
  
  if temp > hi then                               !* if set[1]>hi then
       !* Replace the first item with the upper lens limit
       !* if the first item is greater than the upper limit
       evaluate "SetData "+set$+",1,1,hi"            !* set[1] = hi
  endif
  
  if temp < lo then                               !* if set[1]<lo then
       !* Replace the first item with the lower lens limit
       !* if the first item is less than the lower limit
       evaluate "SetData "+set$+",1,1,lo"            !* set[1] = lo
  endif

  evaluate "setval  = Data("+set$+",1,1)"         !* setval=set[1]
  evaluate "setmass = Data("+massarray$+",1,1)"   !* setmass=massarr[1]
  !* Set the first mass
  evaluate "MSDynamic "+lens$+",set,setmass,setval"

  !* Check slope
  i=2
  while i<=count

       evaluate "temp = Data("+set$+",1,i)"
       if temp> hi then                        !* if set[i]>hi then
           evaluate "SetData "+set$+",1,i,hi"     !* set[i] = hi
       endif
    
       if temp < lo                            !* if set[i]<lo then
           evaluate "SetData "+set$+",1,i,lo"     !* set[i] = lo
       endif
    
       !* check absolute slope against limit
       evaluate "temp = Data("+massarray$+",1,i)"
       evaluate "temp1 = Data("+massarray$+",1,i-1)"
       if temp <> temp1 then                   
            !* massarr[i]<>massarr[i-1]
            evaluate "slope = Data("+set$+",1,i) - Data("+set$+",1,i-1)" 
            !* 20Jan97: The slope should be coverted to Dac steps by
            !* using the lens resolution as a divisor.
            slope = slope/(temp-temp1)            !* slope = (set[i]-set[i-1])/(massarr[i]-massarr[i-1])

            if slope < 0 then
                 slope = -slope
            endif
      else
           slope=5000
      endif

!* Remove slope check.
!*      if slope > 500 then
!*            !* slope too big, use last point
!*           evaluate "SetData "+set$+",1,i,Data("+set$+",1,i-1)"  !* set[i]=set[i-1]
!*      endif
    
      evaluate "setval = Data("+set$+",1,i)"               !* setval=set[i]
      evaluate "setmass = Data("+massarray$+",1,i)"        !* setmass=massarr[i]
      evaluate "MSDynamic "+lens$+",append,setmass,setval"
      i=i+1
  endwhile

  return

ENDMACRO     !DYN_CheckNSet



!====================================================================
NAME DYN_CheckState

! Check if lens$ is enabled for dynamic ramping.  If so, massArr and volts
! dataobj will be filled, and count is set to non-zero to indicate number of
! points.
! maxct is the maximum number of points to pack in massArr and volts.
! count <= maxct
!
! Pre-conditions: 
!    numpts must be greater or equal to 1

! Post-conditions: returns the number of points packed in count
!    The register object given by massArr$ and volts$
!    will be created if they do not exist
!====================================================================
  parameter lens$,maxct default 6, massArr$, volts$
  local numpts,i,x,y
  local a$,b$,c$,d$,e$,f$       !* Strings for receiving data from MSDynamic
  local count, ifGuard
  
  !* Initialize strings 
  a$=" "
  b$=" "
  c$=" "
  d$=" "
  e$=" "
  f$=" "

  MSDynamic list,a$,b$,c$,d$,e$,f$
  !* Create one long list of lens
  a$=a$+","+b$+","+c$+","+d$+","+e$+","+f$
  a$=ConvertText$(upper,a$)
  b$=ConvertText$(upper,lens$)
  
  !* Check to see if the lens given as a parameter is in the list
  !* of dynamically ramped lens
  
  if instr(a$,b$) = 0 then
       !* not dynamically ramped
       count = 0
  else
       !* dynamically ramped
       evaluate "MSDynamic "+lens$+",read,0,numpts"     
       if numpts>maxct then
            !* only pack in maxct number of points
            numpts=maxct
       endif

       !* Test for existance of mass and volts; create if need be
       evaluate "ifGuard = RegSize(" + massArr$ + ")"
    
       if ifGuard = -1 then
            !* Create a data object to store the mass array if need be
            evaluate "  NewObj " + massArr$ + ",2,1,numpts"
       endif
    
       evaluate "ifGuard = RegSize(" + volts$ + ")"
    
       if ifGuard = -1 then
            !* Create a data object to store the voltage if need be
            evaluate  "NewObj " + volts$ + ",2,1,numpts"
       endif

       count=0
       for i = 1 to numpts
            evaluate "MSDynamic "+lens$+",read,i,x,y"    
            evaluate "SetData " + massArr$ + ", 1, i, x"         !massArr[i] = x
            evaluate "SetData " + volts$ + ", 1, i, y"           !volts[i] = y
            !* Count how many points are actually loaded
            count=count+1                           
            next i  
  endif

  return  count

ENDMACRO    !DYN_CheckState



!====================================================================
NAME DYN_CleanUp
!
!  This is a clean up routine used to delete the
!  dynamic ramping registers.  Is used as an error handler.
!  
!==========================================================
  on error print     !* reset error trap
  !* Check if registers exist and delete
! _abort$ = ""  
  MSTN_RemoveAbortHandler  "DYN_CleanUp"
  if RegSize(dyn_OptMassReg)<> -1 then
       !* Delete
       DelReg   dyn_OptMassReg
  endif  
  
  if RegSize(dyn_SetReg) <> -1 then
       !* Delete
       DelReg   dyn_SetReg
  endif  
  
  if RegSize(dyn_points) <> -1 then
       !* Delete registers that may be left over from extrapolation
       DelReg dyn_points
  endif  

  if RegSize(dyn_LstCoef) <> -1 then
       !* Delete registers that may be left over from extrapolation
       DelReg dyn_LstCoef
  endif


  if DialogExists("DlgGetLens") <> 0
      RemoveDialog "DlgGetLens"
  endif

  if DialogExists("DlgOptVoltage") <> 0
       RemoveDialog "DlgOptVoltage"
  endif

  if DialogExists("DlgLensCmd") <> 0
       RemoveDialog("DlgLensCmd")
  endif

  if DialogExists("DlgMassOpt") <> 0 
       RemoveDialog "DlgMassOpt"
  endif
  on error print
  Remove s1,s2,s3,s4,s5,s6    

  ENDMACRO     !DYN_CleanUp



!===================================================================
NAME DYN_DoDynamicOpt
parameter lens$ Default "fragmentor",target$, set$, cnt, extrapolate Default 0

!Use SIMRAMP to find optimum lens values for the masses in target[]
!
!Parameters:
!lens$ is the MS lens to be optimized.
!target$ is the name of the register containing the original array of masses.  
!  It may be changed by extrapolation.
!set$ is the name of the register containing the array of lens setting returned.
!cnt is the initial number of masses to optimize.  It may be changed due to
!extrapolate signals linear extrapolation to the mass limits.
!
! Pre-conditions:
!  The registers name by target$ and set$ must exist and
!    must have dimension of cnt+2 for extrapolation.
!
! Post-conditions:
!====================================================================
    local mass1,i,setval, select1
Local  ID_TUNEMAC_NO_VALID_OPTIM_634
ID_TUNEMAC_NO_VALID_OPTIM_634                      =  17634  
    
    local oldlensVal
    local ifGuard, _button, target
    local value

    !* We will do the simramp using the first tune mass
    !* Save the original value of the first mass in mass1 and select1    
    MSMassValue 1, mass1,,select1

    evaluate "MSParm "+lens$+",oldlensVal"      !* save old static lens value
    
    !* Set an error trap
    on error dyn_ErrDoDynamicOpt mass1,lens$,oldlensVal, select1
    MSTN_AddAbortHandler "dyn_ErrDoDynamicOpt " +val$(mass1) + ","+lens$+","+val$(oldlensVal) +","+val$(select1)
    
    !* disable dynamic ramping so we won't get an error
    !* if the user forgot to disable it
    evaluate "MSDynamic "+lens$+",disable"      

    for i = 1 to cnt
         !* Set the masses according to the target$ array 
         evaluate "target = Data("+target$+",1,i)"

         !* SimRamp using only the first mass
         !* Set the value of the first mass to target and select it  
         MSMassValue 1,,target,,1                 !* Masses target[i]
         
         !* CPL 06/29/09 Only implement MSSetRamp if lens$ = "Lens2RFAmplitude"
         !if i = 1 AND lens$ = "Lens2RFAmplitude" then
         if lens$ = "Lens2RFAmplitude" then  
            if i = 1 then                   
              MSSetRamp Lens2RFAmplitude,10,75,1  !* CPL 01/30/06 Limit Lens2RFAmplitude for Mass 1
            else
              MSSetRamp Lens2RFAmplitude,10,400,5 !* CPL 01/30/06 Larger steps for smoother ramps
            endif
         endif
            
         evaluate "MSSimRamp "+lens$+",1,maximum,,50"
         evaluate "MSParm "+lens$+",setval"
         evaluate "SetData "+ set$ + ",1,i,setval" !* set[i]=setval
    next i
    
    !* Reset the value of the first tune mass to its original value
    MSMassValue 1,,mass1,,select1

    evaluate "MSParm "+lens$+",,oldlensVal"     !* set old static lens value
    on error dyn_ErrDoDynamicOpt mass1,"",oldlensVal

    if cnt > 0 then
         if extrapolate > 0 then
              cnt = dyn_Extrapolate (lens$, target$, set$, cnt)
         endif
         DYN_CheckNSet lens$, target$, set$, cnt
    else
         _button = alert (ReadResource$("tunemac",ID_TUNEMAC_NO_VALID_OPTIM_634),2)
    endif

    !* Remove the abort handler
    MSTN_RemoveAbortHdlrParam "dyn_ErrDoDynamicOpt"

    return cnt

ENDMACRO     !DYN_DoDynamicOpt

!====================================================================
NAME DYN_ErrDoDynamicOpt
  parameter m, lens$, volt, s
!
! Error handler for dyn_DoDynamicOpt
! Tries to restore tune mass #1
!
! Pre-conditions:
!   lens$ must be a valid lens type recognized by MSParm.  See 
!      documentation on MSParm for exact values accepted  
!
! Post-conditions:
!   Will display a dialog box with error message in it.
!   Resets _abort$
!==========================================================
  local _button
    
  on error print
! MSMasses m                             !* restore tune mass #1
  MSMassValue 1,,m,,s
  if len(lens$) <> 0 then
       evaluate "MSParm "+lens$+",,volt"    !* set old static lens value
  endif

  if _error <> 0 then
      _button = alert (_errmsg$, 3)
  endif

! _abort$ = ""  
  MSTN_RemoveAbortHdlrParam "dyn_ErrDoDynamicOpt"
  stop

  return

ENDMACRO     !_ErrDoDynamicOpt

!====================================================================
NAME DYN_DynamicOptMass
parameter lens$ default "fragmentor", OptMassReg$, count, max_entries default 6

!Find the masses to use for dynamic ramping.
!Uses global data object optim_mass
!Uses global CP Vars for check boxes to allow event trapping
!   checkbox CP Var: s1,s2,s3,s4,s5,s6
!Note that a mass found to be less than 0.1 apart from the previous mass
!  is considered redundant and is eliminated.
!
! Pre-conditions:
!  Tune commands DLL must be loaded, and system must be able to talk to MSD.
!
! Post-conditions:
!
! Known problems: 
!  The max number of max_entries is hard-coded, as are dependent variables,
!    such as local variables mass1$ - mass6$ and a loop condition in a
!    dialog box.
!  This routine contains the Stop command and must to clean up here.
!  This routine is too long and complicated!!!
!    
!==========================================================
    local _button,i,j,value
    local m0,m1,m2,m3,m4,m5,m6
    local select,thismass
    local minmass,maxmass
    local title$
    local a$
    local tmp1,tmp2
    local HelpIndex
	Local  ID_TUNEMAC_USE_635
	Local  ID_TUNEMAC__HELP_283
	Local  ID_TUNEMAC_1120
	ID_TUNEMAC_USE_635                                 =  17635  
	ID_TUNEMAC__HELP_283                               =  17283  
	ID_TUNEMAC_1120 = 18120
    
    !ASSERT max_entries <=6;  to handle more, add mass7, mass8, etc
    local mass1,mass2,mass3,mass4,mass5,mass6 
    
    !* Make sure that we only act on 6 masses at most    
    if max_entries > 6 then
       max_entries = 6
    endif

    !* Initialize the min and max mass values    
    minmass = MSInstrparm("minmass")
    maxmass = MSInstrparm("maxmass")

    !* use current tune masses
    i = 1
    while i <= 6
        evaluate "MSMassValue i,m"+val$(i)+",,select"
        evaluate "thismass = m"+val$(i)
        if MSD_VL = 1 then
          if thismass > maxmass then                  ! Should be =< 1500 for a VL model
            evaluate "m"+val$(i)+ " = 50.00"
            select = 0
          endif
        endif
        evaluate "s"+val$(i)+ " = "+val$(select)
        i = i + 1
    endwhile
    
    !* Display masses 

    !==== Create a dialog box ====
    if DialogExists("DlgMassOpt") <> 0 
         !Force the system to build a new dialog box
         !since lens may have changed and we need to get count
         RemoveDialog "DlgMassOpt"
    endif
    
    title$ = "Masses to optimize"
    HelpIndex = HelpSubSystemTopic("msd") + 9087
    MSTN_CPSafeStart "CP2"
    
    !* Add event hooks for when user selects check boxes
    !* to call macro that will make sure that at least one
    !* box is checked
    CPRequest CP2, "onevent s1,  dyn_CheckS1,,CP"
    CPRequest CP2, "onevent s2,  dyn_CheckS2,,CP"
    CPRequest CP2, "onevent s3,  dyn_CheckS3,,CP"
    CPRequest CP2, "onevent s4,  dyn_CheckS4,,CP"
    CPRequest CP2, "onevent s5,  dyn_CheckS5,,CP"
    CPRequest CP2, "onevent s6,  dyn_CheckS6,,CP"

    BeginDialog "DlgMassOpt", 6, 40, 182, (max_entries*20)+30,title$   !* Name of dlg, x, y, dx, dy, title
         StaticText  10,0,40,12, ReadResource$("tunemac",ID_TUNEMAC_USE_635)
         for i = 1 to max_entries               
              !* max_entries+1  -- we can only handle up to 6
         
              !* create the label
              !evaluate "str"+val$(i)+"$= ""Mass&""+val$(i)"              
              a$= ReadResource$("tunemac",ID_TUNEMAC_1120)
              evaluate "str"+val$(i)+"$= """"+a$+""""+val$(i)"
         
              !* create the dialog components
              evaluate "CheckBox  10,-10+(i*20),50,12,str"+val$(i)+"$, s"+val$(i)
              evaluate "NumberBox   77,-8+(i*20),40,12, m"+val$(i)+ ",minmass,maxmass,,,,""%0.2f"""
              next i  
              
         ExecPushButton 122 ,-8+(i*20), 50, 14, ReadResource$("tunemac",ID_TUNEMAC__HELP_283), CP2, "Help " + sprintf$(HelpIndex,"%f")
         OKButton    10,-8+(i*20),50,14
         CancelButton 66,-8+(i*20),50,14
    EndDialog
    
    _button = ShowDialog("DlgMassOpt",HelpIndex)
    
    !* Removed events for check boxes
    CPRequest CP2, "onevent s1,,,CP"
    CPRequest CP2, "onevent s2,,,CP"
    CPRequest CP2, "onevent s3,,,CP"
    CPRequest CP2, "onevent s4,,,CP"
    CPRequest CP2, "onevent s5,,,CP"
    CPRequest CP2, "onevent s6,,,CP"

    if (_button<>1) then
         !* User cancelled operation, so stop
         DYN_CleanUp
         stop
    else
         !* Save masses user entered in dialog
         count = 0               !* Redo the count of valid masses
         for i=1 to max_entries
         !* Remove unselected masses
         !* Update the count of selected masses
         !* Assert: count <= i <= max_entries
            evaluate "select = s" +val$(i)
            if select = 1 then
         !* The ith mass is selected
            !* Increment the count of selected mass 
               count = count + 1  !* Only count if mass is selected
               if (count <> i) then
               !* move the selected ith mass to the count position
               !* if it is not already there
                 evaluate "s" + val$(count) +" = 1"
                 evaluate "m" + val$(count) +" = m" + val$(i)
                 evaluate "s" + val$(i) +" = 0"
                 evaluate "m" + val$(i) +" = 0"
               endif
            endif
         next i

         !*Assert: At this point, masses 1 to count are all of the
         !*        selected masses
         !* Do insertion sort into OptMassReg$
         m0 = 0                  !*Sentinel key for insertion sort
         for i = 2 to count
            evaluate "tmp1 = m" + val$(i)
            j = i
            evaluate "tmp2 = m" + val$(i-1)
            while tmp2 > tmp1
               evaluate "m" + val$(j) + " = m" + val$(j-1)
               j = j -1
               evaluate "tmp2 = m" + val$(j-1)
            endwhile
            evaluate "m" +val$(j) +"  = tmp1"
         next i
         
         !* Eliminate redundant masses
         if count > 0 then
            evaluate "SetData "+OptMassReg$+ ",1,1,m1"    
            j = 1      !* Start with one mass
            for i = 2 to count
               evaluate "tmp1 = m" + val$(i-1)
               evaluate "tmp2 = m" + val$(i)
               if abs(tmp1-tmp2) > 0.1  then
                  j = j + 1   !*Preincrement j to count this mass
                  evaluate "SetData "+OptMassReg$+ ",1,j,m"+val$(i)
               endif
            next i
            count = j         !* Reset the count to the new count
         endif 
         for i = count+1 to max_entries
         !* Zero out all the remaining mass positions
            evaluate "SetData "+OptMassReg$+ ",1,i,0"
         next i
    endif
    return count

ENDMACRO     !DYN_DynamicOptMass


!====================================================================
NAME dyn_CheckDlgOptMass
parameter index
!====================================================================
local count
on error print
   count = s1+s2+s3+s4+s5+s6   
   if (count = 0) then
     if (index > 0) AND (index<7) then
       evaluate "s" + val$(index) + "=1"
     endif
   endif
ENDMACRO 

!====================================================================
NAME dyn_CheckS1
parameter EventCause$, EventLevel$, EventSubjName$, EventCp$
!====================================================================
   if EventCause$= "Changed" then
     dyn_CheckDlgOptMass 1
   endif  
ENDMACRO !dyn_CheckS1

!====================================================================
NAME dyn_CheckS2
parameter EventCause$, EventLevel$, EventSubjName$, EventCp$
!====================================================================
   if EventCause$= "Changed" then
     dyn_CheckDlgOptMass 2
   endif  
ENDMACRO !dyn_CheckS2


!====================================================================
NAME dyn_CheckS3
parameter EventCause$, EventLevel$, EventSubjName$, EventCp$
!====================================================================
   if EventCause$= "Changed" then
     dyn_CheckDlgOptMass 3
   endif  
ENDMACRO !dyn_CheckS3

!====================================================================
NAME dyn_CheckS4
parameter EventCause$, EventLevel$, EventSubjName$, EventCp$
!====================================================================
   if EventCause$= "Changed" then
     dyn_CheckDlgOptMass  4
   endif  
ENDMACRO  !dyn_CheckS4


!====================================================================
NAME dyn_CheckS5
parameter EventCause$, EventLevel$, EventSubjName$, EventCp$
!====================================================================
   if EventCause$= "Changed" then
     dyn_CheckDlgOptMass 5
   endif  
ENDMACRO   !dyn_CheckS5


!====================================================================
NAME dyn_CheckS6
parameter EventCause$, EventLevel$, EventSubjName$, EventCp$
!====================================================================
   if EventCause$= "Changed" then
     dyn_CheckDlgOptMass 6
   endif  
ENDMACRO  !dyn_CheckS6

!====================================================================
NAME MSTN_DynTestDynOptMass

!
! Just a test routine I wrote to test the routine
! dyn_DynamicOptMass when I suspected that it
! wasn't setting the masses correctly.
!
! Pre-conditions:
!  Assumes it is ok to call dyn_DynamicOptMass
!
! Post-conditions:
!  Will create a dyn_OptMassReg containing the
!  values set by the user, hopefully.
!
! Known problems:
!  This routine does not clean up after itself.
!
!====================================================================
local count

    if RegSize(dyn_OptMassReg) <> -1 then
         !* Delete
         DelReg   dyn_OptMassReg
    endif
      
    NewObj   dyn_OptMassReg, 2, 1, 8   !* Used as array of opt masses  
    count = dyn_DynamicOptMass (,"dyn_OptMassReg",3)

ENDMACRO     !MSTN_DynTestDynOptMass



!====================================================================
name DYN_EditVolts
parameter lens$,massArray$,volts$, count
Local  ID_TUNEMAC__HELP_283
Local  ID_TUNEMAC_981
Local  ID_TUNEMAC_982
ID_TUNEMAC__HELP_283                               =  17283  
ID_TUNEMAC_981 = 17981
ID_TUNEMAC_982 = 17982
! Manual editing of dynamic ramping settings.
!
! Pre-conditions:
!  The register named by massArray must exist.
!
! Post-conditions:
!====================================================================
  local i, _button
  local title$,str1$,str2$,str3$,str4$,str5$,str6$  !* String vars for dialog box
  local value1,value2,value3,value4,value5,value6,low,high
  local mass
  local ReturnStop
  local HelpIndex
  local string$, quote$

  !ASSERT count <=6
  if count>6 then
       count=6
  endif
  
  if DialogExists("DlgOptVoltage") <> 0
       !Force the system to build a new dialog box
       RemoveDialog "DlgOptVoltage"
  endif

  !==== Build dialog  ====
  
  HelpIndex = HelpSubSystemTopic("msd") + 9088
  MSTN_CPSafeStart "CP2"

  !title$="Optimum Voltages of "+lens$
  
  title$=ReadResource$("tunemac",ID_TUNEMAC_981)+lens$

  Evaluate "MSParmInfo " + lens$ +",,low,high"
  BeginDialog "DlgOptVoltage", 6, 40, 200, (count*20)+30,title$
       for i = 1 to count
            evaluate "mass = Data(" + MassArray$+ ",1,i)"
           !evaluate "str" + val$(i) +"$ = ""&"" + val$(i) + "" Setting at m/z "" + val$(mass)"
           string$ = ReadResource$("tunemac",ID_TUNEMAC_982)
          
		    evaluate "str" + val$(i) +"$ = ""&"" + val$(i) + string$+ val$(mass)"
            evaluate "StaticText  10,-10+(i*20),115,30, str" + val$(i)+"$"
            evaluate "value"+val$(i)+"= Data("+volts$+",1,i)"
            evaluate "NumberBox  122,-10+(i*20),40,12, value"+val$(i)+",low,high,,,,""%0.2f""" 
            next i                                                                 

       !* Standard button dimensions was dx 32, dy 16
       !* Standard button dimensions is dx 50, dy 14
       ExecPushButton 122, -10+(i*20),50, 14, ReadResource$("tunemac",ID_TUNEMAC__HELP_283),CP2,"Help " + sprintf$(HelpIndex,"%f")
       OKButton    10,-10+(i*20),50,14
       CancelButton 66,-10+(i*20),50,14
    
  EndDialog

   _button = ShowDialog("DlgOptVoltage",HelpIndex)
    
  RemoveDialog "DlgOptVoltage"
  if _button <> 1 then
       !* User cancelled; tell caller to clean up
       ReturnStop = 1
  else
       i=1
       while i<(count+1)
            evaluate "SetData "+volts$+",1,i,value"+ val$(i)  !volts[i]=val(values$[i])
            i=i+1
      endwhile
      DYN_CheckNSet lens$, massArray$, volts$, count
      ReturnStop = 0
  endif

  return ReturnStop

ENDMACRO       !DYN_EditVolts



!====================================================================
NAME DYN_Extrapolate 
  parameter lens$, massarray$, set$,count
  
! Linearly extrapolate dynamic ramping parameters to mass limits.
! No exprapolation is done is lens$ is not a valid MS parameter.
! Creates and destroys data objects points and LstCoef
! Known problems:
!====================================================================
  local  a, lo, hi, res
  local  i, x, y, minmass,maxmass, temp
  local numCoeff, _button

  numCoeff = 2            !* number of coefficients used for least squares fit
  
  if RegSize(dyn_points) <> -1 then
       DelReg dyn_points
  endif
  
  if RegSize(dyn_LstCoef) <> -1 then
       DelReg dyn_LstCoef
  endif
  
  NewObj dyn_points, 2, 2, count         !* matrix object, 2 rows, count cols
  NewObj dyn_LstCoef, 2, 1, numCoeff     !* matrix object, 2 rows, numCoeff cols

  on error dyn_ExtrapolationErr
  minmass = MSInstrparm("minmass")
  maxmass = MSInstrparm("maxmass")
  
  evaluate "MSParminfo "+lens$+",a,lo,hi,res"
 
  if a>0 and count>=2 then
       !* find best line by least squares
       i=1 
       while i<(count+1)
            !* Load the mass array and voltages into DYN_Points
            !* points[i,1]=massarr[i]
            evaluate "SetData DYN_Points, 1, i, Data("+massarray$+"1,i)"  
      
            !* points[i,2]=set[i]
            evaluate "SetData DYN_Points, 2, i, Data("+set$+"1,i)"        
      
            i=i+1
      endwhile
    
      !* Call least squares fit 
      MSLstSqFit DYN_Points,count,numCoeff,DYN_LstCoef           
    
      !* if (lstcoef[2]>1.0e-10 OR lstcoef[2]<-1.0e-10) then 
      if (Data(dyn_LstCoef,1,2)> 1.0e-10) or (Data(dyn_LstCoef,1,2)<-1.0e-10) 
           !* There is a least squares solution of non-zero slope.
           !* First low mass extrapolation
           x = minmass
      
           !* y = lstcoef[1]+x*lstcoef[2] 
           y = Data(dyn_LstCoef,1,1)+x*Data(dyn_LstCoef,1,2)   
      
           !* Now check limits.
           if y>hi then
                y=hi
        
                !* x=(y-lstcoef[1])/lstcoef[2]
                x = y - Data(dyn_LstCoef,1,1)/Data(dyn_LstCoef,1,2)   
           endif
      
           if y<lo then
                y=lo
        
                !* x=(y-lstcoef[1])/lstcoef[2]
                x = y - Data(dyn_LstCoef,1,1)/Data(dyn_LstCoef,1,2)   
           endif
      
           evaluate "temp = Data("+massarray$+",1,1)"
      
           !* Make sure new point has lowest mass
           if (x+0.1)<=temp then    
                !* Now get ready for low mass extrapolation by shifting data.
        
                i=count
                while i>0
                     !* Register acts as an array  massarr[i+1]=massarr[i]
                     evaluate "SetData "+massarray$+",1,i+1,Data("+massarray$+",1,i)"  
          
                     !* Register acts as an array set[i+1]=set[i]
                     evaluate "SetData "+set$+",1,i+1,Data("+set$+",1,i)"  
          
                     i=i-1
               endwhile
        
               evaluate "SetData "+ massarray$ + ",1,1,x"   !massarr[1]=x
               evaluate "SetData "+ set$ + ",1,1,y"         !set[1]=y
               count = count+1
           endif
      
           !* Next Try the high mass extrapolation.
           x = maxmass
      
           !* y = lstcoef[1]+x*lstcoef[2] 
           y = Data(dyn_LstCoef,1,1)+x*Data(dyn_LstCoef,1,2)
      
           !* Now check limits.
           if y>hi then
                y=hi
        
                !* x=(y-lstcoef[1])/lstcoef[2]
                x = y-Data(dyn_LstCoef,1,1)/Data(dyn_LstCoef,1,2)  
           endif
      
           if y<lo then
                y=lo
        
                !* x=(y-lstcoef[1])/lstcoef[2]
                x = y-Data(dyn_LstCoef,1,1)/Data(dyn_LstCoef,1,2)
           endif

           evaluate "temp = Data("+massarray$+",1,count)"
      
           if (x-0.1)>=temp then  
                !* Make sure new point has highest mass
                evaluate "SetData "+massarray$+",1,count+1,x" !massarr[cnt+1]=x
                evaluate "SetData "+set$+",1,count+1,y"       !set[cnt+1]=y
                count = count+1
           endif
      
      endif
  endif 
  
  !* Remove locally used Tune_points and Tune_LstCoef
  DelReg dyn_points
  DelReg dyn_LstCoef
  
  return count              !return the number of points processed

ENDMACRO    !DYN_Extrapolate



!=========================================================================
NAME DYN_ExtrapolationErr
!
! Error handling routine to clean up registers used by dyn_Extrapolate
!=========================================================================
  on error print                    !* Reset error trap
  if RegSize(dyn_points) <> -1 then
       DelReg dyn_points
  endif  

  if RegSize(dyn_LstCoef) <> -1 then
       DelReg dyn_LstCoef
  endif
  
ENDMACRO    !DYN_ExtrapolationErr



!====================================================================
NAME MSDynRamp

parameter lens1$ default "fragmentor",lin1 default 0
parameter lens2$ default "NONE", lin2 default 0
parameter lens3$ default "NONE", lin3 default 0
parameter lens4$ default "NONE", lin4 default 0
parameter lens5$ default "NONE", lin5 default 0
parameter lens6$ default "NONE", lin6 default 0

!
!Support "disable", "enable+autoset" or "enable+manual set" for one of
!   3 MS parameters.
! lens?$ refer to the lens names; lin? refer to linear extrapolation of 
!   dynamic ramping data.
! lens1$ must be a valid keyword string for an MS parameter.
!
! Pre-conditions:
!
! Post-conditions:
!
! Known problems:
!  This routine is long and complicated.
!  It also has multiple exit points, including one in a called subroutine
!  The variable str$ is set but not used.
!
!====================================================================

    local chosenlens$            !* string variable with the name of the selected lens
    local max_entries            !* constant max number of lens to optimize
    local count,i,value          !* integer variables
    local lensnum,firstmass,lastmass,str   !*integer variables
    local title$                 !string variable for dialog box title
    local linear
    local str$
    local _button
    local LenCmd
    local cancel
    local HelpIndex
    local AccelIdx, tmplen
    local AutosetState
    local Enable1, Enable2, Enable3, Enable4, Enable5, Enable6

    !* The following code reflects a max of six tune masses
    max_entries = 6      !maximum number of masses to optimize

    !* Initialize some global registers to use in dynamic ramping only
    !* Assume all matrix objects have one row and many columns

	Local  ID_TUNEMAC_SELECT_LENS_TO_636
	Local  ID_TUNEMAC__HELP_283
	Local  ID_TUNEMAC_DEBUG_ASSERTIO_637
	Local  ID_TUNEMAC__IS_NOT_AVAILA_638
	Local  ID_TUNEMAC_ENABLE_AND__AU_639
	Local  ID_TUNEMAC_ENABLE_AND__MA_640
	Local  ID_TUNEMAC__DISABLE_641
	Local  ID_TUNEMAC__PLOT_DYNAMIC_642

	Local  ID_TUNEMAC__IS_NOT_ENABLE_643
	Local  ID_TUNEMAC_980
	Local  ID_TUNEMAC_1113
	Local  ID_TUNEMAC_1114
	Local  ID_TUNEMAC_1115
	Local  ID_TUNEMAC_1116
	Local  ID_TUNEMAC_1117
	Local  ID_TUNEMAC_1118
	Local  ID_TUNEMAC_1119
	ID_TUNEMAC_SELECT_LENS_TO_636                      =  17636  
	ID_TUNEMAC__HELP_283                               =  17283  
	ID_TUNEMAC_DEBUG_ASSERTIO_637                      =  17637  
	ID_TUNEMAC__IS_NOT_AVAILA_638                      =  17638  
	ID_TUNEMAC_ENABLE_AND__AU_639                      =  17639  
	ID_TUNEMAC_ENABLE_AND__MA_640                      =  17640  
	ID_TUNEMAC__DISABLE_641                            =  17641  
	ID_TUNEMAC__PLOT_DYNAMIC_642                       =  17642  
	ID_TUNEMAC__HELP_283                               =  17283  
	ID_TUNEMAC__IS_NOT_ENABLE_643                      =  17643  
	ID_TUNEMAC_980 = 17980
	ID_TUNEMAC_1113 = 18113
	ID_TUNEMAC_1114 = 18114
	ID_TUNEMAC_1115 = 18115
	ID_TUNEMAC_1116 = 18116
	ID_TUNEMAC_1117 = 18117
	ID_TUNEMAC_1118 = 18118
	ID_TUNEMAC_1119 = 18119

    if RegSize(dyn_OptMassReg) <> -1 then
         !* Delete
         DelReg   dyn_OptMassReg
    endif
      
    if RegSize(dyn_SetReg) <> -1 then
         !* Delete
         DelReg   dyn_SetReg
    endif  
    
    NewObj   dyn_OptMassReg, 2, 1, max_entries+2   !* Used as array of opt masses  
    NewObj   dyn_SetReg, 2, 1, max_entries+2         

    !* Enable the option buttons before the abort routine
    Enable1=1; Enable2=1; Enable3=1; Enable4=1; Enable5=1;Enable6=1

    !* Check for SL instruments
    if lens1$ = "Lens2DC" then
	  if MSD_SL = 0 and MSD_RF = 0 then
        lens1$ = "NONE"
      endif
    endif
    if lens2$ = "Lens2DC" then
	  if MSD_SL = 0 and MSD_RF = 0 then
        lens2$ = "NONE"
      endif
    endif
    if lens3$ = "Lens2DC" then
	  if MSD_SL = 0 and MSD_RF = 0 then
        lens3$ = "NONE"
      endif
    endif
    if lens4$ = "Lens2DC" then
	  if MSD_SL = 0 and MSD_RF = 0 then
        lens4$ = "NONE"
      endif
    endif
    if lens5$ = "Lens2DC" then
	  if MSD_SL = 0 and MSD_RF = 0 then
        lens5$ = "NONE"
      endif
    endif
    if lens6$ = "Lens2DC" then
	  if MSD_SL = 0 and MSD_RF = 0 then
        lens6$ = "NONE"
      endif
    endif

    !* Check for SL-RF instrument
    if lens1$ = "Lens2RFPhase" or lens1$ = "Lens2RFAmplitude" then
      if  MSD_RF = 0 then
        lens1$ = "NONE"
      endif
    endif
    if lens2$ = "Lens2RFPhase" or lens2$ = "Lens2RFAmplitude" then
      if  MSD_RF = 0 then
        lens2$ = "NONE"
      endif
    endif
    if lens3$ = "Lens2RFPhase" or lens3$ = "Lens2RFAmplitude" then
      if  MSD_RF = 0 then
        lens3$ = "NONE"
      endif
    endif
    if lens4$ = "Lens2RFPhase" or lens4$ = "Lens2RFAmplitude" then
      if  MSD_RF = 0 then
        lens4$ = "NONE"
      endif
    endif
    if lens5$ = "Lens2RFPhase" or lens5$ = "Lens2RFAmplitude" then
      if  MSD_RF = 0 then
        lens5$ = "NONE"
      endif
    endif
    if lens6$ = "Lens2RFPhase" or lens6$ = "Lens2RFAmplitude" then
      if  MSD_RF = 0 then
        lens6$ = "NONE"
      endif
    endif

    on error  mstn_dynramperr         !* Set error trap to call clean up and stop
    ! _abort$ = "dyn_CleanUp"       !* Set abort routine
    MSTN_AddAbortHandler "dyn_CleanUp"

    !* Choose which lens to do, assuming at least the first lens is valid.

    if DialogExists("DlgGetLens") <> 0
         !* Force the system to build a new dialog box
         !* since lens may have changed and we need to get count
         RemoveDialog "DlgGetLens"
    endif

    !==== Build Dialog ====
    lensnum = 1                         !* Initialize to first lens
    !title$  = "Dynamic Ramping"
	title$  = ReadResource$("tunemac", ID_TUNEMAC_980)
    HelpIndex = HelpSubSystemTopic("msd") + 9085
    MSTN_CPSafeStart "CP2"

    BeginDialog "DlgGetLens", 6, 40, 182, 145,title$
         statictext   10, 10, 100, 12, ReadResource$("tunemac",	ID_TUNEMAC_SELECT_LENS_TO_636)
         OptionGroup lensnum
         if lens1$ = "&Fragment"          
			OptionButton 10, 25, 60, 12, ReadResource$("tunemac",	ID_TUNEMAC_1113), Enable1
         else
			OptionButton 10, 25, 60, 12, ReadResource$("tunemac",	ID_TUNEMAC_1115), Enable1
         endif   
         !OptionButton 10, 25, 60, 12, lens1$, Enable1
         count = 1                         !* Assume at least one lens
         if lens2$ <> "NONE"
			if lens2$ = "&WidthOffset"
				OptionButton 10, 40, 80, 12, ReadResource$("tunemac",	ID_TUNEMAC_1114), Enable2
			else
				OptionButton 10, 40, 80, 12, lens2$, Enable2
			endif
              
              count = count + 1
         endif
         if lens3$ <> "NONE"
			if lens3$ = "&QuadDC"
				OptionButton 10, 55, 80, 12, ReadResource$("tunemac",	ID_TUNEMAC_1116), Enable3
			else
				OptionButton 10, 55, 80, 12, lens3$, Enable3
             endif
              count = count + 1
         endif
         if lens4$ <> "NONE"
			if lens4$ = "&Lens2DC"
				OptionButton 10, 70, 80, 12, ReadResource$("tunemac",	ID_TUNEMAC_1117), Enable4
			else
				if lens4$ = "&OpolPeak"
					OptionButton 10, 70, 80, 12, ReadResource$("tunemac",	ID_TUNEMAC_1119), Enable4
				endif
				OptionButton 10, 70, 80, 12, lens4$, Enable4
			endif			              
              count = count + 1
         endif
         if lens5$ <> "NONE"
			if lens5$ = "Lens2RFAmplitude"
				OptionButton 10, 85, 80, 12, ReadResource$("tunemac",	ID_TUNEMAC_1118), Enable5
			else				
				OptionButton 10, 85, 80, 12, lens5$, Enable5
			endif		              
              count = count + 1
         endif
         if lens6$ <> "NONE"
			if lens5$ = "&OpolPeak"
				OptionButton 10, 100, 80, 12, ReadResource$("tunemac",	ID_TUNEMAC_1119), Enable6
			else				
				OptionButton 10, 100, 80, 12, lens6$, Enable6
			endif	                            
              count = count + 1
         endif
         !Standard button dimensions was dx 32, dy 16
         !Standard button dimensions is dx 50, dy 14
         ExecPushButton 122,125, 50, 14, ReadResource$("tunemac",ID_TUNEMAC__HELP_283),CP2,"Help " + sprintf$(HelpIndex,"%f")

         !PushButton  122, 70, 50, 14, "&Help",2 
         OKButton  10,125,50,14
         CancelButton 66,125,50,14
      
    EndDialog

    
    if count>1 then
      _button = ShowDialog("DlgGetLens",HelpIndex)
    else
        _button = 1
    endif

    RemoveDialog "DlgGetLens"

    !* ASSERT _button is the value set by DlgGetLens -- keep with the dialog box
    if _button <> 1 then  
         !* not OK, clean up and quit
         DYN_CleanUp    
         stop                          !* Exit point
    endif

    !* Put the name of the chosen lens in chosenlens$
    !* ASSERT 0 < lensnum < 4 
    if lensnum = 1 then
         ChosenLens$= lens1$
         print lens1$
         linear = lin1
    else
         if lensnum = 2
              ChosenLens$= lens2$
              linear = lin2
         else
              if lensnum = 3
                   ChosenLens$= lens3$
                   linear = lin3
              else
                  if lensnum = 4
                       ChosenLens$= lens4$
                       linear = lin4
                  else
                       if lensnum = 5
                            ChosenLens$= lens5$
                            linear = lin5
         		       else
                            if lensnum = 6
                                ChosenLens$= lens6$
                                linear = lin6
                            else
                                !* An unsupported lens number occurred.
                                _button = alert (ReadResource$("tunemac",ID_TUNEMAC_DEBUG_ASSERTIO_637) + val$(lensnum))
                                DYN_CleanUp     !* Exit point
                                stop
                            endif
                       endif
                 endif    
             endif
         endif
    endif
    AccelIndex = instr(ChosenLens$,"&")
    if AccelIndex > 0 then
       tmpLen = len (ChosenLens$) 
       if AccelIndex > 1 then
          if AccelIndex >= tmpLen then
            ChosenLens$ = ChosenLens$[1:AccelIndex-1]
          else   
            ChosenLens$ = ChosenLens$[1:AccelIndex-1]+ ChosenLens$[AccelIndex+1:tmplen]
          endif  
       else      
          ChosenLens$ = ChosenLens$[AccelIndex+1:tmplen]
       endif   
    endif

    !*Check if lens is active.
    evaluate "msparminfo "+ChosenLens$+",i"     !* Get lens limits

    if i=0 then    
         !* lens not available
         _button = alert (ChosenLens$+ReadResource$("tunemac",ID_TUNEMAC__IS_NOT_AVAILA_638),3)
         DYN_CleanUp     !* Exit point
         stop
    endif

    !* Check if the ChosenLens$ is enabled for ramping;  if so, dyn_OptMassReg
    !* and SetReg will be filled; count is set to non-zero to 
    !* indicate number of points
    count = dyn_CheckState(ChosenLens$, max_entries, dyn_OptMassReg,dyn_SetReg)

    !*Check if lens is enabled for dynamic ramping.

    if DialogExists("DlgLensCmd") <> 0
         !* Force the creation of a new dialog box
         RemoveDialog("DlgLensCmd")
    endif

    !==== Create a Dialog Box ====
    if (count=0) then                          !* lens not ramped.
         title$= ChosenLens$+" disabled for DynRamp"
         LensCmd = 1                             !* default auto set
    else                                       !* lens already ramped.
         title$= ChosenLens$+" enabled for DynRamp"
         LensCmd = 4                             !* default to plot
    endif
    
    HelpIndex = HelpSubSystemTopic("msd")  + 9086
    MSTN_CPSafeStart "CP2"

    BeginDialog "DlgLensCmd", 6, 40, 182, 104,title$
         OptionGroup LensCmd
         !* Known bug: Actually, any substring of "QUADDC" that starts with
         !* Q will be accepted by the code, but only QUADDC will
         !* hide the autoset.
         if instr(convertText$(upper,ChosenLens$), "QUADDC") = 0 and \
            instr(convertText$(upper,ChosenLens$), "WIDTHO") = 0 then
            !* Is not quaddc or widthoffset
            AutosetState = 1            !* enable
         else
           if LensCmd = 1 then
             LensCmd = 2                             !* default manual set
           endif
            AutosetState = 0            !* disable
         endif  
         OptionButton 10, 10, 100, 12, ReadResource$("tunemac",ID_TUNEMAC_ENABLE_AND__AU_639),AutoSetState
         OptionButton 10, 25, 100, 12, ReadResource$("tunemac",ID_TUNEMAC_ENABLE_AND__MA_640)
         OptionButton 10, 40, 100, 12, ReadResource$("tunemac",ID_TUNEMAC__DISABLE_641)
         OptionButton 10, 55, 100, 12, ReadResource$("tunemac",ID_TUNEMAC__PLOT_DYNAMIC_642)
         !* Standard button dimensions was dx 32, dy 16
         !* Standard button dimensions is dx 50, dy 14
         ExecPushButton 122, 80, 50, 14, ReadResource$("tunemac",ID_TUNEMAC__HELP_283),CP2,"Help " + sprintf$(HelpIndex,"%f")

         !*PushButton  122, 80, 50, 14, "&Help",2 
         OKButton    10,80,50,14
         CancelButton 66,80,50,14
    EndDialog

   _button = ShowDialog("DlgLensCmd",HelpIndex)


!       repeat
!         _button = ShowDialog("DlgLensCmd",HelpIndex)
!         if _button = 2 then
!              Help HelpIndex
!         endif
!   until _button <> 2   
 
   RemoveDialog("DlgLensCmd")

   !ASSERT _button is set by ShowDialog("DlgLensCmd")
   if _button <> 1 then  ! not OK
        DYN_CleanUp     !* Exit point
        stop
   endif

   !* Do stuff according to what action the user selected in the
   !* DlgLensCmd dialog box.

   if LensCmd = 1 OR LensCmd = 2 then  
        !* Enable dynamic ramping, either autoset or manual
    
        !* Edit masses to optimize.
        !* The routine dyn_DynamicOptMass has a STOP exit point!!!
        count = dyn_DynamicOptMass (ChosenLens$,"dyn_OptMassReg",count,max_entries)

        if count <> 0 then  
             !* already enabled
             evaluate "MSDynamic "+ChosenLens$+",disable"
        endif
      
        if LensCmd = 1 then 
             !* Enabled and autoset
             firstmass = Data(dyn_OptMassReg,1,1)      !* firstmass=optim_mass[1]
             if (count > 0) then
                  lastmass = Data(dyn_OptMassReg,1,count) !* lastmass = optim_mass[count]
             else
                  lastmass = -1                           !* Initialize to impossible value   
             endif
        
             count = dyn_DoDynamicOpt (ChosenLens$,"dyn_OptMassReg","dyn_SetReg",count,linear)

             !* Find extrapolated masses if any.
             if firstmass<> Data(dyn_OptMassReg,1,1)    !if firstmass<>optim_mass[1]
                  str$ = "mass "+val$(Data(dyn_OptMassReg,1,1))
             endif
             if count > 0 then
                  if lastmass<>Data(dyn_OptMassReg,1,count) then
                       if len(str$)>1 then
                            str$ = str$+\
                            " and mass "+val$(Data(dyn_OptMassReg,1,count))+" are extrapolated"
                       else
                            str$ = "mass "+val$(Data(dyn_OptMassReg,1,count))+" is extrapolated"
                       endif
                  else
                       if len(str$)>1 then
                            str$ = str$ + " is extrapolated"
                       endif
                  endif
             endif

        else              
             !* manual set

             !* Initalize voltage settings.
             evaluate "MSParm " + ChosenLens$ + ",value"
             i=1
             while i<(count+1)
                  SetData dyn_SetReg,1,i,value                 !* set[i]=value
                  i=i+1
             endwhile
             cancel = dyn_EditVolts (ChosenLens$,"dyn_OptMassReg","dyn_SetReg",count)
        endif

       if cancel = 0 then
            evaluate "MSDynamic "+ChosenLens$+",plot"
       endif  
  else
       if LensCmd = 3 then 
            !* disable dynamic ramping
            evaluate "MSDynamic "+ChosenLens$+",disable"
      endif
      if LensCmd = 4 then                                 
           !* plot
           if count<>0 then
                evaluate "MSDynamic "+ChosenLens$+",plot"
           else
                print ChosenLens$ + ReadResource$("tunemac",ID_TUNEMAC__IS_NOT_ENABLE_643)
           endif
      endif
  endif
    
  DYN_CleanUp                         !* Exit point

  return
    
ENDMACRO     !MSDynRamp



!====================================================================
NAME MSTN_DynRampErr
!
!  This is a clean up routine used to delete the
!  dynamic ramping registers.  Is used as an error handler.
!  
!====================================================================
local _button
Local  ID_TUNEMAC_AN_ERROR_OCCUR_644
ID_TUNEMAC_AN_ERROR_OCCUR_644                      =  17644  
  _button = Alert(ReadResource$("tunemac",ID_TUNEMAC_AN_ERROR_OCCUR_644) + _errmsg$,3)
  DYN_CleanUp
  stop

ENDMACRO     !MSTN_DynRampErr



!====================================================================
NAME DYN_SortDataObj

!simple sort of table tab$ in register reg$ to increasing order
!
! Pre-conditions:
!   The register given by reg$ must be a matrix object and must exist with
!     at least num items in it
!
! Post-conditions:
!   The first num items in reg$ will be sorted.
!
! Known problems:
!=====================================================================
parameter reg$, num
local i,j,BiggerVal, ival, jval

   if num> 1
        !* sort if there are more than one object in the register
        !*compare the items pairwise
        !* Numbering items left to right, i gives the left item in the 
        !* pair, j gives the right item in the pair
        i=1
        while i<num
             j=i+1
             while j<=num
                  !* The loop will march left to right with increasing index number
                  !* put max(val[i],val[i+1]) in val[i+1] 
                   evaluate "jVal = Data(" + reg$ + ",1,j)"

                  !* put min(val[i],val[i+1] in val[i]
                  evaluate "iVal = Data(" + reg$ + ",1,i)"
          
                  if jVal<iVal      
                       !* if the current item is larger than the next item
                       !* swap the two
                       BiggerVal=iVal                                !biggerval = val[i]
                       evaluate "SetData "+ reg$ + ",1, i, jVal"        !val[i]=val[j]
                       evaluate "SetData "+ reg$ + ",1, j, BiggerVal"   !val[j]=biggerval
                 endif
          
                 j=j+1
            endwhile
            i=i+1
       endwhile
  endif

  return

ENDMACRO    !DYN_SortDataObj

!====================================================================
NAME MSTN_DoDynRamp

  if (MSD_SL = 1) or (MSD_HT = 1) then ! CPL 10/11/2006 Add support for "HT"
    if MSD_RF = 1 then
      !* SL or HT with Lens2RF
      if (MSD_46 = 1) then
        MSDynRamp "&Fragment",0,"&WidthOffset",0,"&QuadDC",0,"&Lens2DC",0,"Lens2RFAmplitude",0
      else
        MSDynRamp "&Fragment",0,"&WidthOffset",0,"&QuadDC",0,"&Lens2DC",0,"Lens2RFAmplitude",0,"&OpolPeak",0        
      endif
	  else
      !* SL without Lens2RF
      MSDynRamp "&Fragment",0,"&WidthOffset",0,"&QuadDC",0,"&Lens2DC",0
	  endif
  else
    if (MSD_46 = 1) then
      MSDynRamp "&Fragmentor",0,"&WidthOffset",0,"&QuadDC",0    !* 1946 other models      
    else
      MSDynRamp "&Fragmentor",0,"&WidthOffset",0,"&QuadDC",0,"&OpolPeak",0    !* 1956A      
    endif
  endif
ENDMACRO    !DYN_DoDynRamp


!==========================END OF MACRO FILE==========================
