!******************************************************************************
!*
!* FILE:  msacqpre.mac
!*
!* DESCRIPTION:  PreRun macro
!*
!* $Header: /cag/DRIVERS/sprite1b/release/msacqpre.mac 1.2 1996-05-06 12:37:24-07 hmgr Exp $
!*
!******************************************************************************

!##############################################################################

Name MsdAcqPre

!*
!* User define macro before starting a method run
!*

     Return
     Endmacro
