 !*******************************************************************************
! mstnUtil.mac - diagnostic and utility macros for the LC/MSD
!
! COPYRIGHT (C) AGILENT TECHNOLOGIES, 1999-2005.  ALL RIGHTS ARE RESERVED   
! COPYING OR OTHER REPRODUCTION OF THIS PROGRAM EXCEPT FOR ARCHIVAL  
! PURPOSES IS PROHIBITED WITHOUT THE PRIOR WRITTEN CONSENT OF  
! AGILENT TECHNOLOGIES.
!
!                     RESTRICTED RIGHTS LEGEND                          
!                                                                       
! Use, duplication, or disclosure by the Government is subject to       
! restrictions as set forth in subdivision (b) (3) (ii) of the Rights in  
! Technical Data and Computer Software clause at 52.227-7013.           
!                                                                       
! AGILENT TECHNOLOGIES                                               
! Life Sciences and Chemical Analysis Solutions           
! 5301 Stevens Creek Blvd
! Santa Clara, CA 95051-7201
! United States
!
!+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
!  These MACROs are the common macros that are called when tune is invoked.
!  They take care of testing for the current instrument configuration and
!  call the proper set of macros for tuning or diagnostics. IT IS STRONGLY 
!  RECOMMENDED THAT NO MODIFICATIONS BE MADE TO THESE MACROS.
!+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
!
! Macros:
!   MSutil        : Load the entire macro set
!   InitMStnUtils : Initialize data subdir, check versions
!   MStnPrintError: Error message output 
!   
! EM Gain utilities:
!   ResetEMGain  : Sets EM gain calibration curve to default
!   SetGain      : Adjusts gain curve to give Gain of 1 at specified EMV
!
! Quad frequency utilities
!   QF           : Reports quad frequencies
!   SetQF        : Set quad frequency 
!   DipQF        : Dip and report quad frequency
!   burnQF       : burns current quad freq to NVRAM
!
! Quad temperature utilities
!   QT           : reads quad temperature and setpoints
!   SetQT        : sets quad temp setpoint
!   BurnQT       : burns a quad power-on setpoint
!   FastHeatQT   : rapid quadrupole temperature equilibration
!
! Quad polarity utilities
!   QP           : read or set quad polarity
!   burnQP       : burns quad polarities to NVRAM
!   psetqpol     : burns quad polarities to NVRAM
!
! Firmware identification utilities
!   SCid         : SmartCard rev & serial number query
!   MSid         : read or set MS serial number
!   PDBid        : Read pdb firmware rev
!   SBid         : Read SICB-LON board firmware rev
!   TCid         : Read turbo controller firmware rev
!   LONversion   : Formatted display of all LON node info
!   CheckVer$    : Displays software, firmware, macro and SC code versions
!
! General utilities
!   ShowRF       : Display RF drive & power at specified mass setting
!   Recapture    : Repetitive MSCapture command.
!   HED          : read or set HED
!   RampHED      : ramps mass 3 by default, 0 means all masses
!   Set_Lag      : calculate and store mass axis lag factors
!   flt          : execute dgMSreportFault
!   SCFault$     : returns a full fault string in 16 words
!   scqStr$      : returns a substring from an MSSCQuery
!   PrintErrTable: Prints out the MSDLogBook register error table 
!   MSlight      : Status light test utility
!   PSDelay      : Read or set polarity switching delay
!   burnPSDelay  : Store new default polarity switching delay
!   pre6100()    : = 1 if a model G1946 or G1956 is connected,
!                  otherwise the return value is 0
!   CDSshort     : Shortens waiting time for calibrant switches / flushing
!                  set only. Instruments returns to default after power cycle
!
! Global Variables set:
!   mstnUtilVer$ : Version string for this macro file
!   SCq$         : response string from an MSSCQuery (global)
!   SCid$        : SmartCard *idn? string
!   PDBid$       : PDB firmware rev
!   SBid$        : SICB-LON firmware rev
!   TCid$        : Turbo controller firmware rev
!
  mstnUtilVer$ = "$Header: /cag/DRIVERS/sprite1b/macros/tune/mstnutil.mac 1.23 2007-06-14 09:10:00-08 clove Exp $"
  verIx = instr(mstnUtilVer$, ".mac ") + 5
  mstnUtilVer$ =  mstnUtilVer$[verIx:VerIx + instr(mstnUtilVer$[VerIx:len(mstnUtilVer$)]," ") - 1] 
  remove verIx
!
!*******************************************************************************
name msUtil
! Reloads the rest of the MS utilities set 
! ***************************************************************** 

   On Error Print _ErrMsg$
      
   !2-22-02pdr(PVCS1717) faster startup, execute this upon switch to diagnosis: macro _AutoMSPath$ + "mstndiag.mac"
   macro _AutoMSPath$ + "enutnrmp.mac"
   macro _AutoMSPath$ + "mstnNRT.mac"
   macro _AutoMSPath$ + "mstnNVR.mac"
   macro _AutoMSPath$ + "mix_util.mac"
   macro _AutoMSPath$ + "edit_mix.mac"
   macro _AutoMSPath$ + "mstnspry.mac"

   InitMStnUtils 

   RETURN
   
endmacro
!************************************************************************!

!************************************************************************!
!************************************************************************!
!************************************************************************!
name InitMStnUtils
! Initialization for MStn Utilities
! 
!************************************************************************!


Local  ID_TUNEMAC_CAN_T_LOAD_FIL_308
Local  ID_TUNEMAC_SOFTWARE_FIRMW_310

Local  ID_TUNEMAC_LC_MSD_UTILITI_311
Local  ID_TUNEMAC___IN_OFFLINE_S_312
Local  ID_TUNEMAC_ERROR_EXECUTIN_313
ID_TUNEMAC_CAN_T_LOAD_FIL_308                      =  17308  
ID_TUNEMAC_SOFTWARE_FIRMW_310                      =  17310  

ID_TUNEMAC_LC_MSD_UTILITI_311                      =  17311  
ID_TUNEMAC___IN_OFFLINE_S_312                      =  17312  
ID_TUNEMAC_ERROR_EXECUTIN_313                      =  17313  
   On Error goto InitmstnUtilsErr

   ! Initialize string
   if Check(Variable, _Abort$) = 0 then
      _abort$ = " "
   endif

   ! Instrument initialization
   MSLogData ,1    ! Enable data logging
    
   ! Run the version check macro
   if _offline = 0 then
      if Check(Macro, CheckVer$) = 0 then
         On Error Print ReadResource$("tunemac",ID_TUNEMAC_CAN_T_LOAD_FIL_308) + _AutoMSPath$ + " verschk.mac"
         macro _AutoMSPath$ + " verschk.mac"
         On Error goto InitmsUtilsErr
      endif
      print ReadResource$("tunemac",ID_TUNEMAC_SOFTWARE_FIRMW_310) + CheckVer$(0)
      print ReadResource$("tunemac",ID_TUNEMAC_LC_MSD_UTILITI_311) + MStnUtilVer$
   else
      print ReadResource$("tunemac",ID_TUNEMAC_LC_MSD_UTILITI_311) + MStnUtilVer$ + \
            ReadResource$("tunemac",ID_TUNEMAC___IN_OFFLINE_S_312)
   endif
   
   RETURN
   
InitMStnUtilsErr:
   MStnPrintError
   print ReadResource$("tunemac",ID_TUNEMAC_ERROR_EXECUTIN_313) + MStnUtilVer$
   RETURN

endmacro        ! InitMStnUtils

!************************************************************************!
!************************************************************************!
name MStnPrintError
PARAMETER command$ default ""
! Writes an error message to the status line and evaluates a command
!************************************************************************!

  print _ErrMacro$ + ": " + _ErrMsg$ + " occurred at line " + \
         val$(_ErrLine) + " in " + _ErrFile$ + ", cmd/fct " + _ErrCmd$

  evaluate command$
  
  RETURN

endmacro
!************************************************************************!

! ---- EM gain utilities ------------------------------------------------!

!************************************************************************!

!************************************************************************!
name ResetEMGain
parameter PosGainMass default 623.03
parameter NegGainMass default 602.98
parameter Auto default 0 ! 1= called from another macro
! Restores default EM gain parameters
!************************************************************************!
LOCAL curve1$,curve2$,curve3$,curvenum,title$,count,_button,result,CurrPol

Local  ID_TUNEMAC_DO_YOU_WANT_TO_314
Local  ID_TUNEMAC_SELECT_WHICH_C_315
Local  ID_TUNEMAC_WRITING_VALUES_316
Local  ID_TUNEMAC_THIS_WILL_TAKE_317
Local  ID_TUNEMAC_EM_GAIN_CURVE_318
Local  ID_TUNEMAC_CAN_T_CHANGE_E_319
Local  ID_TUNEMAC_979

ID_TUNEMAC_DO_YOU_WANT_TO_314                      =  17314  
ID_TUNEMAC_SELECT_WHICH_C_315                      =  17315  
ID_TUNEMAC_WRITING_VALUES_316                      =  17316  
ID_TUNEMAC_THIS_WILL_TAKE_317                      =  17317  
ID_TUNEMAC_WRITING_VALUES_316                      =  17316  
ID_TUNEMAC_EM_GAIN_CURVE_318                       =  17318  
ID_TUNEMAC_CAN_T_CHANGE_E_319                      =  17319  
ID_TUNEMAC_979                                     =  17979  

On Error goto ResetEMGainErr  
! Check ion polarity and scan mode:
  MsParm IonPolarity,CurrPol
    if CurrPol > 1 then
      killit=Alert(ReadResource$("tunemac",ID_TUNEMAC_979),3,"Gain Calibration Curve")
      stop
    endif
    
  if _OffLine = 0 then
    if Auto = 0 then
      if Alert(ReadResource$("tunemac",ID_TUNEMAC_DO_YOU_WANT_TO_314), \
               4, "ResetEMGain") = 1 then
        curve1$ = "Positive"; curve2$ = "Negative"; curve3$ = "Positive and Negative"
        !* Choose which curve to reset
        if DialogExists("DlgGetCurve") <> 0
          !* Force the system to build a new dialog box
          RemoveDialog "DlgGetCurve"
        endif
      !==== Build Dialog ====
      curvenum = 1                         !* Initialize to first curve
      title$  = "Reset Gain Curve"

      BeginDialog "DlgGetCurve", 150, 80, 182, 100,title$
         statictext   10, 10, 125, 12, ReadResource$("tunemac",ID_TUNEMAC_SELECT_WHICH_C_315)
         OptionGroup curvenum
         OptionButton 10, 25, 60, 12, curve1$
         count = 1                         !* Assume at least one curve
         if curve2$ <> "NONE"
           OptionButton 10, 40, 80, 12, curve2$
           count = count + 1
         endif
         if curve3$ <> "NONE"
           OptionButton 10, 55, 90, 12, curve3$
           count = count + 1
         endif
         OKButton  10,80,50,14
         CancelButton 66,80,50,14
      EndDialog

        if count>1 then
          _button = ShowDialog("DlgGetCurve")
        else
          _button = 1
        endif
        if _button <> 1 then      ! User cancelled out
          curvenum = -1
        endif
      RemoveDialog "DlgGetCurve"
      else
        print ReadResource$("tunemac",ID_TUNEMAC_EM_GAIN_CURVE_318)
        Return
      endif   !* if Alert("Do you...
    else  
      curvenum = (CurrPol + 1)
    endif  !* if Auto = 0
      
      ! Load and/or initialize the GainCurve register:
        if RegSize(GainCurve) = -1 then
        !* Register not loaded.  Try loading the register from disk
          if filestat(mode,_tunepath$ + "GainCurve.reg") = 1 then
            LoadObj _tunepath$ + "GainCurve.reg",, GainCurve
          else
            ! GainCurve.reg has been deleted from this system
              title$= "Gain Curve Check"
              line1$= ReadResource$("tunemac",ID_TUNEMAC_GAINCURVE_REG_323)
              line2$= chr$(13) + chr$(13) +"Please restore file or reload ChemStation software."
              _button=alert(line1$ + line2$,3,title$)  ! CPL 03/06 Replace Atuneprint statement with Alert.
              stop
          endif
        endif
        
        !* Initialize the Gain Curve register, if necessary 
        if (RegSize(GainCurve) > -1) and (RegSize(GainCurve) < 2) then
          print msat_InitGainCurveReg()
        endif

      EmvGain0=8.5                 ! Default Pos/Neg Slope, m
      EmvGain1=-62.08              ! Default Pos/Neg Intercept ("Offset"), b
      EmvGain2=0                   ! Dummy value; may remove later
      
      SetAbort Off                 !* Don't let user abort until calibration
                                   !* done and burned into SmartCard
                                   
      If (curvenum = 1) Or (curvenum = 3) Then        ! Reset positive curve      
        ! Initialize parameters
          CurrPol = 0
          m = EmvGain0                 ! Default Slope
          b = EmvGain1                 ! Default Intercept
          ve6=Exp((Ln(1)-b)/m)         ! Default EMV from Slope and Intercept values
          v_1=2500
          Gain_1=Exp(m*Ln(v_1)+b)*1e6  ! Build default Gain Curve, 1st point
          v_2=2200
          Gain_2=Exp(m*Ln(v_2)+b)*1e6  ! Build default Gain Curve, 2nd point
          v_3=1900          
          Gain_3=Exp(m*Ln(v_3)+b)*1e6  ! Build default Gain Curve, 3rd point
          v_4=1600          
          Gain_4=Exp(m*Ln(v_4)+b)*1e6  ! Build default Gain Curve, 4th point
          v_5=1300          
          Gain_5=Exp(m*Ln(v_5)+b)*1e6  ! Build default Gain Curve, 5th point    
          
        ! Set the values in SmartCard NVRAM
          print ReadResource$("tunemac",ID_TUNEMAC_WRITING_VALUES_316) + \
          ReadResource$("tunemac",ID_TUNEMAC_THIS_WILL_TAKE_317)
          MSSCWrite "msc:parm:pset emvgain0," + val$(EmvGain0)
          MSSCWrite "msc:parm:pset emvgain1," + val$(EmvGain1)
          MSSCWrite "msc:parm:pset emvgain2," + val$(EmvGain2)
        ! write to memory as well
          MSSCWrite "msc:parm emvgain0," + val$(EmvGain0)
          MSSCWrite "msc:parm emvgain1," + val$(EmvGain1)
          MSSCWrite "msc:parm emvgain2," + val$(EmvGain2)
          
        WinUpdate Off  
        ! Update Positive Gain Curve Register
          nPoints = 5  ! Set the number of columns in the gain data object to 5
          NewObj GainCurve[CurrPol+2], 2, 1, nPoints !* Create new gain data object
          SetObjHdrText GainCurve[CurrPol+2], "Title", "Positive Gain Curve"
          DelObj GainCurve[CurrPol+3]               ! Get rid of the old data object
          msat_UpdateGainCurveReg CurrPol,PosGainMass,ve6,m,b,v_1,Gain_1,v_2,Gain_2, \
            v_3,Gain_3,v_4,Gain_4,v_5,Gain_5
        WinUpdate On    
          
        ! Annotate the Gain Curve register:
          msat_AnnotGainCurve CurrPol
      
        ! Save the gain curve:
          saveobj GainCurve,_TunePath$+"GainCurve.reg",new
      
        ! Display the Gain-EMV curve on the screen, if not called by autotune:
          if Auto = 0 then
            if curvenum = 1 then
              msat_DispGainCurve,,CurrPol
            endif
          endif
        endif
      If (curvenum = 2) Or (curvenum = 3) Then        ! Reset negative curve
        ! Initialize parameters
          CurrPol = 1
          m = EmvGain0                 ! Default Slope
          b = EmvGain1                 ! Default Intercept
          ve6=Exp((Ln(1)-b)/m)         ! Default EMV from Slope and Intercept values
          v_1=2500
          Gain_1=Exp(m*Ln(v_1)+b)*1e6  ! Build default Gain Curve, 1st point
          v_2=2200
          Gain_2=Exp(m*Ln(v_2)+b)*1e6  ! Build default Gain Curve, 2nd point
          v_3=1900          
          Gain_3=Exp(m*Ln(v_3)+b)*1e6  ! Build default Gain Curve, 3rd point
          v_4=1600          
          Gain_4=Exp(m*Ln(v_4)+b)*1e6  ! Build default Gain Curve, 4th point
          v_5=1300          
          Gain_5=Exp(m*Ln(v_5)+b)*1e6  ! Build default Gain Curve, 5th point
          
        ! Set the values in SmartCard NVRAM
        print ReadResource$("tunemac",ID_TUNEMAC_WRITING_VALUES_316) + \
              "This will take a few moments.  Please wait."
          MSSCWrite "msc:parm:pset emvgain0n," + val$(EmvGain0)
          MSSCWrite "msc:parm:pset emvgain1n," + val$(EmvGain1)
          MSSCWrite "msc:parm:pset emvgain2n," + val$(EmvGain2)
        ! write to memory as well
          MSSCWrite "msc:parm emvgain0n," + val$(EmvGain0)
          MSSCWrite "msc:parm emvgain1n," + val$(EmvGain1)
          MSSCWrite "msc:parm emvgain2n," + Val$(EmvGain2)
        
        WinUpdate Off  
        ! Update Negative Gain Curve Register
          nPoints = 5  ! Set the number of columns in the gain data object to 5
          NewObj GainCurve[CurrPol+2], 2, 1, nPoints !* Create new gain data object
          SetObjHdrText GainCurve[CurrPol+2], "Title", "Negative Gain Curve"
          DelObj GainCurve[CurrPol+3]               ! Get rid of the old data object
          msat_UpdateGainCurveReg CurrPol,NegGainMass,ve6,m,b,v_1,Gain_1,v_2,Gain_2, \
            v_3,Gain_3,v_4,Gain_4,v_5,Gain_5
        WinUpdate On  
          
        ! Annotate the Gain Curve register:
          msat_AnnotGainCurve CurrPol
      
        ! Save the gain curve:
          saveobj GainCurve,_TunePath$+"GainCurve.reg",new
      
        ! Display the Gain-EMV curve on the screen, if not called by autotune:
          if Auto = 0 then
            if curvenum = 2 then
              msat_DispGainCurve,,CurrPol
            else 
              msat_DispGainCurve 0,1
            endif
          endif
      endif
      setabort on
  else
    print ReadResource$("tunemac",ID_TUNEMAC_CAN_T_CHANGE_E_319)
  endif  !* if _OffLine = 0
WinUpdate
  RETURN

ResetEMGainErr:
   On Error Print
   MStnPrintError
   RETURN

endmacro

!************************************************************************!
!************************************************************************!
name SetGain
PARAMETER targEMV default 1485
PARAMETER Auto default 0
! Gain compensation: shifts gain curve for the current polarity so that the
!                    specified target EMV will correspond to a Gain of 1.0.
!                    The target EMV will be clipped to 1400 and 2700 volts.
!
! 10/19/09  CPL Change EMV lower limit to 1000V and upper limit to 2800V. 
! 
!************************************************************************!
! Local oldGain, oldEMV, oldUseEMV, oldEMV$, tempEMV
Local  text$, tempEMV, OOR, CurrPol
Local  CurrSlope$
Local  ID_TUNEMAC_THE_MAXIMUM_AL_320
Local  ID_TUNEMAC_THE_MINIMUM_AL_321
Local  ID_TUNEMAC_SHIFTGAIN_ABOR_322
Local  ID_TUNEMAC_CAN_T_CHANGE_E_319
Local  ID_TUNEMAC_GAINCURVE_REG_323
Local  ID_TUNEMAC_DONE_BURNING_G_324
Local  ID_TUNEMAC_SLOPE_OF_LN_LN_709
Local  ID_TUNEMAC_979

ID_TUNEMAC_979                                     =  17979  
ID_TUNEMAC_THE_MAXIMUM_AL_320                      =  17320  
ID_TUNEMAC_THE_MINIMUM_AL_321                      =  17321  
ID_TUNEMAC_SHIFTGAIN_ABOR_322                      =  17322  
ID_TUNEMAC_CAN_T_CHANGE_E_319                      =  17319  
ID_TUNEMAC_GAINCURVE_REG_323                       =  17323  
ID_TUNEMAC_DONE_BURNING_G_324                      =  17324
ID_TUNEMAC_SLOPE_OF_LN_LN_709                      =  17709
  
   On Error goto SetGainErr  
   
   text$ = ""   
   OOR = 0

   if (_OffLine = 0)  then   
    ! Check for ion polarity and FastScan mode:
      MsParm IonPolarity,CurrPol
    if CurrPol > 1 then
      killit=Alert(ReadResource$("tunemac",ID_TUNEMAC_979),3,"Gain Calibration Curve")
      stop
    endif
   
     if (targEMV > 2800) then
       text$ = text$ + chr$(13) + ReadResource$("tunemac",ID_TUNEMAC_THE_MAXIMUM_AL_320)
       tempEMV = 2800
       OOR = 1
     endif
     if (targEMV < 1000) then
       text$ = text$ + chr$(13) + ReadResource$("tunemac",ID_TUNEMAC_THE_MINIMUM_AL_321)
       tempEMV = 1000
       OOR = 1
     endif
     if OOR = 1 then
       if Alert(text$, 4, "ShiftGain") = 0 then
         print ReadResource$("tunemac",ID_TUNEMAC_SHIFTGAIN_ABOR_322)
         RETURN
       else
         targEMV = tempEMV                    ! Accepts clipped value
       endif
     endif
   else
      print ReadResource$("tunemac",ID_TUNEMAC_CAN_T_CHANGE_E_319)
      RETURN
   endif
   
   !* Check and load the GainCurve register if necessary:
      if RegSize(GainCurve) = -1 then
      !* Register not loaded.  Try loading the register from disk
        if filestat(mode,_tunepath$ + "GainCurve.reg") = 1 then
          LoadObj _tunepath$ + "GainCurve.reg",, GainCurve
        else
        ! GainCurve.reg has been deleted from this system
            title$= "Gain Curve Check"
            line1$= ReadResource$("tunemac",ID_TUNEMAC_GAINCURVE_REG_323)
            line2$= chr$(13) + chr$(13) +"Please restore file or reload ChemStation software."
            _button=alert(line1$ + line2$,3,title$)  ! CPL 03/06 Replace Atuneprint statement with Alert.
            stop
        endif
      endif 
        
   !* Check the GainCurve register and initialize if necessary:
      if (RegSize(GainCurve) < 2) then
        print msat_InitGainCurveReg()  ! Initialize GainCurve register 
        ResetEMGain,,1                 ! Set GainCurve data register to default values
      else
        if (Data (GainCurve[CurrPol+2], 0,1)=0) then
          ResetEMGain,,1               ! No data exists, set GainCurve data register to default values
        endif       
      endif
      
   ! Get the current slope:
   curr_m = TabVal(GainCurve[1],CurveInfo,CurrPol+1,"Slope")
   print Readresource$("tunemac",ID_TUNEMAC_SLOPE_OF_LN_LN_709), curr_m

   ! Calculate and burn the new gain curve
     new_b = -(curr_m*ln(targEMV))        ! New intercept value, keep existing slope
    
   SetAbort Off                 !* Don't let user abort until calibration
                                !* done and burned into SmartCard and Gain Curve Register.
     ! Burn new intercept values in SmartCard NVRAM and Gain Curve Register.
       if CurrPol = 0 then
         SCintercept$ = "emvgain1"
       else
         SCintercept$ = "emvgain1n"
       endif
       b1$ = """msc:parm:pset "+SCintercept$+","""+" + val$(new_b)"
         evaluate "MSSCWrite " + b1$                               ! Intercept ("Offset")
       b2$ = """msc:parm "+SCintercept$+","""+" + val$(new_b)"
         evaluate "MSSCWrite " + b2$

   WinUpdate Off          
     ! Create data object for shifted Gain Curve:
        nPoints = 5  ! Set the number of points in the Gain Curve to 5
          NewObj GainCurve[CurrPol+2], 2, 1, nPoints
            if (CurrPol = 0) then
              SetObjHdrText GainCurve[CurrPol+2], "Title", "Positive Gain Curve"
            else
              SetObjHdrText GainCurve[CurrPol+2], "Title", "Negative Gain Curve"
            endif
       
   ! Update Gain Curve data object CPL 03/31/06
     numcols = DataCols(GainCurve[CurrPol+3])
      for i=1 to numcols
        thisEMV = Data(GainCurve[CurrPol+3],0,i)
        thisGain = Data(GainCurve[CurrPol+3],1,i)
        SetData GainCurve[CurrPol+2],0,i,thisEMV 
        SetData GainCurve[CurrPol+2],1,i,thisGain
      next i
   
     ve6 = targEMV  ! Set Ve6 to targEMV value
     SetTabVal GainCurve[1], "CurveInfo",CurrPol+1,"Offset",new_b
     SetTabVal GainCurve[1], "CurveInfo",CurrPol+1,"Ve6",ve6
   ! Update the Maximum Gain header value:
    if CurrPol = 0 then
      SetObjHdrVal GainCurve[1], "PosGainMax", Data(GainCurve[CurrPol+2], 1, 5)
    else
      SetObjHdrVal GainCurve[1], "NegGainMax", Data(GainCurve[CurrPol+2], 1, 5)
    endif
     DelObj GainCurve[CurrPol+3]  ! Get rid of the old data object
   WinUpdate On
          
    ! Annotate the Gain Curve register:
      msat_AnnotGainCurve CurrPol
  
    ! Save the gain curve:
      saveobj GainCurve,_TunePath$+"GainCurve.reg",new
  
    ! Display the Gain-EMV curve on the screen, if not called by autotune:
      if Auto = 0 then
        msat_DispGainCurve,,CurrPol
    endif
     setabort on
     Print ReadResource$("tunemac",ID_TUNEMAC_DONE_BURNING_G_324)

   RETURN
   
SetGainErr:
   On Error Print
   MStnPrintError
   RETURN   
   
endmacro

!************************************************************************!
!---- Quad Frequency utilities ------------------------------------------!
!************************************************************************!
name QF
! Reports current quad frequency
! 
!************************************************************************!
LOCAL qf1$, qf2$

Local  ID_TUNEMAC_CURRENT_QUAD_F_325
Local  ID_TUNEMAC_POWER_ON_SETTI_326
ID_TUNEMAC_CURRENT_QUAD_F_325                      =  17325  
ID_TUNEMAC_POWER_ON_SETTI_326                      =  17326  
   SCTimeout = 30
   MSSCQuery "msc:parm? quadfreq", qf1$
   MSSCQuery "msc:parm:pset? quadfreq", qf2$
   Print SPrintF$(val(qf1$),ReadResource$("tunemac",ID_TUNEMAC_CURRENT_QUAD_F_325)) + \
         SPrintF$(val(qf2$),ReadResource$("tunemac",ID_TUNEMAC_POWER_ON_SETTI_326)) 
   REMOVE SCTimeout

endmacro   !  QF

!************************************************************************!
!************************************************************************!
name SetQF
PARAMETER quadfreq default 0
! Sets current quad frequency
! 
!************************************************************************!

Local  ID_TUNEMAC_MUST_SPECIFY_A_327
ID_TUNEMAC_MUST_SPECIFY_A_327                      =  17327  
   On Error MStnPrintError
   
   if quadfreq = 0 then
      Print ReadResource$("tunemac",ID_TUNEMAC_MUST_SPECIFY_A_327)
      RETURN
   endif

   MSSCWrite "msc:parm quadfreq," + val$(quadfreq)
   QF          ! read and report quad frequencies

endmacro   !  SetQF

!************************************************************************!
!************************************************************************!
name DipQF
! Sets and reads the quad frequency
! Note: does not burn the frequency; use burnQF to store in instrument
!************************************************************************!
LOCAL qf1$, qf2$

Local  ID_TUNEMAC_QUAD_FREQUENCY_328
Local  ID_TUNEMAC_NEW_QUAD_FREQU_330
ID_TUNEMAC_QUAD_FREQUENCY_328                      =  17328  
ID_TUNEMAC_NEW_QUAD_FREQU_330                      =  17330  
   On Error goto DipQFerror

   SCTimeout = 30
   MSSCQuery "msc:parm? quadfreq", qf1$
   MSSCWrite "cal:mass:rf"
   MSSCQuery "msc:parm? quadfreq", qf2$

   if qf1$ = qf2$ then 
      Print ReadResource$("tunemac",ID_TUNEMAC_QUAD_FREQUENCY_328), qf2$, " Hz"
   else     
      Print ReadResource$("tunemac",ID_TUNEMAC_NEW_QUAD_FREQU_330), qf2$, " Hz"
   endif

   Remove SCTimeout
   
   RETURN
   
DipQFerror:
   On Error Print
   REMOVE SCTimeOut
   MStnPrintError
   
   RETURN

endmacro   !  dipQF

!************************************************************************!
!************************************************************************!
name BurnQF
! Burns the current quad frequency into NVRAM
!************************************************************************!
LOCAL qf$

Local  ID_TUNEMAC_POWER_ON_QUAD_331
ID_TUNEMAC_POWER_ON_QUAD_331                       =  17331  
   On Error goto BurnQFerror

   SCTimeout = 30
   MSSCQuery "msc:parm? quadfreq", qf$
   MSSCWrite "msc:parm:pset quadfreq,", qf$
   print ReadResource$("tunemac",ID_TUNEMAC_POWER_ON_QUAD_331), qf$, " Hz"
   
   Remove SCTimeout
   
   RETURN

endmacro   !  burnQF 

!************************************************************************!
! ---- Quad Temperature utilities ---------------------------------------!
!************************************************************************!
name QT 
! Reads quad temperature
!
!************************************************************************!
LOCAL qt, qtSet$, qtPset$

Local  ID_TUNEMAC_QUAD_TEMP_332
ID_TUNEMAC_QUAD_TEMP_332                           =  17332  
    MSZone quad, qt
    MSSCQuery "zone:name quad; set?", qtset$
    MSSCQuery "zone:name quad; pset?", qtPset$
    print ReadResource$("tunemac",ID_TUNEMAC_QUAD_TEMP_332), qt, "; setpoint: ", qtSet$, \
          "; power-on setpoint: ", qtPset$,  " (ºC)"

endmacro

!************************************************************************!
!************************************************************************!
name SetQT                    ! Downloads quad temp 
PARAMETER NewTemp default -1
!
!************************************************************************!
LOCAL NewTemp$

Local  ID_TUNEMAC_SPECIFY_A_QUAD_334
Local  ID_TUNEMAC_QUAD_TEMPERATU_335
ID_TUNEMAC_SPECIFY_A_QUAD_334                      =  17334  
ID_TUNEMAC_QUAD_TEMPERATU_335                      =  17335  
   if NewTemp = -1 then
      print ReadResource$("tunemac",ID_TUNEMAC_SPECIFY_A_QUAD_334)
   else
      MSSCWrite "zone:name quad; set " + val$(NewTemp)
      MSSCQuery "zone:name quad; set?", NewTemp$
      print ReadResource$("tunemac",ID_TUNEMAC_QUAD_TEMPERATU_335) + NewTemp$ + " ºC"
   endif

endmacro

!************************************************************************!
!************************************************************************!
name BurnQT
PARAMETER NewTemp  default -1
!
!************************************************************************!
LOCAL newTemp$

Local  ID_TUNEMAC_SPECIFY_A_POWE_337
Local  ID_TUNEMAC_POWER_ON_QUAD_338
ID_TUNEMAC_SPECIFY_A_POWE_337                      =  17337  
ID_TUNEMAC_POWER_ON_QUAD_338                       =  17338  
   if NewTemp  < 0 then 
      Print ReadResource$("tunemac",ID_TUNEMAC_SPECIFY_A_POWE_337)
   else
      MSSCWrite "zone:name quad; pset " + val$(NewTemp)
      MSSCWrite "zone:name quad; set "  + val$(NewTemp)
      MSSCQuery "zone:name quad; pset?", NewTemp$
      Print ReadResource$("tunemac",ID_TUNEMAC_POWER_ON_QUAD_338) + NewTemp$ 
   endif

endmacro

!************************************************************************!
!************************************************************************!
Name FastHeatQT	!  Macro for Fast Quadrupole Temperature Equlibration
Parameter   pRunTime Default 90
!   Version B.03.01,SR1 Release
!   Turns off turbo pump for up to 90 minutes to accelerate quad heating.  
!   During macro execution, the Quad Shroud and Estimated Quad Rod temperatures are plotted.
!   After selected time period, the turbo is turned on and the macro is ended. 

    Local i, lRefTime,lQShroud,lQTemp,lTimeScale,lUpdate,lbutton
    Local lout$		! holds outout string
    Local lT1LabelT$, lT2LabelT$, sEnterTime$, sTemp$;
    Local ID_TUNEMAC__MIN___TIME_RE_544
    Local ID_TUNEMAC_Time_1136
    Local ID_TUNEMAC_CELSIUS_1137
    Local ID_TUNEMAC_QUAD_SHROUD_1138
    Local ID_TUNEMAC_QUAD_ROD_1139
    Local ID_TUNEMAC_ENTER_TIME_1140
    Local ID_TUNEMAC_MACRO_CANCELLED_1141
    Local ID_TUNEMAC_MACRO_COMPLETED_1142
    
    ID_TUNEMAC__MIN___TIME_RE_544     = 17544
    ID_TUNEMAC_Time_1136              = 18136 ! "Time(sec)"
    ID_TUNEMAC_CELSIUS_1137           = 18137 ! "Celsius"
    ID_TUNEMAC_QUAD_SHROUD_1138       = 18138 ! "Quad Shroud Temperature"
    ID_TUNEMAC_QUAD_ROD_1139          = 18139 ! "Quad Rod Temperature (Estimated)"
    ID_TUNEMAC_ENTER_TIME_1140        = 18140 ! "Enter a time value from 15 to 90 minutes"
    ID_TUNEMAC_MACRO_CANCELLED_1141   = 18141 ! "Macro Cancelled"
    ID_TUNEMAC_MACRO_COMPLETED_1142   = 18142 ! "Macro Completed"
    
    lT1LabelT$ = ReadResource$("tunemac",ID_TUNEMAC_QUAD_SHROUD_1138)
    lT2LabelT$ = ReadResource$("tunemac",ID_TUNEMAC_QUAD_ROD_1139)
    sEnterTime$ = ReadResource$("tunemac",ID_TUNEMAC_ENTER_TIME_1140)
 
    If ( regsize( CheckQT ) > 0 ) then
        delobj CheckQT
    EndIf
    
    msscwrite "msc:parm quadto,80"
    Repeat  
    lbutton = INPUT( sEnterTime$, pRunTime )
    If lbutton = 1 Then
      If (pRunTime < 15) OR (pRunTime > 90 ) then
        lbutton = Alert (sEnterTime$, 3, sEnterTime$)
    !Until (pRunTime >= 15)
      Else 
        lTimeScale = pRunTime*60 !Convert to seconds
        lUpdate = pRunTime*6 !Update display every 10 seconds
      Endif
    Else
      Print ReadResource$("tunemac",ID_TUNEMAC_MACRO_CANCELLED_1141)
      Stop
    EndIf
    Until ((pRunTime >= 15) AND (pRunTime <= 90))
    TurbosOff ! Macro call to mstnnrt.mac
    SetQT 100 ! Macro call to mstnutil.mac
    
    i = 0
    MSZone Quad, lQShroud ! Read quad temperature
    lQTemp = lQShroud
    newobj CheckQT,2,2,lUpdate ! Setup matrix register to store quad temperature data
    SetDataVal CheckQT, 0, Step, 10 ! Set the time interval to 10 seconds
    SetData CheckQT, 1, 1, lQShroud ! Set Y1-axis (shroud) value to current temperature
    SetData CheckQT, 2, 1, 30 ! Set Y2-axis (quad) initial value to 30 degrees (cold)
    Draw 3, CheckQT,,25:105,0,1,0	! Scale the graph from 25 to 105 deg C
    SetDataText CheckQT, 0, AxisTitle, ReadResource$("tunemac",ID_TUNEMAC_Time_1136) !X-axis time
    SetDataText CheckQT, 1, AxisTitle, ReadResource$("tunemac",ID_TUNEMAC_CELSIUS_1137) !Y-axis temperature
      Dummy = NewTextAnn (CheckQT[1], "*" + lT1LabelT$,20,102,4,8,8,0xff0000,0,,3,"Arial") !Quad shroud
      Dummy = NewTextAnn (CheckQT[1], "*" + lT2LabelT$,20,99,4,8,8,0x0000ff,0,,3,"Arial") !Quad rods
    lRefTime = Time()
    While i < (lUpdate) do
        Sleep 10
        i = i + 1
        MSZone Quad, lQShroud !Read quad shroud temperature
        sTemp$ = sprintf$(lTimeScale/60,"%.2f") + ReadResource$("tunemac",ID_TUNEMAC__MIN___TIME_RE_544)        
        sTemp$ = sTemp$ + sprintf$((lTimeScale - i*10)/60,"%.2f")
        sTemp$ = sTemp$ + "  " + lT1LabelT$ + " = "
        Print sTemp$, lQShroud
        
        ! Note, the following is an approximation of the Quad rod temperature from cold (30 deg C)
        lQTemp = (-2.2e-12)*(i*i*i*i*i) + (3.23e-9)*(i*i*i*i) - (2.1e-6)*(i*i*i) + (7e-4)*(i*i) + 30 !CPL 12/07/06
        SetData CheckQT, 0, i, (Time() - lRefTime) !Update X-axis time
        SetData CheckQT, 1, i, lQShroud !Update Y1-axis (shroud) temperature
        SetData CheckQT, 2, i, lQTemp !Update Y2-axis (rod) temperature
    EndWhile
    msscwrite "msc:parm quadto,50"
    TurbosOn ! Macro call to mstnnrt.mac
    Print ReadResource$("tunemac",ID_TUNEMAC_MACRO_COMPLETED_1142)
Endmacro ! FastHeatQT

!************************************************************************!
! ---- Quad Polarity Utilities ------------------------------------------!
!************************************************************************!
name QP                         ! quad polarity
PARAMETER NewQP default -1      ! by default, only reports 
                                ! quad polarity
                                ! qp 1 or qp 0 sets quad polarity
!************************************************************************!
local a$, text$, IonPol

Local  ID_TUNEMAC__IS_NOT_A_VALI_339
Local  ID_TUNEMAC_QUAD_POLARITY_340
Local  ID_TUNEMAC___USE_BURNQP_T_341
ID_TUNEMAC__IS_NOT_A_VALI_339                      =  17339  
ID_TUNEMAC_QUAD_POLARITY_340                       =  17340  
ID_TUNEMAC___USE_BURNQP_T_341                      =  17341  
   MSParm IonPolarity, IonPol

   if NewQP <> 1 and NewQP <> 0 and NewQP <> -1 then
      Print NewQP, ReadResource$("tunemac",ID_TUNEMAC__IS_NOT_A_VALI_339)
      RETURN
   endif

   if NewQP <> -1 then
      if IonPol = 0 then                                ! positive ion value
         MSSCWrite "msc:parm quadpolp," + val$(NewQP) 
      else                                              ! negative ion value
         MSSCWrite "msc:parm quadpoln," + val$(NewQP)
      endif
      MSSCWrite "msc:parm quadpol," + val$(NewQP)
   endif

   if IonPol = 0 then
      MSSCQuery "msc:parm? quadpolp",a$ ! report quad polarity
   else
      MSSCQuery "msc:parm? quadpoln",a$
   endif

   Text$ =  ReadResource$("tunemac",ID_TUNEMAC_QUAD_POLARITY_340) + a$ 
   if NewQP <> -1 then
      Text$ = Text$ + ReadResource$("tunemac",ID_TUNEMAC___USE_BURNQP_T_341)
   endif
   
   Print Text$
   RETURN

endmacro

!************************************************************************!
!************************************************************************!
name BurnQP
PARAMETER PosIonQP default -1, NegIonQP default -1
! This macro is an alias for PSetQPol, which stores quad polarity in 
! non-volatile memory.
!
!    Quad polarity is 0 or 1
!    PosIonQP:  for positive ion polarity
!    NegIonQP:  for negative ion polarity
!
! Example:  To set quad polarity to negative for both pos and neg
!      ion polarity, after loading the macro type on the command line:
!
!    BurnQP 1,1
!
!************************************************************************!

Local  ID_TUNEMAC_QUAD_POLARITY_342
Local  ID_TUNEMAC_SYNTAX__BURNQP_343
ID_TUNEMAC_QUAD_POLARITY_342                       =  17342  
ID_TUNEMAC_SYNTAX__BURNQP_343                      =  17343  
   if (PosIonQP = -1) and (NegIonQP = -1) then
      Print ReadResource$("tunemac",ID_TUNEMAC_QUAD_POLARITY_342) + \
            ReadResource$("tunemac",ID_TUNEMAC_SYNTAX__BURNQP_343)
      RETURN
   endif

   PSetQPol PosIonQP, NegIonQP
   RETURN

endmacro

!************************************************************************!
!************************************************************************!
name PSetQPol
PARAMETER pos_set default -1, neg_set default -1
! This macro stores quad polarity in non-volatile memory.
!
!    Quad polarity is 0 or 1
!    pos_set:  for positive ion polarity
!    neg_set:  for negative ion polarity
!
! Example:  To set quad polarity to negative for both pos and neg
!      ion polarity, after loading the macro type on the command line:
!
!   PSetQPol 1,1
!
!************************************************************************!
LOCAL text$ 
Local  ID_TUNEMAC_QUAD_POLARITY_342
Local  ID_TUNEMAC_SYNTAX__PSETQP_344
Local  ID_TUNEMAC_POS__ION_QUAD_345
Local  ID_TUNEMAC_POS__ION_QUAD_346
Local  ID_TUNEMAC_NEG__ION_QUAD_347
Local  ID_TUNEMAC_NEG__ION_QUAD_348
ID_TUNEMAC_QUAD_POLARITY_342                       =  17342  
ID_TUNEMAC_SYNTAX__PSETQP_344                      =  17344  
ID_TUNEMAC_POS__ION_QUAD_345                       =  17345  
ID_TUNEMAC_POS__ION_QUAD_346                       =  17346  
ID_TUNEMAC_NEG__ION_QUAD_347                       =  17347  
ID_TUNEMAC_NEG__ION_QUAD_348                       =  17348  
 
   if (pos_set = -1) and (neg_set = -1) then
      Print ReadResource$("tunemac",ID_TUNEMAC_QUAD_POLARITY_342) + \
            ReadResource$("tunemac",ID_TUNEMAC_SYNTAX__PSETQP_344)
      RETURN
   endif

   SCTIMEOUT = 60        ! 60 sec. timeout
   if (pos_set = 0) or (pos_set = 1) then
      MSSCWrite ":msc:parm quadpolp," + val$(pos_set)
      MSSCWrite ":msc:parm:pset quadpolp," + val$(pos_set)
      text$ = ReadResource$("tunemac",ID_TUNEMAC_POS__ION_QUAD_345) + val$(pos_set) + "; "
   else
      text$ = ReadResource$("tunemac",ID_TUNEMAC_POS__ION_QUAD_346) 
   endif
   if (neg_set = 0) or (neg_set = 1) then
      MSSCWrite ":msc:parm quadpoln," + val$(neg_set)
      MSSCWrite ":msc:parm:pset quadpoln," + val$(neg_set)
      text$ = text$ + ReadResource$("tunemac",ID_TUNEMAC_NEG__ION_QUAD_347) + val$(neg_set)
   else
      text$ = text$ + ReadResource$("tunemac",ID_TUNEMAC_NEG__ION_QUAD_348)
   endif

   Remove SCTimeout
   
   print text$   
   RETURN

endmacro

!************************************************************************!
! ---- Firmware identification utilities --------------------------------!
!************************************************************************!
name MSID                          ! Read or set MS serial number
parameter newSerialNum$ default "" ! reads MS serial number by default
! Sets the global variable MSid$
!************************************************************************!
local a$

Local  ID_TUNEMAC_LC_MSD_SERIAL_349
ID_TUNEMAC_LC_MSD_SERIAL_349                       =  17349  
   if newSerialNum$ <> "" then     
      MSSCWrite "config:id:desc serialnum, '" + newSerialNum$ + "'"
   endif

   MSSCQuery "config:id:desc? serialnum", MSID$  
   MSID$ = ConvertText$(TRIM, MSID$)
   print ReadResource$("tunemac",ID_TUNEMAC_LC_MSD_SERIAL_349) + MSID$

endmacro

!************************************************************************!
!************************************************************************!
name SCid
PARAMETER verbose default 1
! Reads SmartCard code revision; returns value in the global scid$
!************************************************************************!

Local  ID_TUNEMAC_SMARTCARD_CODE_350
ID_TUNEMAC_SMARTCARD_CODE_350                      =  17350  
   MSSCQuery "*idn?", scid$
   if verbose = 1 then
      Print ReadResource$("tunemac",ID_TUNEMAC_SMARTCARD_CODE_350) + scid$
   endif
   
   RETURN

endmacro   ! SCid

!************************************************************************!
!************************************************************************!
name PDBid
PARAMETER verbose default 1
! Reads Power Distribution Board code revision; returns value in 
! the global PDBid$
!************************************************************************!

Local  ID_TUNEMAC_POWER_DISTRIBU_351
Local  ID_TUNEMAC_THIS_FUNCTION_1080
ID_TUNEMAC_POWER_DISTRIBU_351                      =  17351  
ID_TUNEMAC_THIS_FUNCTION_1080                      =  18080 

If ( pre6100() = 0 ) then
  Print ReadResource$("tunemac",ID_TUNEMAC_THIS_FUNCTION_1080)
EndIf

   MSSCQuery "msc:nrt:id? pdb", pdbid$
   if verbose = 1 then
      Print ReadResource$("tunemac",ID_TUNEMAC_POWER_DISTRIBU_351) + \
             PDBid$
   endif
          
   RETURN

endmacro   ! PDBid

!************************************************************************!
!************************************************************************!
name SBid
PARAMETER verbose default 1
! Reads SICB-LON Board firmware code revision; returns value in 
! the global SBid$
!************************************************************************!

Local  ID_TUNEMAC_SICB_LON_BOARD_352
Local  ID_TUNEMAC_THIS_FUNCTION_1080
ID_TUNEMAC_SICB_LON_BOARD_352                      =  17352 
ID_TUNEMAC_THIS_FUNCTION_1080                      =  18080 

If ( pre6100() = 0 ) then
  Print ReadResource$("tunemac",ID_TUNEMAC_THIS_FUNCTION_1080)
EndIf
 
   MSSCQuery "msc:nrt:id? sb", SBid$
   if verbose = 1 then
      Print ReadResource$("tunemac",ID_TUNEMAC_SICB_LON_BOARD_352) + \
             SBid$
   endif

endmacro   ! SBid

!************************************************************************!
!************************************************************************!
name TCid
PARAMETER verbose default 1
! Reads turbo controller interface board firmware code revision; 
! returns value in the global TCid$
!************************************************************************!

Local  ID_TUNEMAC_TURBO_CONTROLL_353
Local  ID_TUNEMAC_THIS_FUNCTION_1080
ID_TUNEMAC_TURBO_CONTROLL_353                      =  17353 
ID_TUNEMAC_THIS_FUNCTION_1080                      =  18080 

If ( pre6100() = 0 ) then
  Print ReadResource$("tunemac",ID_TUNEMAC_THIS_FUNCTION_1080)
EndIf
 
   MSSCQuery "msc:nrt:id? tpc", TCid$
   if verbose = 1 then
      Print ReadResource$("tunemac",ID_TUNEMAC_TURBO_CONTROLL_353) + \
             TCid$
   endif

endmacro   ! TCid

!************************************************************************!
!************************************************************************!
name LONversion
!  Formatted printout of lon node revisions.  Output to status line is
!  only readily useful if ListMessages is ON 
!************************************************************************!
LOCAL datetime$,tpcid$,cgid$,igid$,sbid$,pdbid$, oldmsecho
LOCAL tpcswrev$,cgswrev$,igswrev$,sbswrev$,pdbswrev$
LOCAL tpchwrev$,cghwrev$,ighwrev$,sbhwrev$,pdbhwrev$
LOCAL km2488d$,km2488e$

   ! Save ms_echo state
Local  ID_TUNEMAC_ID_STRINGS_FRO_354
Local  ID_TUNEMAC_ERROR_COMMUNIC_355
Local  ID_TUNEMAC___CONVECTRON_G_356
Local  ID_TUNEMAC______FIRMWARE_357
Local  ID_TUNEMAC_ERROR_COMMUNIC_358
Local  ID_TUNEMAC___ION_GAUGE_359
Local  ID_TUNEMAC_ERROR_COMMUNIC_360
Local  ID_TUNEMAC___TURBO_INTERF_361
Local  ID_TUNEMAC_ERROR_COMMUNIC_362
Local  ID_TUNEMAC___POWER_DIST_B_363
Local  ID_TUNEMAC_ERROR_COMMUNIC_364
Local  ID_TUNEMAC___SICB_LON_INT_365
Local  ID_TUNEMAC_THIS_FUNCTION_1080 

ID_TUNEMAC_ID_STRINGS_FRO_354                      =  17354  
ID_TUNEMAC_ERROR_COMMUNIC_355                      =  17355  
ID_TUNEMAC___CONVECTRON_G_356                      =  17356  
ID_TUNEMAC______FIRMWARE_357                       =  17357  
ID_TUNEMAC_ERROR_COMMUNIC_358                      =  17358  
ID_TUNEMAC___ION_GAUGE_359                         =  17359  
ID_TUNEMAC______FIRMWARE_357                       =  17357  
ID_TUNEMAC_ERROR_COMMUNIC_360                      =  17360  
ID_TUNEMAC___TURBO_INTERF_361                      =  17361  
ID_TUNEMAC______FIRMWARE_357                       =  17357  
ID_TUNEMAC_ERROR_COMMUNIC_362                      =  17362  
ID_TUNEMAC___POWER_DIST_B_363                      =  17363  
ID_TUNEMAC______FIRMWARE_357                       =  17357  
ID_TUNEMAC_ERROR_COMMUNIC_364                      =  17364  
ID_TUNEMAC___SICB_LON_INT_365                      =  17365  
ID_TUNEMAC______FIRMWARE_357                       =  17357 
ID_TUNEMAC_THIS_FUNCTION_1080                      =  18080 

If ( pre6100() = 0 ) then
  print ReadResource$("tunemac",ID_TUNEMAC_THIS_FUNCTION_1080)
EndIf
 
   if Check(Variable, ms_echo) = 0 then
      ms_echo = 0
   endif
   oldmsecho = ms_echo
   ms_echo = 0

   !Initialize rev strings
   km2488d$ = "PRH1.00.00"
   km2488e$ = "PRH1.00.01"

   Print ""
   Print "********************************************************************"
   Print "--------------------------------------------------------------------"
   Print ReadResource$("tunemac",ID_TUNEMAC_ID_STRINGS_FRO_354)
   MSSCQuery "msc:nrt:id? cg",cgid$
   MSSCQuery "msc:nrt:id? ig",igid$
   MSSCQuery "msc:nrt:id? tpc",tpcid$
   MSSCQuery "msc:nrt:id? pdb",pdbid$
   MSSCQuery "msc:nrt:id? sb",sbid$
   print "--------------------------------------------------------------------"

   ! Get date and time for this query
   msscquery "msc:nrt:nv? pdb,datetime",datetime$

   ! Extract revision strings from the node's ID string
   cgswrev$ = substring$(cgid$,6,,",")
   cghwrev$ = substring$(cgid$,5,,",")
   igswrev$ = substring$(igid$,6,,",")
   ighwrev$ = substring$(igid$,5,,",")
   tpcswrev$ = substring$(tpcid$,6,,",")
   tpchwrev$ = substring$(tpcid$,5,,",")
   pdbswrev$ = substring$(pdbid$,6,,",")
   pdbhwrev$ = substring$(pdbid$,5,,",")
   sbswrev$ = substring$(sbid$,6,,",")
   sbhwrev$ = substring$(sbid$,5,,",")

   ! Print out Hardware Rev and Firmware Rev of LON nodes
   if len(cgswrev$) = 0 or len(cghwrev$) = 0 then
      Print ReadResource$("tunemac",ID_TUNEMAC_ERROR_COMMUNIC_355)
   endif
   Print ReadResource$("tunemac",ID_TUNEMAC___CONVECTRON_G_356)+\
         substring$(cgid$,5,,",")+\
         ReadResource$("tunemac",ID_TUNEMAC______FIRMWARE_357)+cgswrev$

   if len(igswrev$) = 0 or len(ighwrev$) = 0 then
      Print ReadResource$("tunemac",ID_TUNEMAC_ERROR_COMMUNIC_358)
   endif
   Print ReadResource$("tunemac",ID_TUNEMAC___ION_GAUGE_359)+\
         substring$(igid$,5,,",")+\
         ReadResource$("tunemac",ID_TUNEMAC______FIRMWARE_357)+igswrev$

   if len(tpcswrev$) = 0 or len(tpchwrev$) = 0 then
      Print ReadResource$("tunemac",ID_TUNEMAC_ERROR_COMMUNIC_360)
   endif
   Print ReadResource$("tunemac",ID_TUNEMAC___TURBO_INTERF_361)+\
         substring$(tpcid$,5,,",")+\
         ReadResource$("tunemac",ID_TUNEMAC______FIRMWARE_357)+tpcswrev$

   if len(pdbswrev$) = 0 or len(pdbhwrev$) = 0 then
      Print ReadResource$("tunemac",ID_TUNEMAC_ERROR_COMMUNIC_362)
   endif
   Print ReadResource$("tunemac",ID_TUNEMAC___POWER_DIST_B_363)+\
         substring$(pdbid$,5,,",")+\
         ReadResource$("tunemac",ID_TUNEMAC______FIRMWARE_357)+pdbswrev$

   if len(sbswrev$) = 0 or len(sbhwrev$) = 0 then
      Print ReadResource$("tunemac",ID_TUNEMAC_ERROR_COMMUNIC_364)
   endif
   Print ReadResource$("tunemac",ID_TUNEMAC___SICB_LON_INT_365)+\
         sbhwrev$+\
         ReadResource$("tunemac",ID_TUNEMAC______FIRMWARE_357)+sbswrev$
   Print "--------------------------------------------------------------------"

   ms_echo = oldmsecho

   RETURN

endmacro   ! lonversion

!************************************************************************!
!************************************************************************!
name CheckVer$       ! Print out all versions 
PARAMETER ListMessagesOn default 1
! Returns "completed" or "failed: communication error."
! If ListMessWin is 0, then the listmessages window is not popped up.
!
!************************************************************************!
local Result$, swID$, ProdNum$, oldmsecho

Local  ID_TUNEMAC____LC_MSD_VERS_366
Local  ID_TUNEMAC_CHEMSTATION_SO_367
Local  ID_TUNEMAC_MS_UTILITIES_R_368
Local  ID_TUNEMAC_LC_MSD_MODEL_369
Local  ID_TUNEMAC_LC_MSD_SERIAL_370
Local  ID_TUNEMAC_SMARTCARD_CODE_371
Local  ID_TUNEMAC_ANALYZER_BOARD_372
Local  ID_TUNEMAC_I_O_BOARD_FIRM_373
ID_TUNEMAC____LC_MSD_VERS_366                      =  17366  
ID_TUNEMAC_CHEMSTATION_SO_367                      =  17367  
ID_TUNEMAC_MS_UTILITIES_R_368                      =  17368  
ID_TUNEMAC_LC_MSD_MODEL_369                        =  17369  
ID_TUNEMAC_LC_MSD_SERIAL_370                       =  17370  
ID_TUNEMAC_SMARTCARD_CODE_371                      =  17371  
ID_TUNEMAC_ANALYZER_BOARD_372                      =  17372  
ID_TUNEMAC_I_O_BOARD_FIRM_373                      =  17373  
   On Error goto CheckVerErr
   if listMessagesOn = 1 then
      ListMessages on
   endif

   ! Save ms_echo state
   if Check(Variable, ms_echo) = 0 then
      ms_echo = 0
   endif
   oldmsecho = ms_echo
   ms_echo = 0

   print ""
   print "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
   print ReadResource$("tunemac",ID_TUNEMAC____LC_MSD_VERS_366)
   print "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
   print ""
   ! get software rev
   print ReadResource$("tunemac",ID_TUNEMAC_CHEMSTATION_SO_367) + _Version$
   ! print msUtil rev
   print ReadResource$("tunemac",ID_TUNEMAC_MS_UTILITIES_R_368) + MStnUtilVer$
   SCid 0
   print ReadResource$("tunemac",ID_TUNEMAC_LC_MSD_MODEL_369) + SubString$(SCid$,2,,",")
   print ReadResource$("tunemac",ID_TUNEMAC_LC_MSD_SERIAL_370) + SubString$(SCid$,3,,",")
   print ReadResource$("tunemac",ID_TUNEMAC_SMARTCARD_CODE_371) + SubString$(SCid$,4,,",")
   print ""
   print ReadResource$("tunemac",ID_TUNEMAC_ANALYZER_BOARD_372) + nvrAnRev$()
   print ReadResource$("tunemac",ID_TUNEMAC_I_O_BOARD_FIRM_373) + nvrIORev$()
   LONVersion
   print ""

   RETURN " completed"
   
CheckVerErr:
   On Error print
   MStnPrintError
   RETURN " failed: communication error."

   ms_echo = oldmsecho

endmacro

!************************************************************************!
! ---- General utilities ------------------------------------------
!************************************************************************!
name showRF
PARAMETER mz default 1000, count default 3
! displays the RF drive, RF forward power and RF reflected power
! at a given mass setting.  
!************************************************************************!


Local  ID_TUNEMAC_M_Z_374
ID_TUNEMAC_M_Z_374                                 =  17374  
ID_TUNEMAC_M_Z_374                                 =  17374  
   MSSetRFPA mz
   sleep 2

   while count > 0 
      msscquery "sens? rfdrive", rfdrive$
      ! msscquery "sens? rfpowerf", rfpowerf$
      ! msscquery "sens? rfpowerr", rfpowerr$
      print ReadResource$("tunemac",ID_TUNEMAC_M_Z_374), mz, ";  RF Drive: ", rfdrive$
      ! print ReadResource$("tunemac",ID_TUNEMAC_M_Z_374), mz, "RF Drive: ", rfdrive$, "; Forward power: ", \
      !       rfpowerf$, "; Reverse power: ", rfpowerr$
      sleep 1
      count = count - 1
   endwhile

endmacro   ! end showRF

!************************************************************************!
!*****************************************************************************
name recapture
PARAMETER mz default 622.03, CapPer default 100, do_prof default 1
PARAMETER nPts default 10000
! Infinite loop of captures.  A profile is done before the first 
! capture if the third parameter is non-zero.  The macro is stopped
! using the abort menu item
!*****************************************************************************
LOCAL OldLogDataState

   ! Turn on logging
Local  ID_TUNEMAC_CAPTURE__RSD_378
ID_TUNEMAC_CAPTURE__RSD_378                        =  17378  
   MSLogData oldLogDataState ,1
   MSSCQuery "cap:per?", OldCapPer$
   CapPer = CapPer / 1e6   ! convert to seconds from microseconds
   MSSCWrite "cap:per " + val$(CapPer)
 
   ! Do an MSOn if specified
   if do_prof <>0 then
      MSProfile -1
   endif

   while 1=1 do
      MSCapture mz, nPts
      if capMean <> 0 then
         print ReadResource$("tunemac",ID_TUNEMAC_CAPTURE__RSD_378)+val$((capStdDev/CapMean)*100)
      endif
   endwhile
   MSLogData OldLogDataState 

endmacro   ! end recapture

!*****************************************************************************
!************************************************************************!
name HED                          ! reads or sets HED voltage
PARAMETER newVoltage default -1   ! by default, only reports 
                                  ! anything over 10000 sets to 10000
!************************************************************************!
LOCAL MaxHED, newHEDV

Local  ID_TUNEMAC_HED_SET_TO_379
ID_TUNEMAC_HED_SET_TO_379                          =  17379  
   MSParmInfo HED,,, MaxHED

   if newVoltage > MaxHED then
      newVoltage = MaxHED
   endif

   if newVoltage > -1 then
      MSParm HED,, newVoltage     ! Turns on to default
   endif

   MSParm HED, newHEDV              ! reports HED voltage
   Print ReadResource$("tunemac",ID_TUNEMAC_HED_SET_TO_379), newHEDV, " volts."
   RETURN

endmacro

!************************************************************************!
!************************************************************************!
name RampHED                
PARAMETER massNumber default -1   ! Ramps mass 3 by default 
                                  ! 0 means all masses
!************************************************************************!
LOCAL isMassSelected

   ! parameter checking
   if massNumber - floor(massNumber) <> 0  ! in case they asked for an m/z value
Local  ID_TUNEMAC_PLEASE_SPECIFY_381
ID_TUNEMAC_PLEASE_SPECIFY_381                      =  17381  
      print ReadResource$("tunemac",ID_TUNEMAC_PLEASE_SPECIFY_381) + \
            "selected masses." 
      RETURN
   endif
   
   ! anything over six gives the default
   if massNumber >  6 or massNumber < -1 then
      massNumber = -1
   endif
   
   ! Default 
   if massNumber = -1 then
      massNumber =  3
   endif

   ! Make sure the mass is selected
   if massNumber <> 0 then
      MSMassValue massNumber,,, isMassSelected
      MSMassValue massNumber,,,, 1
   endif

   if massNumber = 0 then
      MSSIMRamp HED                  ! all currently selected masses
   else
      MSSIMRamp HED, massNumber      ! indicated mass number
   endif
   
   if massNumber <> 0 then
      MSMassValue massNumber,,,, isMassSelected
   endif
   
   RETURN

endmacro

!************************************************************************!
!************************************************************************!
name Set_Lag
PARAMETER MassNumber default 2
PARAMETER Threshold default 1e4
! Determines the mass axis lag factors (scanning down) using a specified
! m/z value.  By default, massNumber 2 is used.  If the signal is 
! < Threshold in profile scan, then the macro aborts.
!
! Preconditions:
! There should be a strong, stable signal before calculating the lag factors
!************************************************************************!
LOCAL MALD0$, MALD1$, MALD2$, RetStr$, i, oldAverages, oldSamples, text$
LOCAL MassSel1, MassSel2, MassSel3, MassSel4, MassSel5, MassSel6
LOCAL Mass

Local  ID_TUNEMAC_INSUFFICIENT_S_382
Local  ID_TUNEMAC_CALCULATING_MA_383
Local  ID_TUNEMAC_MASS_LAG_FACTO_384
Local  ID_TUNEMAC___MALD1___4_2E_385
Local  ID_TUNEMAC___MALD2___4_2E_386
ID_TUNEMAC_INSUFFICIENT_S_382                      =  17382  
ID_TUNEMAC_CALCULATING_MA_383                      =  17383  
ID_TUNEMAC_MASS_LAG_FACTO_384                      =  17384  
ID_TUNEMAC___MALD1___4_2E_385                      =  17385  
ID_TUNEMAC___MALD2___4_2E_386                      =  17386  
   On Error goto Set_LagErr

   if (massNumber < 1) or (massNumber > 6) then
         massNumber = 2
   endif
   
   ! Turn off all masses except selected mass
   for i = 1 to 6
      if i = massNumber then
         text$ = "MSMassValue i, Mass,, MassSel" + val$(i) + ", 1"
         evaluate text$
      else
         text$ = "MSMassValue i,,, MassSel" + val$(i) + ", 0"
         evaluate text$
      endif
   next i
   
   MSAverages oldAverages, 9
   MSSamples  oldSamples, 20
   MSProfile 
   
   if (PeakMax2 < Threshold) then
      i = Alert(SPrintF$(Mass, ReadResource$("tunemac",ID_TUNEMAC_INSUFFICIENT_S_382)), 3, \
                "Set Lag")
      goto Set_LagExit
   endif
   Mass = BasePeak2
   
   SCTimeOut = 60

   Print SPrintF$(Mass,ReadResource$("tunemac",ID_TUNEMAC_CALCULATING_MA_383))

   MSSCWrite "cal:mass:lag " + val$(Mass)

   MSSCWrite "msc:parm:name MALD0"
   MSSCQuery "msc:parm:act? ", MALD0$
   MSSCWrite "msc:parm:name MALD1"
   MSSCQuery "msc:parm:act? ", MALD1$
   MSSCWrite "msc:parm:name MALD2"
   MSSCQuery "msc:parm:act? ", MALD2$

   RetStr$ = SPrintF$(val(MALD0$), ReadResource$("tunemac",ID_TUNEMAC_MASS_LAG_FACTO_384)) + \
             SPrintF$(val(MALD1$), ReadResource$("tunemac",ID_TUNEMAC___MALD1___4_2E_385)) + \
             SPrintF$(val(MALD2$), ReadResource$("tunemac",ID_TUNEMAC___MALD2___4_2E_386))
   
   if Check(Variable, PRTestVer$) = 1 then
      Archive_Header "SETLAG"
      Archive_Data "MASS", val$(mass)
      Archive_Data "FACTOR0", MALD0$
      Archive_Data "FACTOR1", MALD1$
      Archive_Data "FACTOR2", MALD2$
      Archive
   endif

   i = Alert(RetStr$, 2, "Set Lag")

Set_LagExit:
   Remove SCTimeOut

   ! Restore mass settings
   for i = 1 to 6
      text$ = "MSMassValue i,,,, MassSel" + val$(i)
      evaluate text$
   next i

   MSAverages , oldAverages
   MSSamples,   oldSamples
   
   RETURN
   
Set_LagErr:
   On Error Print
   MStnPrintError
   goto Set_LagExit

endmacro

!************************************************************************!
!************************************************************************!
name SCFault$
! Returns the 256-bit fault string broken up into 16 words
!************************************************************************!
LOCAL faultIn4, faultOut$, pos

   MSSCQuery "msc:flt:stat:full?", faultIn$
   ! Strip leading 0x
   FaultOut$ = "Fault: 0x "
   for i = 1 to 16
      pos = ((i-1)*4)+3
      FaultOut$ = FaultOut$ + FaultIn$[pos:pos+3] + ", "
   next i 

   RETURN FaultOut$[1:len(FaultOut$)-1]

endmacro
!************************************************************************!

!************************************************************************!
!************************************************************************!
!************************************************************************!
name flt
! shortcut for dgMSReportFault
! 
!************************************************************************!
  
   if check(macro, dgMSReportFault) = 0 then
      LoadMacroMcxOrMac _AutoMSPath$ + "hpmsdiag"
   endif 
   
   dgMSReportFault

endmacro
!************************************************************************!

!************************************************************************!
!************************************************************************!
!************************************************************************!
name scqStr$
PARAMETER queryStr$, field default 0
!
! Returns the response from the supplied SCQuery string.  If field is 
! specified, will return the field (comma separated) requested.  
!
! 12/10/2009 CPL Updated for 6100 series 'Orion' instruments
!************************************************************************!
LOCAL scqResp$

Local  ID_TUNEMAC__HAS_OCCURRED_387
ID_TUNEMAC__HAS_OCCURRED_387                       =  17387  

   ! To handle Non-Real Time (NRT) errors from 61xx series LC/MS instruments
   if (msmodeloptions > 13) AND (msmodeloptions < 27) then
     if Instr(queryStr$, "msc:nrt") > 0 then
       return "N/A"
     endif
   endif

   On Error goto SCqStrErr

   evaluate "MSSCQuery """ + queryStr$ + """, scqResp$"
   if field > 0 then
      scqResp$ = SubString$(scqResp$, field, , ",")
   endif
 
   RETURN scqResp$
   
   scqStrErr: 
   print _ErrMsg$ + ReadResource$("tunemac",ID_TUNEMAC__HAS_OCCURRED_387) + queryStr$ + ")"
   RETURN "ERROR"

endmacro

!************************************************************************!
!************************************************************************!
name PrintErrTable
PARAMETER filename$ default ""
!  This will print out the MSDLogBook register Error table, with formatted
!  time stamp.  If no filename is supplied, it will go to the printer.
!
!************************************************************************!
LOCAL i, filenum, MfgEnv, a$

Local  ID_TUNEMAC_MSD_LOGBOOK_ER_389
Local  ID_TUNEMAC_ERROR_LOGBOOK_390
ID_TUNEMAC_MSD_LOGBOOK_ER_389                      =  17389  
ID_TUNEMAC_ERROR_LOGBOOK_390                       =  17390  
   if filename$ = "" then
      filenum = 5
   else 
      filenum = 7
   endif
   
   MfgEnv = Check(Variable, PRTestVer$)
   MSID
   
   on error print
   close #filenum
   endjob
   on error goto PrintErrTableErr

   if filenum = 5 and MfgEnv = 1 then
      MfgHeaderMain "MSD Logbook Error table"
   else
      open filename$ for output as #filenum
      print #filenum, ReadResource$("tunemac",ID_TUNEMAC_MSD_LOGBOOK_ER_389) + MSID$ + \
                      "    " + Time$()
      print #filenum,  ""
   endif

   if ObjHdrType(MSDLogBook, Error) <> 4 then
      print #filenum, ReadResource$("tunemac",ID_TUNEMAC_ERROR_LOGBOOK_390)
   else
      for i = 1 to TabHdrVal(MSDLogBook, Error, "NumberOfRows")
        print #filenum, Time$(,TabVal(MSDLogBook, Error, i, "Time"))
        print #filenum, "   " + TabText$(MSDLogBook, Error, i, "EventMessage") 
        if (filenum = 5) and (yLoc() > YlogMax() - 3) then
           FormFeed
           if Check(Variable, PRTestVer$) = 1 then
              MfgHeaderPrint
           endif
         endif
      next i
   endif
   
PrintErrTableExit:
   On Error print
   EndJob
   close #filenum

   if filenum <> 5 then
!       a$ = "notepad.exe " + FileName$
 
       a$ = "notepad.exe" + chr$(34) + FileName$ + chr$(34) 	 
       execnowait a$, 1
   endif

   RETURN   
      

PrintErrTableErr:   
   On Error Print
   MStnPrintError
   goto PrintErrTableExit
   
endmacro

!************************************************************************!
!************************************************************************!
name MSLight
PARAMETER PrintReport default 0
! This status light macro requires visual inspection of the display panel.
! It sets the light to a color and asks the user to visually verify if the
! color displaying on the panel is correct or not.
!
! The data values correspond to colors on the Sprite display board.
! All of these data words are send to address 3.
!
! Color     Data Word   Blinking
! --------------------------------------
! Off       0x0007
! Green     0x0002      0x000A
! Yellow    0x0000      0x0008
! Red       0x0005      0x000D
!
! There are also other combinations that produce dim green (0x0003 &
! 0x0006), light orange (0x0001), orange (0x0004), but the fundamental
! colors are the ones above that need to be tested.
!************************************************************************!
LOCAL statusOff, statusGrn, statusYel, statusRed, MfgEnv, resp
LOCAL statusOff$, statusGrn$, statusYel$, statusRed$, msg$
LOCAL Disp$

   ! Initialization
Local  ID_TUNEMAC_THE_STATUS_LIG_391
Local  ID_TUNEMAC_IS_THE_STATUS_392
Local  ID_TUNEMAC_IS_STATUS_LIGH_393
Local  ID_TUNEMAC_EVALUATING_STA_394
Local  ID_TUNEMAC_GENERATING_REP_395
Local  ID_TUNEMAC_LC_MSD_STATUS_396
Local  ID_TUNEMAC_STATUS_LIGHT_P_397
Local  ID_TUNEMAC_LC_MSD_STATUS_398
Local  ID_TUNEMAC_STATUS_LIGHT_399

Local  ID_TUNEMAC_LC_MSD_STATUS_400
ID_TUNEMAC_THE_STATUS_LIG_391                      =  17391  
ID_TUNEMAC_IS_THE_STATUS_392                       =  17392  
ID_TUNEMAC_IS_STATUS_LIGH_393                      =  17393  
ID_TUNEMAC_EVALUATING_STA_394                      =  17394  
ID_TUNEMAC_GENERATING_REP_395                      =  17395  
ID_TUNEMAC_LC_MSD_STATUS_396                       =  17396  
ID_TUNEMAC_STATUS_LIGHT_P_397                      =  17397  
ID_TUNEMAC_LC_MSD_STATUS_398                       =  17398  
ID_TUNEMAC_STATUS_LIGHT_399                        =  17399  
ID_TUNEMAC_LC_MSD_STATUS_396                       =  17396  
ID_TUNEMAC_LC_MSD_STATUS_400                       =  17400  
   statusOff = 0
   statusGrn = 0
   statusYel = 0
   statusRed = 0
   statusOff$ = "PASS"
   statusGrn$ = "PASS"
   statusYel$ = "PASS"
   statusRed$ = "PASS"
   MfgEnv = Check(Variable, PRTestVer$)
   Disp$ = ""
   msg$ = "The status light test requires visual inspection " + chr$(13) + \
          "of the status light." + chr$(13)
   print  ReadResource$("tunemac",ID_TUNEMAC_THE_STATUS_LIG_391)

   ! Off Status
   msscwrite "msdc:mse 3,7"
   sleep 1
   print msg$
   statusoff = Alert(msg$ + "Is the status light OFF?",5)
   if (statusOff = -1) then
      goto LabelDone
   endif

   ! Green Status
   msscwrite "msdc:mse 3,2"
   sleep 1
   statusGrn = Alert(msg$ + "Is the status light GREEN?",5)
   if (statusGrn = -1) then
      goto LabelDone
   endif

   ! Yellow Status
   msscwrite "msdc:mse 3,0"
   sleep 1
   statusYel = alert(msg$ + ReadResource$("tunemac",ID_TUNEMAC_IS_THE_STATUS_392),5)
   if (statusYel = -1) then
      goto LabelDone
   endif

   ! Red Status
   msscwrite "msdc:mse 3,5"
   sleep 1
   statusRed = alert(msg$ + ReadResource$("tunemac",ID_TUNEMAC_IS_STATUS_LIGH_393),5)
   if (statusRed = -1) then
      goto LabelDone
   endif


   ! Evaluate Each Status
   print ReadResource$("tunemac",ID_TUNEMAC_EVALUATING_STA_394)
   if (statusOff = 0) then
      statusOff$ = "FAIL"
      Disp$ = "OFF "
   endif
   if (statusGrn = 0) then
      statusGrn$ = "FAIL"
      Disp$ = Disp$ + "GREEN "
   endif
   if (statusYel = 0) then
      statusYel$ = "FAIL"
      Disp$ = Disp$ + "YELLOW "
   endif
   if (statusRed = 0) then
      statusRed$ = "FAIL"
      Disp$ = Disp$ + "RED "
   endif

   ! Generate report
   print ReadResource$("tunemac",ID_TUNEMAC_GENERATING_REP_395)

   if (printreport = 0) then  ! display report on screen
      if ((statusOff + StatusGrn + statusYel + StatusRed) < 4) then
         resp = alert(ReadResource$("tunemac",ID_TUNEMAC_LC_MSD_STATUS_396) + chr$(13) + Disp$,2)
      else
         resp = alert(ReadResource$("tunemac",ID_TUNEMAC_STATUS_LIGHT_P_397),2)
      endif
   else           ! print report to printer
      if MfgEnv = 1 then
         MfgHeaderMain "Status Light Test"
      else
         GetCurrentPrinterSetup                    !3-02PR utilize current printer setup
!!         On Error Print
!!         EndJob
!!         Close #5
         if DevNum() <> 5 then
            On Error CloseDeviceBeforeOpenDevice   !3-02PR close only if error on OpenDevice
            OpenDevice "Printer" as #5
         endif
         On Error Print
         BeginJob
         print #5, ReadResource$("tunemac",ID_TUNEMAC_LC_MSD_STATUS_398) + MSID$ + \
                         "   " + Time$()
         print #5,  ""
      endif

      print #5, ReadResource$("tunemac",ID_TUNEMAC_STATUS_LIGHT_399)
      print #5, " "
      print using #5, "%%%%%%   %%%%%%/","Color","Status"
      print       #5, "---------------"
      print using #5, "%%%%%%   %%%%%%/","Off", statusOff$
      print using #5, "%%%%%%   %%%%%%/","Green", statusGrn$
      print using #5, "%%%%%%   %%%%%%/","Yellow", statusYel$
      print using #5, "%%%%%%   %%%%%%/","Red", statusRed$ 
      On Error print
      close #5
      EndJob
   endif

LabelDone:
   if ((statusOff + StatusGrn + statusYel + StatusRed) < 4) then
      print ReadResource$("tunemac",ID_TUNEMAC_LC_MSD_STATUS_396)+Disp$
   else
      print ReadResource$("tunemac",ID_TUNEMAC_LC_MSD_STATUS_400)
   endif
   
   RETURN

endmacro

!**************************************************************************
!************************************************************************!
name PSDelay                    ! Polarity switching delay
PARAMETER NewPSDelay default -1 ! by default, only reports the delay
                                ! Use burnPSDelay to change power-on default
!************************************************************************!
local a$, b$, text$

Local  ID_TUNEMAC_ERROR__POLARIT_401
Local  ID_TUNEMAC_CURRENT_POLARI_402
Local  ID_TUNEMAC_POWER_ON_POLAR_404
Local  ID_TUNEMAC_MSD__POLARITY_406
Local  ID_TUNEMAC__MSEC_405
ID_TUNEMAC_ERROR__POLARIT_401                      =  17401  
ID_TUNEMAC_CURRENT_POLARI_402                      =  17402  
ID_TUNEMAC_POWER_ON_POLAR_404                      =  17404  
ID_TUNEMAC_MSD__POLARITY_406                       =  17406  
ID_TUNEMAC__MSEC_405                               =  17405  
   if NewPSDelay <> -1 then    
      if NewPSDelay < 0 then 
         Print ReadResource$("tunemac",ID_TUNEMAC_ERROR__POLARIT_401)
         RETURN
      else
         MSSCWrite "msc:parm mpst, " + val$(NewPSDelay)
      endif
   endif

   MSSCQuery "msc:parm? mpst", a$
   MSSCQuery "msc:parm:pset? mpst", b$
   Print ReadResource$("tunemac",ID_TUNEMAC_CURRENT_POLARI_402) + a$ + " mSec; " + \
         ReadResource$("tunemac",ID_TUNEMAC_POWER_ON_POLAR_404) + b$ + " mSec."

   ! Make a logbook entry
   WriteToLogbook ReadResource$("tunemac",ID_TUNEMAC_MSD__POLARITY_406) + \
                  val$(NewPSDelay) + ReadResource$("tunemac",ID_TUNEMAC__MSEC_405)

   ! Change ChemStation variable for delay (in seconds)
   
   MSCFGPOLSWITCH = val(a$) * 0.001 

   RETURN

endmacro       ! PSDelay

!************************************************************************!
!************************************************************************!
name IonDelay                    ! Ionization switching delay
PARAMETER NewIonDelay default -1 ! by default, only reports the delay
                                ! Use burnIonDelay to change power-on default
!************************************************************************!
local a$, b$, text$

Local  ID_TUNEMAC_ERROR__IONIZAT_407
Local  ID_TUNEMAC_CURRENT_IONIZA_408
Local  ID_TUNEMAC_MSD__IONIZATIO_409
ID_TUNEMAC_ERROR__IONIZAT_407                      =  17407  
ID_TUNEMAC_CURRENT_IONIZA_408                      =  17408  
ID_TUNEMAC_MSD__IONIZATIO_409                      =  17409  
   if NewIonDelay <> -1 then    
      if NewIonDelay < 0 then 
         Print ReadResource$("tunemac",ID_TUNEMAC_ERROR__IONIZAT_407)
         RETURN
      else
         MSSCWrite "msc:parm ionst, " + val$(NewIonDelay)
      endif
   endif

   MSSCQuery "msc:parm? ionst", a$
   MSSCQuery "msc:parm:pset? ionst", b$
   Print ReadResource$("tunemac",ID_TUNEMAC_CURRENT_IONIZA_408) + a$ + " mSec; " + \
         "power-on ionization switching delay: " + b$ + " mSec."

   ! Make a logbook entry
   WriteToLogbook ReadResource$("tunemac",ID_TUNEMAC_MSD__IONIZATIO_409) + \
                  val$(NewIonDelay) + " mSec."

   ! Change ChemStation variable for delay (in seconds)
   
   MSCFGIONSWITCH = val(a$) * 0.001 

   RETURN

endmacro       ! IonDelay

!************************************************************************!
!************************************************************************!
name BurnPSDelay
PARAMETER NewPSDelay default -1   ! Polarity switching delay
! Stores a new polarity switching delay value to non-volatile RAM
!************************************************************************!

Local  ID_TUNEMAC_ERROR__POLARIT_401
Local  ID_TUNEMAC_CURRENT_POLARI_402
ID_TUNEMAC_ERROR__POLARIT_401                      =  17401  
ID_TUNEMAC_CURRENT_POLARI_402                      =  17402  
   if NewPSDelay <> -1 then    
      if NewPSDelay < 0 then 
         Print ReadResource$("tunemac",ID_TUNEMAC_ERROR__POLARIT_401)
         RETURN
      else
         MSSCWrite "msc:parm:pset mpst, " + val$(NewPSDelay)
      endif
  endif

   MSSCQuery "msc:parm? mpst", a$
   MSSCQuery "msc:parm:pset? mpst", b$
   Print ReadResource$("tunemac",ID_TUNEMAC_CURRENT_POLARI_402) + a$ + " mSec; " + \
         "power-on polarity switching delay: " + b$ + " mSec."
   RETURN

endmacro

!************************************************************************!
!************************************************************************!
name BurnIonDelay
PARAMETER NewIonDelay default -1   ! Ionization switching delay
! Stores a new ionization switching delay value to non-volatile RAM
!************************************************************************!

Local  ID_TUNEMAC_ERROR__IONIZAT_407
Local  ID_TUNEMAC_CURRENT_IONIZA_408
ID_TUNEMAC_ERROR__IONIZAT_407                      =  17407  
ID_TUNEMAC_CURRENT_IONIZA_408                      =  17408  
   if NewIonDelay <> -1 then    
      if NewIonDelay < 0 then 
         Print ReadResource$("tunemac",ID_TUNEMAC_ERROR__IONIZAT_407)
         RETURN
      else
         MSSCWrite "msc:parm:pset ionst, " + val$(NewIonDelay)
      endif
  endif

   MSSCQuery "msc:parm? ionst", a$
   MSSCQuery "msc:parm:pset? ionst", b$
   Print ReadResource$("tunemac",ID_TUNEMAC_CURRENT_IONIZA_408) + a$ + " mSec; " + \
         "power-on ionization switching delay: " + b$ + " mSec."
   RETURN

endmacro

!************************************************************************!
!****************************************************************************!
name MSTNCpTerminate 

PARAMETER CpProcess$ default ""

!
! Description: Macro will get the CP given by CpProcess$ if it is currently active.
!              otherwise no action will be taken and no error will be generated.
!  
!****************************************************************************!
LOCAL CpXY$, i

  i = 1   
  CpXY$ = CpName$(i)
  while CpXY$ <> "" do
      if UpperCase$(CpXY$) = UpperCase$(CpProcess$) then
     CpTerminate CpProcess$
     return
   else
     i = i + 1
      CpXY$ = CpName$(i)
   endif
  endwhile

  return

endmacro !MSTNCpTerminate

!*******************************************************************************
Name Pre6100
! Function returns 1 if an MSD model G1946 or G1956 is connected.
! Otherwise the function returns 0.
!
! Test if register MSAcqInfo exist. If not, try to load it.
! If it fails, return 0
! Check if header variable InstrumentType exists. If not return 0
! Test if InstrumentType is 1946 or 1956. If not, return 0. If yes, return 1
!*******************************************************************************
Local lModel$
    If ( regsize( MSAcqInfo ) < 1 ) then
	MSAcqInfo
    Endif
    If ( regsize( MSAcqInfo ) < 1 ) then
        Return 0                             !----->
    Endif
    If ( ObjHdrType( MSAcqInfo, InstrumentType ) <> 0 ) then
        Return 0                             !----->
    Endif
    lModel$ = ObjHdrText$( MSAcqInfo[1], "InstrumentType")
    If ( instr( lModel$, "1946") > 0 ) OR ( instr( lModel$, "1956" ) > 0 ) then
        Return 1                             !----->
    Else
        Return 0                             !----->
    Endif
Endmacro ! pre6100()
!===============================================================================
Name CDSshort  ! Makes waiting time for calibrant switching short (ueff 060830)
               ! Original waiting time is restored when MSD reboots.
    MSSCWrite "MSC:PARM:SET CDSDONPS,3"
    MSSCWrite "MSC:PARM:SET CDSDONCD,1"
    MSSCWrite "MSC:PARM:SET CDSDOFP2,1"
    MSSCWrite "MSC:PARM:SET CDSDOFP1,1"
    MSSCWrite "MSC:PARM:SET CDSDOFRS,1"
EndMacro ! CDSshort
!===============================================================================
!*******************************************************************************
MSutil
!----------- end of file ------------------------------------------------------!
