! $Header: /PHX3D/parts/macros/lcapplic.mac 4.0 1996-03-22 17:45:10-05 hmgr Exp $
!
! This macro file is just a dummy to ensure backwards compatibility.
! The macros that were here previously have been moved to other places.
! The file itself, plus the empty initialization macro, however, has to
! be shipped still, because in the previous revision the file applics.mac
! had a line 'macro "lcapplic.mac", go'. As the file applics.mac will not be
! shipped anymore in the product (to ease automatic adding of additional
! applications), applics.mac will stay untouched on the customer's disc.
! Therefore the line 'macro "lcapplic.mac", go' has to be effectively a
! null statement.

Name Init_LCapplic

  return
endMacro
