[Signature]
ID605=izQjIBRXvsrL/osjk/o8MsZt00000000
[Version]
ID=G2715 Version: A.06.05
[General]
Type=0
Run Duration=900.00
NoLimit=0
NoMSD=0
PeakWidth=3.60
ScanSpeedOverride=0
Solvent Delay=0.00
Tune File=atunes.tun
Polarity=1
IonizationMode=6
Group Ions=1
Acq Mode=1
Zones=4
Scan Groups=1
Data Curves=0
Data Curve Rate=2000
Acq Mode 2=0
Acq Mode 3=0
Acq Mode 4=0
Signal Summary=
Signal Summary 2=
Signal Summary 3=
Signal Summary 4=
Signal Active=1
Signal Active 2=0
Signal Active 3=0
Signal Active 4=0
Cycle Time=100
Cycle Time 2=0
Cycle Time 3=0
Cycle Time 4=0
Polarity 2=0
Polarity 3=0
Polarity 4=0
Group Ions 2=1
Group Ions 3=1
Group Ions 4=1
Scan Groups 2=1
Scan Groups 3=1
Scan Groups 4=1
[DynamicParm 1]
GlobalId=11
Enable=0
DynamicValues=
[Zone 1]
ID=6
On=1
Soft Max=350.00
Set Point=350.00
Type=0
[Zone 2]
ID=7
On=1
Soft Max=500.00
Set Point=425.00
Type=0
[Zone 3]
ID=13
On=1
Soft Max=13.00
Set Point=6.00
Type=0
[Zone 4]
ID=14
On=1
Soft Max=60.00
Set Point=60.00
Type=0
[Ions 1]
Group Name=Group 1
Start Time=0.00
Resolution=0
Gain=3.0
Fragmentor=100
Plot Index 1=0
Plot Index 2=0
Number of Ions=1
Ion 1=138.0,340
Row OnOff=1
Frgmtr Ion 1=100
[Scan 1]
Start Time=0.00
Low Mass=100.0
High Mass=500.0
Threshold=0
Sampling=6
Stepsize=0.10
Gain=1.0
Fragmentor=80
Low Plot 1=100.0
High Plot 1=500.0
Low Plot 2=100.0
High Plot 2=500.0
Row OnOff=1
[Filters]
Mass Type=1
Mass Param=0.300
Mass Sigma=2.00
Time Type=1
Time Param=1.800
Time Sigma=2.00
[Plot]
Plot Type 1=0
Plot Type 2=1
[DynamicParm 2 1]
GlobalId=-1
Enable=0
DynamicValues=
[DynamicParm 3 1]
GlobalId=-1
Enable=0
DynamicValues=
[DynamicParm 4 1]
GlobalId=-1
Enable=0
DynamicValues=
[Ions 2 1]
Group Name=1
Start Time=0.00
Row OnOff=1
Resolution=1
Gain=1.0
Plot Index 1=0
Plot Index 2=0
Number of Ions=1
Ion 1=74.1,340
Frgmtr Ion 1=200
[Ions 3 1]
Group Name=1
Start Time=0.00
Row OnOff=1
Resolution=1
Gain=1.0
Plot Index 1=0
Plot Index 2=0
Number of Ions=1
Ion 1=74.1,340
Frgmtr Ion 1=200
[Ions 4 1]
Group Name=1
Start Time=0.00
Row OnOff=1
Resolution=1
Gain=1.0
Plot Index 1=0
Plot Index 2=0
Number of Ions=1
Ion 1=74.1,340
Frgmtr Ion 1=200
[Scan 2 1]
Start Time=0.00
Row OnOff=1
Low Mass=50.0
High Mass=550.0
Threshold=500
Sampling=5
Stepsize=0.10
Gain=1.0
Fragmentor=100
Low Plot 1=50.0
High Plot 1=550.0
Low Plot 2=50.0
High Plot 2=550.0
[Scan 3 1]
Start Time=0.00
Row OnOff=1
Low Mass=50.0
High Mass=550.0
Threshold=500
Sampling=5
Stepsize=0.10
Gain=1.0
Fragmentor=200
Low Plot 1=50.0
High Plot 1=550.0
Low Plot 2=50.0
High Plot 2=550.0
[Scan 4 1]
Start Time=0.00
Row OnOff=1
Low Mass=50.0
High Mass=550.0
Threshold=500
Sampling=5
Stepsize=0.10
Gain=1.0
Fragmentor=200
Low Plot 1=50.0
High Plot 1=550.0
Low Plot 2=50.0
High Plot 2=550.0
[Filters 2]
Mass Type=1
Mass Param=0.300
Mass Sigma=2.00
Time Type=1
Time Param=1.800
Time Sigma=2.00
[Filters 3]
Mass Type=1
Mass Param=0.300
Mass Sigma=2.00
Time Type=1
Time Param=1.800
Time Sigma=2.00
[Filters 4]
Mass Type=1
Mass Param=0.300
Mass Sigma=2.00
Time Type=1
Time Param=1.800
Time Sigma=2.00
[FractionCollection]
Mode=0
CSV File=
Signal 1=0
Signal 2=0
Signal 3=0
Signal 4=0
Detector=0
Standard Positive Adducts=0,0,0,0,0
Standard Negative Adducts=0
User-defined Positive Adducts=0, ,0, ,0,          
User-defined Negative Adducts=0, ,0, ,0,          
Number Of Base Masses=0
Model=0
Min Peak Width=0.10
Max Peak Width=0.50
Time Limit=1.00
MSD Delay=0.00
MSD Threshold=3000
MSD Peak Slope=1000
Other Delay=0.00
Other Threshold=100
Other Peak Slope=10
MSD Window=1.0
MSD Output Range=65535
Other Full Scale=0.10
[Parameters]
ID 1=1
Mode 1=1
Value 1=4000.000000,0.000000
ID 2=5
Mode 2=1
Value 2=2500.000000,2500.000000
ID 3=7
Mode 3=1
Value 3=4.000000,0.000000
ID 4=8
Mode 4=1
Value 4=10.000000,20.000000
ID 5=-1
Mode 5=0
Value 5=0.000000,0.000000
[Time Events]
Number Events=0
