# -*- coding: utf-8 -*-
"""Generate PART2_L4_P0_P4.md — T13 full 7-field tables for P0~P4."""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "deploy" / "GC1_RUNTIME_DESIGN_PART2_L4_P0_P4.md"

# (id, title, channel, pre, action, post, on_fail, timeout_ms)
ATOMS: list[tuple[str, str, str, str, str, str, str, int]] = [
    # P0
    (
        "Ω.A.L4.P0.01",
        "hancom 잔류 창 정리",
        "H",
        "Ω.A.L0.WIN.04",
        "P0.01a..P0.01g (hancom loop)",
        "CMP len(hancom_handles)==0",
        "{code:null,max_attempt:1}",
        30000,
    ),
    (
        "Ω.A.L4.P0.02",
        "Autochro 창 연결·배치",
        "H",
        "Ω.A.L2.GEX.03, Ω.A.B.IDENT.07",
        "P0.02a..P0.02q (WIN chain + move)",
        "Ω.A.L0.WIN.06, Ω.A.L0.WIN.07",
        "{code:E_WIN_NONE,max_attempt:2,retry_delay_ms:1000}",
        60000,
    ),
    (
        "Ω.A.L4.P0.03",
        "data_name 읽기",
        "H|E",
        "Ω.A.L4.P0.02 ok",
        "P0.03a..P0.03g (DN-T/DN-R)",
        "CMP data_name non-empty",
        "{code:E_DATA_NAME,max_attempt:1}",
        20000,
    ),
    (
        "Ω.A.L4.P0.04",
        "pdf_path_planned",
        "PURE|STW",
        "Ω.A.L4.P0.03 ok, data_name STW",
        "P0.04a L1.01, P0.04b L1.02, P0.04c STW",
        "CMP pdf_path_planned set",
        "{code:null,max_attempt:1}",
        5000,
    ),
    (
        "Ω.A.L4.P0.05",
        "fresh skip",
        "PURE|CMP",
        "Ω.A.L4.P0.04 ok",
        "P0.05a L1.05, P0.05b CMP force|fresh",
        "CMP skip_decision recorded",
        "{code:EARLY_OK,max_attempt:1}",
        5000,
    ),
    (
        "Ω.A.L4.P0.06",
        "job init",
        "STW",
        "Ω.A.L4.P0.05 not EARLY_OK",
        "P0.06a..P0.06d (job_id, atoms pending)",
        "CMP job_id, phase_current=P0",
        "{code:null,max_attempt:1}",
        5000,
    ),
    # P1
    (
        "Ω.A.L4.P1.01",
        "제어 탭 선택",
        "H",
        "Ω.A.L4.P0.06 ok, Ω.A.L0.TAB.01",
        "P1.01a TAB.04?, P1.01b select(1), P1.01c WAIT 800",
        "Ω.A.L0.TAB.04",
        "{code:E_P1_TAB,max_attempt:2,retry_delay_ms:800}",
        15000,
    ),
    (
        "Ω.A.L4.P1.02",
        "제어 목록 ListView",
        "H",
        "Ω.A.L0.TAB.04",
        "P1.02a L0-LV lower, P1.02b L0-LVP pick",
        "CMP control_sync_list non-null",
        "{code:null,max_attempt:1}",
        10000,
    ),
    (
        "Ω.A.L4.P1.03",
        "시료표 focus",
        "H",
        "Ω.A.L4.P1.02 ok",
        "P1.03 W32 set_focus",
        "CMP focused hwnd",
        "{code:null,max_attempt:1}",
        5000,
    ),
    (
        "Ω.A.L4.P1.04",
        "중립 클릭",
        "H",
        "Ω.A.L4.P1.03 ok",
        "P1.04 W32 click_input neutral",
        "CMP click sent",
        "{code:null,max_attempt:1}",
        5000,
    ),
    (
        "Ω.A.L4.P1.05",
        "rel_x",
        "PURE",
        "Ω.A.L4.P1.04 ok",
        "P1.05 PURE rel_x=max(20,w//4)",
        "CMP rel_x>0",
        "{code:null,max_attempt:1}",
        1000,
    ),
    (
        "Ω.A.L4.P1.06",
        "rel_y",
        "PURE",
        "Ω.A.L4.P1.05 ok",
        "P1.06 PURE rel_y=max(12,h-24)",
        "CMP rel_y>0",
        "{code:null,max_attempt:1}",
        1000,
    ),
    (
        "Ω.A.L4.P1.07",
        "double_click 동기화",
        "H",
        "Ω.A.L4.P1.05, Ω.A.L4.P1.06",
        "P1.07 W32 double_click_input",
        "CMP dblclick sent",
        "{code:null,max_attempt:1}",
        5000,
    ),
    (
        "Ω.A.L4.P1.08",
        "동기화 대기",
        "W",
        "Ω.A.L4.P1.07 ok",
        "P1.08 WAIT 1500",
        "CMP elapsed>=1500",
        "{code:null,max_attempt:1}",
        2000,
    ),
    (
        "Ω.A.L4.P1.09",
        "분석목록 탭",
        "H",
        "Ω.A.L4.P1.08 ok",
        "P1.09a TAB.03?, P1.09b select(0) WAIT 800",
        "Ω.A.L0.TAB.03",
        "{code:E_P1_TAB,max_attempt:2,retry_delay_ms:800}",
        15000,
    ),
    (
        "Ω.A.L4.P1.10",
        "분석목록 탭 검증",
        "CMP",
        "Ω.A.L4.P1.09 done",
        "P1.10 CMP TAB.03",
        "Ω.A.L0.TAB.03",
        "{code:E_P1_TAB,max_attempt:1}",
        3000,
    ),
    (
        "Ω.A.L4.P1.11",
        "eye 탭 검증 (opt)",
        "E",
        "GC1_RUNTIME_VERIFY_EYE=1, Ω.A.L4.P1.10 ok",
        "P1.11 TASK verify_active_tab_analysis",
        "TASK verify_active_tab_analysis pass",
        "{code:E_VERIFY_TAB,max_attempt:1}",
        30000,
    ),
    # P2
    (
        "Ω.A.L4.P2.01",
        "분석목록 탭",
        "H",
        "Ω.A.L4.P1.10 ok",
        "P2.01 H.select_analysis_tab",
        "Ω.A.L0.TAB.03",
        "{code:null,max_attempt:1}",
        10000,
    ),
    (
        "Ω.A.L4.P2.02",
        "시료표 ListView",
        "H",
        "Ω.A.L0.TAB.03",
        "P2.02 L0-LVP upper",
        "CMP sample_list non-null",
        "{code:null,max_attempt:1}",
        10000,
    ),
    (
        "Ω.A.L4.P2.03",
        "focus+click neutral",
        "H",
        "Ω.A.L4.P2.02 ok",
        "P2.03a set_focus, P2.03b rel_x, P2.03c rel_y, P2.03d click",
        "CMP focus on sample_list",
        "{code:E_P2_FOCUS,max_attempt:3,retry_delay_ms:500,fallback:re-P2.03}",
        15000,
    ),
    (
        "Ω.A.L4.P2.04",
        "Ctrl+A",
        "H",
        "Ω.A.L4.P2.03 ok",
        "P2.04 send_keys ^a",
        "CMP keys sent",
        "{code:E_P2_SELECT,max_attempt:2,retry_delay_ms:300}",
        5000,
    ),
    (
        "Ω.A.L4.P2.05",
        "선택 대기",
        "W",
        "Ω.A.L4.P2.04 ok",
        "P2.05 WAIT 500",
        "CMP elapsed>=500",
        "{code:null,max_attempt:1}",
        1000,
    ),
    # P3
    (
        "Ω.A.L4.P3.01",
        "분석목록 탭",
        "H",
        "Ω.A.L4.P2.05 ok",
        "P3.01 H.select_analysis",
        "Ω.A.L0.TAB.03",
        "{code:null,max_attempt:1}",
        10000,
    ),
    (
        "Ω.A.L4.P3.02",
        "시료표 ListView",
        "H",
        "Ω.A.L0.TAB.03",
        "P3.02 L0-LVP upper",
        "CMP sample_list non-null",
        "{code:null,max_attempt:1}",
        10000,
    ),
    (
        "Ω.A.L4.P3.03",
        "우클릭 준비",
        "H",
        "Ω.A.L4.P3.02 ok",
        "P3.03a focus, P3.03b coords, P3.03c rclick, P3.03d WAIT 350",
        "CMP rclick sent",
        "{code:null,max_attempt:1}",
        10000,
    ),
    (
        "Ω.A.L4.P3.04",
        "초기화 메뉴",
        "H",
        "Ω.A.L4.P3.03 ok",
        "P3.04.1..P3.04.11 (#32768 loop)",
        "CMP menu clicked",
        "{code:E_P3_MENU,max_attempt:3,retry_delay_ms:120,fallback:E}",
        20000,
    ),
    (
        "Ω.A.L4.P3.05",
        "초기화 대기",
        "W",
        "Ω.A.L4.P3.04 ok",
        "P3.05 WAIT 800",
        "CMP elapsed>=800",
        "{code:null,max_attempt:1}",
        2000,
    ),
    (
        "Ω.A.L4.P3.06",
        "피크표 cleared 검증",
        "E",
        "Ω.A.L4.P3.05 ok",
        "P3.06 TASK verify_peak_table_cleared",
        "TASK zero_ratio>=0.85",
        "{code:E_VERIFY_PEAK,max_attempt:1}",
        30000,
    ),
    # P4
    (
        "Ω.A.L4.P4.01",
        "MTD 경로",
        "F|L0",
        "Ω.A.L4.P3.06 ok",
        "P4.01 Ω.A.L0.MTD.01..03",
        "Ω.A.L0.MTD.03 FS.isfile",
        "{code:E_MTD_MISSING,max_attempt:1}",
        10000,
    ),
    (
        "Ω.A.L4.P4.02",
        "분석목록 탭",
        "H",
        "Ω.A.L4.P4.01 ok",
        "P4.02 H.select_analysis",
        "Ω.A.L0.TAB.03",
        "{code:null,max_attempt:1}",
        10000,
    ),
    (
        "Ω.A.L4.P4.03",
        "트리 시료 선택",
        "H",
        "Ω.A.L0.TAB.03, Ω.A.L0.L1.03",
        "P4.03.1..P4.03.9 tree loop",
        "CMP tree selection ok",
        "{code:E_P4_TREE,max_attempt:3,retry_delay_ms:250}",
        30000,
    ),
    (
        "Ω.A.L4.P4.04",
        "트리 우클릭",
        "H",
        "Ω.A.L4.P4.03 ok",
        "P4.04 rclick tree center",
        "CMP rclick sent",
        "{code:null,max_attempt:1}",
        10000,
    ),
    (
        "Ω.A.L4.P4.05",
        "분석방법 불러오기 메뉴",
        "H",
        "Ω.A.L4.P4.04 ok",
        "P4.05 popup 분석방법+불러",
        "CMP menu item clicked",
        "{code:null,max_attempt:1}",
        15000,
    ),
    (
        "Ω.A.L4.P4.06",
        "MTD 파일 대화상자",
        "H|F",
        "Ω.A.L4.P4.05 ok",
        "P4.06a..P4.06g dialog path",
        "CMP dialog closed ok",
        "{code:E_P4_MTD_DLG,max_attempt:2,retry_delay_ms:400,fallback:F}",
        30000,
    ),
    (
        "Ω.A.L4.P4.07",
        "MTD 로드 대기",
        "W",
        "Ω.A.L4.P4.06 ok",
        "P4.07 WAIT 2000",
        "CMP elapsed>=2000",
        "{code:null,max_attempt:1}",
        3000,
    ),
    (
        "Ω.A.L4.P4.08",
        "피크 데이터 검증",
        "E",
        "Ω.A.L4.P4.07 ok",
        "P4.08 TASK verify_peak_table_has_data",
        "TASK numeric>=1",
        "{code:E_VERIFY_PEAK,max_attempt:1}",
        30000,
    ),
]


def main() -> None:
    lines = [
        "# GC1 Runtime 설계 — PART 2a: L4 P0~P4 (7필드 전량, T13)",
        "",
        "> 상위: [GC1_RUNTIME_DESIGN.md](GC1_RUNTIME_DESIGN.md)",
        "> action sub-leaf: [PART2_L4](GC1_RUNTIME_DESIGN_PART2_L4.md)",
        "",
        "---",
        "",
        "## §L4-P0~P4 atom registry (36 atoms)",
        "",
        "| atom_id | channel | pre_probe[] | post_probe[] | on_fail | timeout_ms |",
        "|---------|---------|-------------|--------------|---------|------------|",
    ]
    for row in ATOMS:
        aid, _title, ch, pre, _act, post, fail, tmo = row
        lines.append(f"| {aid} | {ch} | {pre} | {post} | {fail} | {tmo} |")

    lines += ["", "---", ""]
    for row in ATOMS:
        aid, title, ch, pre, act, post, fail, tmo = row
        lines += [
            f"### {aid} — {title}",
            "",
            "| 필드 | 값 |",
            "|------|-----|",
            f"| id | {aid} |",
            f"| channel | {ch} |",
            f"| pre_probe | [{pre}] |",
            f"| action | [{act}] |",
            f"| post_probe | [{post}] |",
            f"| on_fail | {fail} |",
            f"| timeout_ms | {tmo} |",
            "",
        ]

    lines += [
        "## §T13 leaf count",
        "",
        "| block | atoms | action leaves (PART2) |",
        "|-------|-------|----------------------|",
        "| P0 | 6 | 38 |",
        "| P1 | 11 | 18 |",
        "| P2 | 5 | 9 |",
        "| P3 | 6 | 22 |",
        "| P4 | 8 | 28 |",
        "| **7필드 registry** | **36** | **115** |",
        "",
        "*T13 complete — pre/post probe ID per atom*",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} atoms={len(ATOMS)}")


if __name__ == "__main__":
    main()
